- README.md
- doc/release-process.md
> Add step-by-step documentation for the release process

- CHANGELOG.md
- migrate answer database table into Radio and ShortText
> release-002

- README.md
- script/console
- Scripts to Rule Them All: console edition
> Script to conventionally start a rails console with docker

- doc/release-process.md
Make some updates to the release process Slack message.
> Update deployment Slack message

- app/controllers/journeys_controller.rb
- app/models/step.rb
- app/presenters/step_presenter.rb
- app/views/journeys/show.html.erb
- spec/models/step_spec.rb
- spec/presenters/step_presenter_spec.rb
Based on https://github.com/DFE-Digital/buy-for-your-school/pull/71
I recently added a method into the Step model that I would have liked to add to a Presenter, this small change does that refactor so the next view logic is easier to add.
> Refactor step view logic into presenter

- db/schema.rb
This was being changed automatically and will continue to do so unless one of us commits it.
> Rails 6.1 migrations updated the schema comment

- CHANGELOG.md
- app/controllers/answers_controller.rb
- spec/factories/answer.rb
- spec/features/visitors/anyone_can_edit_their_answers_spec.rb
Based on https://github.com/DFE-Digital/buy-for-your-school/pull/110
Checkbox answers can be edited in the same way as other question types.
> (252) Users can edit checkbox answers

- CHANGELOG.md
- app/controllers/journeys_controller.rb
- app/services/find_all_journey_answers.rb
- spec/services/find_all_journey_answers_spec.rb
- straight refactor to move some heavy controller code into a class with unit test coverage
> Refactor answer finding into a tested service

- CHANGELOG.md
- app/views/pages/planning_start_page.html.erb
- config/locales/en.yml
- spec/features/visitors/anyone_can_see_a_planning_start_page_spec.rb
Update the start page content with revised copy.
> Update start page content

- CHANGELOG.md
- app/controllers/journeys_controller.rb
- app/models/number_answer.rb
- app/models/step.rb
- app/presenters/number_answer_presenter.rb
- app/services/answer_factory.rb
- app/services/create_journey_step.rb
- app/services/find_all_journey_answers.rb
- app/views/steps/number.html.erb
- config/environments/test.rb
- db/migrate/20210127154732_create_number_answer.rb
- db/schema.rb
- spec/factories/answer.rb
- spec/factories/step.rb
- spec/features/visitors/anyone_can_complete_a_journey_spec.rb
- spec/fixtures/contentful/categories/number-question.json
- spec/fixtures/contentful/sections/number-section.json
- spec/fixtures/contentful/steps/number-question.json
- spec/presenters/number_answer_presenter_spec.rb
- spec/services/answer_factory_spec.rb
- Users can answer questions which expect a number
- An exception is rasied when AnswerFactory receives an unexpected question type
> Users can answer questions which expect a number

- spec/features/visitors/anyone_can_complete_a_journey_spec.rb
- spec/fixtures/contentful/categories/nil-help-text.json
- spec/fixtures/contentful/sections/nil-help-text-section.json
- spec/fixtures/contentful/steps/nil-help-text.json
We thought that an empty help text may expose a bug in the code. This test makes sure that it doesn't.
> Add test to make sure empty help text works as expected

- app/views/journeys/show.html.erb
- spec/features/visitors/anyone_can_complete_a_journey_spec.rb
> Correct landing page/tasklist heading

- CHANGELOG.md
- app/controllers/answers_controller.rb
- app/views/journeys/_step_list.html.erb
- spec/features/visitors/anyone_can_complete_a_journey_spec.rb
- spec/features/visitors/anyone_can_edit_their_answers_spec.rb
Users are returned to the same place in the task list after answering a question
> Users return to same place in task list after answering a question

- Dockerfile
Removes `COPY . .` in the Dockerfile, and only `COPY`'s required files
> Dockerfile to only copy required files

- .github/workflows/deploy.yml
- script/deploy-terraform
- script/docker-push-ghcr
- terraform/app/generate-app-env-yml
Adds a `deploy` workflow, which triggers on pushes to `develop`/`main`, which runs scripts to:
- build the image
- push the image to ghcr.io
- deploy terraform
Required GitHub secrets:
- `GHCR_USERNAME`
- `GHCR_PASSWORD`
- `GHCR_REPO`
- `CF_USER`
- `CF_PASSWORD`
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
Terraform variables can be added to GitHub secrets, by prepending them with `{ENV_NAME}_TF_VAR_`
Application environment variables can be added to GitHub secrets, by prepending them with `APP_ENV_{ENV_NAME}_`
> Deploy with GitHub actions

- script/deploy-terraform
Fixes the `APP_ENV_*` key truncating, so that the correct number of characters are removed
> Fix APP_ENV_* key truncating

- script/deploy-terraform
Remove quotes from jq variable (becomes literal `$e`)
> Remove quotes from jq variable

- terraform/app/cdn.tf
> Add cdn service instance

- CHANGELOG.md
- auto deploy research and preview environments
> release-008

- .github/workflows/deploy.yml
.. automatically on git pushes to the branch named "research"
> Deploy research environment

- terraform/app/locals.tf
- terraform/app/logs.tf
- terraform/app/variables.tf
- terraform/app/web-app.tf
- terraform/app/web-worker.tf
* Creates a user-provided service, and binds it to the applications
* `<ENV>_TF_VAR_syslog_drain_url` GitHub secrets need to be created for
this to launch
> Add log stream service

- doc/console-access.md
Correct reference: https://docs.cloud.service.gov.uk/get_started.html#deploy-a-test-static-html-page
> Fix space selection documentation

- doc/architecture/decisions/0012-use-logit-for-application-logs.md
[We recently adding log stream support](https://github.com/DFE-Digital/buy-for-your-school/pull/293). As it was configured generically without requiring us to express a choice of which log stream we'd be using, this PR exists seperately to document why we are using Logit.
> ADR to describe logging choice

- CHANGELOG.md
- fix multiple specification fields
- content security policy
- remove humans.txt
> release-009

- .env.example
- .env.test
- CHANGELOG.md
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- spec/features/visitors/anyone_can_see_the_service_banners_spec.rb
- spec/features/visitors/anyone_can_see_the_service_components_spec.rb
- spec/helpers/application_helper_spec.rb
Add header and footer information for feedback and data requests
Header
Footer
> Add header and footer information for feedback and data requests

- doc/dfe-sign-in.md
This now reflects the current state.
> Update documentation on DSI environment usage

- app/views/tasks/show.html.erb
- config/locales/en.yml
Fixes some visual glitches with the task view
> Refine task question display

- config/initializers/content_security_policy.rb
Simple line removal to avoid code duplication
> Remove line duplication for security nonce generator

- app/views/journeys/show.html.erb
- spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
- spec/features/school_buying_professionals/view_existing_journeys_spec.rb
The back button journey now matches the user journey
> Make breadcrumb journey match the user journey

- Brewfile
- script/bootstrap
- script/test
- script/update
To closer follow the Scripts To Rule Them All pattern, these scripts will automate updating dependencies and performing migrations. They are also run automatically as part of script/test.
`script/update` and by extension `script/bootstrap` are run automatically as part of `script/test`.
Since these actions are idempotent they do not interfere with the setup actions already taken by the `Dockerfile` during CI.
> Add script/update and script/bootstrap

- CHANGELOG.md
- app/controllers/tasks_controller.rb
- app/views/tasks/show.html.erb
- config/locales/en.yml
- spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
The link to continue the current task questions is replaced with a link to the next task if it is incomplete
> Continue to the next task

- .env.example
- .env.test
- .ruby-gemset
- Brewfile
- Brewfile.example
- Gemfile
- Gemfile.lock
- app/controllers/journey_maps_controller.rb
- app/controllers/journeys_controller.rb
- app/controllers/tasks_controller.rb
- doc/getting-started.md
- docker-compose.yml
- script/bootstrap
- improve bootstrapping for new developers
- open ports in docker-compose development environment
- do not rescue controller errors in development
- add extra debugging tools in development
- suggest ASDF for package management
- promote developing against containerised services
- add extra tools to Brewfile
- make Brewfile optional
> Update development environment and getting started documentation

- lib/tasks/default.rake
- Removed duplicated default Rake task
> #113: Tidy default rake task

- .erdconfig
- Brewfile.example
- Gemfile
- Gemfile.lock
- lib/tasks/auto_generate_diagram.rake
- Add rails-erd dependency
- Add auto-generated task to produce an ERD on database migration
> #150: Auto ERD

- .github/workflows/continuous-integration.yml
- README.md
- doc/architecture/decisions/0017-implement-codeclimate-tool.md
- package-lock.json
Added code climate badges (Maintainability & Test Coverage) to readme. Modified the CI github action to report coverage to codeclimate
> WIP Added code climate badges

- README.md
- doc/clean-up.md
- doc/getting-started.md
- script/spec
- Add convenience script `script\spec` that runs our tests within Docker.
- Update documentation with `doc\clean-up.md` that shows how to kill and remove running containers and volumes.
> #112: Utility script for test suite in Docker

- .gitignore
Ignore .tool-verions (preferred file convention for ASDF tooling)
> Ignore tool-verions file

- config/initializers/better_errors.rb
Enable BetterErrors access when running in Docker
> Enable BetterErrors in Docker dev env

- README.md
- script/test
I've commented out the CC tool and removed it's badge (this needs further investigation) - will reach out to CC support as there is no output from the reports they have received.
> Comment out CC Test Reporter & removed badge

- .github/pull_request_template.md
Update Github pull request template for the new team
> Update Github PR template

- app/services/get_entry.rb
- app/services/get_steps_from_task.rb
- app/services/record_action.rb
- app/services/save_answer.rb
- app/services/toggle_additional_steps.rb
- spec/factories/journey.rb
- spec/factories/step.rb
- spec/features/dashboard/dashboard_spec.rb
- spec/features/steps/additional_steps_spec.rb
- spec/services/toggle_additional_steps_spec.rb
Fix bug caused by not refreshing state once additional questions had been toggled
> Fix for toggling additional steps and missing feature coverage

- config/environments/development.rb
- doc/getting-started.md
- NB: Nota bene, to draw attention (inside methods for example)
- DSI: external authentication service related
- CMS: external content service related
> Custom annotation tags

- doc/cloud-foundry-utilities.md
Added doc to describe how to export data from envs in Cloud Foundry to CSV file.
> Doc for exporting CSV data from CF envs

- spec/support/shared/incomplete_journey.rb
- spec/support/shared/new_journey.rb
- all steps are visible and incomplete
- the incomplete context inherits this
> Extract shared context of new journey

- doc/cloud-foundry-utilities.md
- Updated instructions as per @peterdavidhamilton feedback that I missed - helps avoid copy and paste errors.
> Updated Export Instructions

- app/controllers/api/contentful/categories_controller.rb
- spec/requests/api/contentful/webhook_upsert_category_spec.rb
- Added Rollbar event for processing publish category webhook
> Rollbar Category Webhook

- app/controllers/steps_controller.rb
- config/locales/en.yml
- spec/features/self-serve/steps/skip_question_spec.rb
- ensure the user is taken back to the task summary page after skipping the last step
> Skip button navigation fix

- app/controllers/api/contentful/categories_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/journeys_controller.rb
- app/views/categories/index.html.erb
- db/migrate/20210825142114_add_slug_to_categories.rb
- db/migrate/20210825142733_add_slugs_to_existing_categories.rb
- db/schema.rb
- spec/factories/category.rb
- spec/features/self-serve/categories/categories_spec.rb
- spec/features/self-serve/errors/content_errors_spec.rb
- spec/features/self-serve/journeys/task_list/view_hidden_spec.rb
- spec/migrations/self-serve/add_slugs_to_existing_categories_spec.rb
- spec/requests/self-serve/api/contentful/webhook_upsert_category_spec.rb
- spec/requests/self-serve/contentful_caching_spec.rb
- spec/support/journey_helpers.rb
- add `slug` column to `categories`
- replace `category.id` with `category.slug` in form selectors
> Use category slug as an HTML identifier

- spec/models/self-serve/category_spec.rb
- spec/models/self-serve/checkbox_answers_spec.rb
- spec/models/self-serve/currency_answer_spec.rb
- spec/models/self-serve/long_text_answer_spec.rb
- spec/models/self-serve/radio_answer_spec.rb
- spec/models/self-serve/short_text_answer_spec.rb
- spec/models/self-serve/single_date_answer_spec.rb
- spec/models/self-serve/step_spec.rb
- spec/models/self-serve/user_spec.rb
Removed rouge require rails helpers from specs
> Removed rouge require rails helpers

- doc/cloud-foundry-utilities.md
- doc/dfe-sign-in.md
- correct formatting error
- fix hyperlink to other doc
- make links to DSI clickable
> Update markdown documentation

- app/models/support/agent.rb
Added an informative comment delineating the purpose of the `Agent` class and what it means in Business terms to minimise confusion.
> Add informative comment delineating class purpose

- app/controllers/design_controller.rb
- app/presenters/category_presenter.rb
- app/presenters/journey_presenter.rb
- app/views/categories/index.html.erb
- app/views/journeys/show.html.erb
- app/views/pages/specifying_start_page.html.erb
- app/views/specifications/show.html.erb
- config/locales/en.yml
- spec/features/self-serve/categories/categories_spec.rb
- spec/features/self-serve/dashboard/access_spec.rb
- spec/features/self-serve/dashboard/new_journey_spec.rb
- spec/features/self-serve/journeys/category_spec.rb
- spec/features/self-serve/journeys/download_spec.rb
- spec/features/self-serve/landing/body_spec.rb
- spec/features/self-serve/support_requests/new_support_request_spec.rb
- spec/presenters/self-serve/category_presenter_spec.rb
- spec/presenters/self-serve/journey_presenter_spec.rb
- spec/support/contentful_helpers.rb
- spec/support/journey_helpers.rb
- updated content on the start, category, journey and specification pages
> Content updates

- config/schedule.yml
Updates scheduler to use the correct namespacing for the RefreshSchoolsJob
> Add namespacing to RefreshSchoolsJob in scheduler

- app/views/support_request_submissions/show.html.erb
> add in correct classes to links for styling

- config/static/next_steps_catering.md
- config/static/next_steps_mfd.md
External links on the next steps pages now open in a new window.
> Make external links on next steps pages open in a new window

- config/static/next_steps_catering.md
- config/static/next_steps_mfd.md
Use target="_blank" on external links of the next steps mfd page to ensure pages open in a new tab/window.
> Use target="_blank" on external links on the next steps mfd page

- app/views/support_request_submissions/show.html.erb
- config/locales/en.yml
- config/static/accessibility.md
- spec/features/self-serve/support_requests/submit_support_request_spec.rb
All references to 5 working days for support request sla changed to 2 working days
> Correct 5 working days to 2 working days for sla

- config/static/privacy_notice.md
- added required text to privacy_notice.md
Link to the ticket with requested changes:
https://trello.com/c/T0fxpRHe/798-update-privacy-notice-in-footer-of-the-service
> Updated privacy notice in the footer of the service

- config/static/terms_and_conditions.md
- updated with required text for terms_and_conditions.md
Link to the ticket with requested changes:
https://trello.com/c/I22DnmNs/811-update-terms-conditions
> Updated terms & conditions

- lib/school/information.rb
- with a 1GB memory restriction, a batch size of 1k is able to run unimpeded 
- updates 22k records in 5 mins
```
Support::Organisation
id: "UUID"
establishment_type_id: "UUID"
number: "1234"
urn: "123456"
ukprn: "12345678"
name: "The School"
rsc_region: "North-West London and South-Central England"
telephone_number: ""
address: {"town"=>"", "county"=>"", "street"=>"", "locality"=>"", "postcode"=>""}
contact: {"role"=>"", "title"=>"", "last_name"=>"", "first_name"=>""}
local_authority: {"code"=>201, "name"=>"City of London"}
phase: "primary"
gender: "mixed"
status: "opened"
created_at: "Time"
updated_at:  "Time"
opened_date: "Time"
```
> Remove Garbage Collector

- config/locales/en.yml
> Change CTA button text on Request support confirmation page

- CHANGELOG.md
- app/assets/javascripts/application.js
- app/assets/javascripts/components/autocomplete/autocomplete.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_autocomplete.scss
- app/controllers/support/schools_controller.rb
- app/models/support/organisation.rb
- app/views/components/_autocomplete.html.erb
- config/environments/production.rb
- config/routes.rb
- doc/components/autocomplete.md
- package-lock.json
- package.json
- spec/factories/support/establishment_type.rb
- spec/factories/support/organisation.rb
- spec/models/support/organisation_spec.rb
- spec/requests/support/schools_spec.rb
- Addition of [alphagov/accessible-autocomplete](https://github.com/alphagov/accessible-autocomplete)
- Glue code to enable quick and declaritive use of [alphagov/accessible-autocomplete](https://github.com/alphagov/accessible-autocomplete) using data attributes.
- Schools api endpoint to demonstrate (and to be used in future work)
Refer to `docs/components/autocomplete.md`
https://user-images.githubusercontent.com/1352756/141455844-52ef7e12-42b8-4143-8ef7-17b13c9bd019.mov
> Introduce accessible autocomplete component

- app/forms/support/case_assignment_form.rb
- app/forms/support/case_categorisation_form.rb
- app/forms/support/case_email_content_form.rb
- app/forms/support/case_email_type_form.rb
- app/forms/support/case_resolution_form.rb
- app/forms/support/concerns/validatable_form.rb
- app/forms/support_form.rb
- app/services/create_user.rb
- app/services/current_user.rb
- app/services/document_formatter.rb
- app/services/downloader.rb
- app/services/emails/document.rb
- app/services/exporter.rb
- app/services/liquid_parser.rb
- app/services/specification_renderer.rb
- app/services/submit_support_request.rb
- app/services/support/seed_categories.rb
- app/services/support/seed_groups.rb
- app/services/support/seed_schools.rb
- lib/dsi/client.rb
- lib/dsi/user.rb
- lib/notify/email.rb
- lib/school/information.rb
- update yard documentation for dry-initializer `options` and `params`
> Correct yard syntax for dry-initialiser classes

- config/static/terms_and_conditions.md
> updated terms and conditions

- CHANGELOG.md
- doc/dfe-sign-in.md
- doc/getting-started.md
Orphaned [commits](https://github.com/DFE-Digital/buy-for-your-school/pull/642) that update getting started documentation and CHANGELOG
> Docker tooling documentation

- app/services/content/page/build.rb
- app/services/content/page/get.rb
- config/static/terms_and_conditions.md
- spec/services/self-serve/content/page/build_spec.rb
- spec/services/self-serve/content/page/get_spec.rb
- add `get` and `build` services for `Pages`
> Page services

- doc/webhooks.md
- Info regarding the additional two webhooks and ngrok setup
> Update webhook documentation

- Dockerfile
- doc/getting-started.md
- script/console
- script/docker-push-ghcr
- deploy the production stage
- open an existing dev console if the server is already running
- append the bundled bin to PATH for use in the deployment env
> Docker tweaks to dev and prod

- README.md
> Rename service in readme

- CHANGELOG.md
- app/controllers/support/cases_controller.rb
- app/controllers/support/migrations/base_controller.rb
- app/controllers/support/migrations/hub_cases_controller.rb
- app/controllers/support/migrations/previews_controller.rb
- app/forms/support/case_hub_migration_form_schema.rb
- app/presenters/support/case_presenter.rb
- app/presenters/support/organisation_presenter.rb
- app/services/submit_support_request.rb
- app/services/support/create_interaction.rb
- app/views/support/cases/_row.erb
- app/views/support/cases/_school_details.html.erb
- app/views/support/cases/case_history/_interaction.html.erb
- app/views/support/cases/show.html.erb
- app/views/support/migrations/hub_cases/forms/_case_form.html.erb
- app/views/support/migrations/previews/new.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- db/migrate/20211129091202_remove_org_strings_from_case.rb
- db/schema.rb
- spec/factories/support/case.rb
- spec/factories/support/organisation.rb
- spec/features/support/case_school_details_spec.rb
- spec/models/support/case_spec.rb
- spec/presenters/support/case_presenter_spec.rb
- spec/presenters/support/organisation_presenter_spec.rb
- spec/services/self-serve/submit_support_request_spec.rb
- spec/services/support/create_interaction_spec.rb
- Removed org strings from case, views to render org details from org object
- Added create interaction service & spec
> Case hub interactions

- app/controllers/support/cases/assignments_controller.rb
- app/models/support/case.rb
- app/views/support/cases/show.html.erb
- config/locales/en.yml
- spec/features/support/case_assignment_spec.rb
- spec/features/support/case_resolution_spec.rb
- spec/features/support/case_school_details_spec.rb
- spec/features/support/case_summary_spec.rb
- spec/features/support/emails/agent_sends_basic_email_spec.rb
- spec/features/support/emails/agent_sends_templated_email_spec.rb
- spec/features/support/interactions/list_interactions_spec.rb
- spec/features/support/interactions/new_interaction_spec.rb
- spec/models/support/case_spec.rb
Change the status "open" to "opened" on Support::Case model to avoid method name collision
> Change open status to opened on Support::Case

- app/presenters/support/case_presenter.rb
- app/services/submit_support_request.rb
- app/views/support/cases/case_history/_support_request.html.erb
- config/locales/en.yml
- spec/features/self-serve/pages/show_spec.rb
- spec/features/self-serve/support_requests/submit_support_request_spec.rb
- spec/presenters/support/case_presenter_spec.rb
- spec/services/self-serve/submit_support_request_spec.rb
- Updated 'additional data' styling for the support_request interaction,
- Updated case presenter to account for nil organisation
- Submit support request to use CreateCase & Create Interaction services
> Updated support request additional data (interaction) styling

- db/migrate/20211202164607_add_savings_attributes_to_support_case.rb
- db/schema.rb
- spec/models/support/case_spec.rb
Adds savings attributes to case model.
> [169] add savings attributes to support_cases

- app/models/support/case.rb
- app/models/support/procurement.rb
- db/migrate/20211202151356_create_support_procurements.rb
- db/migrate/20211202153336_add_procurement_to_case.rb
- db/schema.rb
- spec/factories/support/procurement.rb
- spec/models/support/case_spec.rb
- spec/models/support/procurement_spec.rb
- create `procurement` table and model
- create a `case` to `procurement` relationship
> Procurement data model

- CHANGELOG.case_management.md
- CHANGELOG.md
- doc/architecture/decisions/0020-use-accessible-autocomplete-for-autocomplete-fields.md
- add missing CHANGELOG items and tidy descriptions
- add a template for linking to commits/PRs in the CHANGELOG for future releases
> Tidy CHANGELOG for release

- app/controllers/support/application_controller.rb
- app/controllers/support/cases/application_controller.rb
- app/controllers/support/cases_controller.rb
- spec/features/support/interactions/list_interactions_spec.rb
- spec/requests/support/authorisation_spec.rb
- spec/requests/support/schools_spec.rb
- spec/support/sign_in_helpers.rb
- Modified Support::ApplicationController to ensure agent is present when accessing the case management system
- Added specs
- Fixed interaction spec to have agent
> Ensure agent cant be nil

- .rubocop_todo.yml
- Gemfile.lock
- lib/microsoft_graph/microsoft_graph.rb
- lib/microsoft_graph/resource/attachment.rb
- spec/lib/microsoft_graph/resource/attachment_spec.rb
- Added attachment resource to Microsoft Graph lib
Consider UI
> Attachments incoming email

- app/controllers/support/cases/procurement_details_controller.rb
- app/controllers/support/concerns/has_date_params.rb
- app/forms/support/case_procurement_details_form.rb
- app/forms/support/case_procurement_details_form_schema.rb
- app/models/support/procurement.rb
- app/presenters/support/case_presenter.rb
- app/presenters/support/procurement_presenter.rb
- app/views/support/cases/_procurement_details.html.erb
- app/views/support/cases/procurement_details/edit.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- spec/factories/support/case.rb
- spec/factories/support/procurement.rb
- spec/features/support/case_procurement_details_spec.rb
- spec/features/support/procurement-details/edit_spec.rb
- spec/forms/support/case_procurement_details_form_spec.rb
- spec/models/support/procurement_spec.rb
- spec/presenters/support/case_presenter_spec.rb
- spec/presenters/support/procurement_presenter_spec.rb
- add route, controller, and view to edit `procurement` details
- add form object and schema to capture and validate `procurement` details
> Update procurement details form

- app/models/support/case.rb
- app/models/support/email.rb
- db/migrate/20211215115111_create_support_emails.rb
- db/schema.rb
- spec/factories/support/email.rb
- spec/factories/support/emails.rb
- spec/models/support/email_spec.rb
Adds an email model for supported.
> Add email model for support cases

- app/services/create_user.rb
Disables the roles method in the CreateUser service
> Temporarily disable roles in CreateUser service

- app/controllers/admin_controller.rb
- app/views/admin/show.html.erb
- config/locales/en.yml
- spec/features/self-serve/admin/show_spec.rb
- add download button to `/admin` for user activity log `csv`
> Data download link

- .github/workflows/health-check.yml
Uses [jtalk/url-health-check-action@v2](https://github.com/marketplace/actions/url-health-check) to check our environments are up and [Gamesight/slack-workflow-status@master](https://github.com/marketplace/actions/slack-workflow-notifications) to notify slack
> Github actions workflow to check health of the service

- .github/workflows/health-check.yml
> tweak healthcheck

- .github/workflows/health-check.yml
> add research to healthchecks

- spec/features/self-serve/pages/show_spec.rb
This is breaking develop.
Current test was failing depending on the date due to extra spaces in the date formatting if the day was less than 10.
Fix is just to code in the date so it works the same regardless of date.
> Ensure test works every day

- app/forms/support/case_hub_migration_form.rb
- db/schema.rb
- spec/forms/support/case_hub_migration_form_spec.rb
- add check for nw_hub and sw_hub according to identification number
> Case source being set incorrectly on create a case

- app/forms/support/case_hub_migration_form_schema.rb
- config/locales/validation/support/en.yml
- spec/features/support/case_migration_spec.rb
- add validation to the `school_urn` field in the hub migration form
> Hubs migration when there is no establishment

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- db/migrate/20220112104638_change_active_storage_attachments_record_id_to_uuid.rb
- db/schema.rb
active_storage_attachments record_id field needs to be uuid not biginit
> Fix active storage schema

- app/services/support/incoming_emails/case_assignment.rb
- spec/services/support/incoming_emails/case_assignment_spec.rb
Notify templates will contain the case reference going forward, a change in phrase required the automatic case assignment logic to change also.
> Tweak to email attachment format

- app/forms/support/case_contracts_form.rb
- app/forms/support/case_contracts_form_schema.rb
- app/forms/support/case_procurement_details_form.rb
- app/forms/support/case_procurement_details_form_schema.rb
- app/forms/support/schema.rb
- config/locales/validation/support/en.yml
- db/schema.rb
- lib/date_builder.rb
- lib/types.rb
- renamed type for clarity
- have a single function responsible for handling data hashes 
(including the rescuing)
- construct rules manually
> Reusability in validation rules

- config/support/establishment_types.yml
- spec/services/support/seed_groups_spec.rb
Add additional establishment type to the supported case management which will persist extra organisations to the database.
Run the task to seed the new UTC type.
> Add UTCs as supported establishment types

- config/sidekiq.yml
> add support to sidekiq queues

- app/models/support/email.rb
- app/models/support/email_attachment.rb
- spec/models/support/email_attachment_spec.rb
- spec/models/support/email_spec.rb
- Make sure attachment content_id and is_inline is recorded
- Put attachment download job inline to fix "MicrosoftGraph::ClientSession::GraphRequestFailedError: Code: ApplicationThrottled, Message: Application is over its MailboxConcurrency limit."
> Email attachment tweaks

- app/jobs/support/synchronize_shared_inbox_job.rb
- config/schedule.yml
- spec/jobs/support/synchronize_shared_inbox_job_spec.rb
Email synchronisation doesn't need to be so slow. Importing the entire mailbox + attachments takes 3 seconds.
Increase cadence to every 3 minutes.
> Increase email sync cadence

- app/models/support/email.rb
- app/views/support/cases/_row.erb
- app/views/support/cases/_school_details.html.erb
- app/views/support/cases/_status_badge.html.erb
- app/views/support/cases/show.html.erb
- config/locales/en.yml
- db/migrate/20220118155549_add_action_required_to_support_cases.rb
- db/schema.rb
- spec/factories/support/case.rb
- spec/features/support/case_list_spec.rb
- spec/features/support/case_view_spec.rb
- spec/models/support/email_spec.rb
Case can display if there is an action required of it's case workers by setting a flag.
This flag is automatically set when a new email comes in for the case.
> Case action status

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/base/_misc.scss
- app/controllers/support/email_read_status_controller.rb
- app/models/support/email.rb
- app/views/support/cases/case_history/_interaction.html.erb
- app/views/support/cases/emails/_unread_badge.html.erb
- app/views/support/emails/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220119145844_add_is_read_to_support_emails.rb
- db/schema.rb
- spec/features/support/emails/agent_can_mark_email_as_read_spec.rb
- spec/models/support/case_spec.rb
- spec/models/support/email_spec.rb
- spec/requests/support/email_read_status_spec.rb
Agent can see unread flag next to unread emails and mark emails as read / remark them as unread again.
Marking all emails as read will remove "action required" status from the case.
> Email unread/read flag management

- app/controllers/support/cases/resolutions_controller.rb
- spec/features/support/case_resolution_spec.rb
When resolving a case we need to keep the agent assigned as before.
> Keep agent assigned when resolving a case

- app/models/support/email.rb
- app/views/support/emails/show.html.erb
- spec/features/support/emails/agent_sees_details_of_an_email_spec.rb
- spec/models/support/email_spec.rb
Some changes that have come out of testing.
- Email interactions were not being created due to body preview being an empty string (violating interaction validations)
- Email show page breaks if no case attached (due to hard coding of case reference)
> Various fixes for email

- app/assets/javascripts/application.js
- app/assets/javascripts/components/close-tab-link.js
- app/controllers/support/email_read_status_controller.rb
- app/controllers/support/emails_controller.rb
- app/models/support/email.rb
- app/views/support/emails/show.html.erb
- db/schema.rb
- spec/models/support/case_spec.rb
- spec/models/support/email_spec.rb
- spec/requests/support/email_read_status_spec.rb
Currently the email interactions are listed in creation order not email received order so it looks strange in case history.
> Email interactions are ordered by email sent date

- app/controllers/framework_requests_controller.rb
- app/presenters/support/interaction_presenter.rb
* fixes case management case show page not rendering due to interaction presenter `additional_data` assignment bug
> faf - rename blank referer

- app/controllers/support/organisations_controller.rb
- app/forms/framework_support_form.rb
- app/views/framework_requests/steps/_step_4.html.erb
- config/locales/en.yml
- add "Search for your school" page
> #243 FaF Support Request - Search for a school

- CHANGELOG.md
- app/controllers/sessions_controller.rb
- app/controllers/support/pages_controller.rb
- app/models/user.rb
- spec/features/self-serve/auth/supported_user_spec.rb
- spec/models/self-serve/user/user_internal_spec.rb
- redirect to case management's entry point for users in the proc ops org
> Add redirect to case management for agents

- app/controllers/admin_controller.rb
- app/views/admin/show.html.erb
- config/locales/en.yml
- spec/features/self-serve/admin/show_spec.rb
- Add ability to download activity log items in json
> The KPI 'Specify user activity' data to be in JSON format

- config/locales/en.yml
- added missing translations for the FaF interaction
> Missing translations

- app/controllers/support/cases/contact_details_controller.rb
- app/forms/support/case_contact_details_form.rb
- app/forms/support/case_contact_details_form_schema.rb
- app/views/support/cases/_school_details.html.erb
- app/views/support/cases/contact_details/edit.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- spec/features/support/agent_can_set_case_contact_spec.rb
Case worker can update contact details
> Case worker can update contact details

- CHANGELOG.case_management.md
- CHANGELOG.md
Add links to bug fix and feature PRs
Update https://dfedigital.atlassian.net/wiki/spaces/GHBFS/pages/3468230657/Release+19
> Update CHANGELOG for release 19 changes

- CHANGELOG.md
- app/controllers/admin_controller.rb
- app/views/admin/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/self-serve/admin/show_spec.rb
- add `users` table download in JSON to `/admin`
> Add the user table to the KPI download

- app/controllers/framework_requests_controller.rb
fix email disappearing on name/email update action
> faf - fix email disappearing on name/email update action

- app/controllers/framework_requests_controller.rb
> faf - nil urn bug

- app/views/framework_requests/index.html.erb
- config/locales/en.yml
- updated content for faf start page
> Content on FaF start page is incorrect

- config/locales/en.yml
- spec/features/self-serve/faf/check_your_answers_spec.rb
- spec/features/self-serve/faf/create_framework_request_spec.rb
description of problem => description of request
> faf - description of problem => description of request

- app/controllers/framework_request_submissions_controller.rb
- app/controllers/framework_requests_controller.rb
- app/controllers/support/cases/organisations_controller.rb
- app/forms/framework_support_form.rb
- app/forms/framework_support_form_schema.rb
- app/forms/support/case_hub_migration_form.rb
- app/forms/support/case_hub_migration_form_schema.rb
- app/forms/support/case_organisation_form.rb
- app/forms/support/case_organisation_form_schema.rb
- app/services/submit_framework_request.rb
> Add :nocov: flags to facilitate devs with no admin rights

- app/views/framework_requests/index.html.erb
- config/locales/en.yml
Wording changes on faf entrypoint page.
> Wording changes to faf entrypoint page

- app/views/support/cases/index.html.erb
Ensures correct cases are being used for pagination on case maangement
> Correct objects being used for pagination

- app/services/create_user.rb
- config/initializers/school_types.rb
- spec/factories/user.rb
- spec/features/self-serve/auth/supported_user_spec.rb
- allow users belonging to groups (MATs and SATs) to use the service
> FaF Support Request - Modify eligibility check so MATs are eligible

- app/controllers/framework_requests_controller.rb
- app/views/framework_requests/show.html.erb
- app/views/framework_requests/steps/_step_3.html.erb
- app/views/framework_requests/steps/_step_4.html.erb
- app/views/framework_requests/steps/_step_5.html.erb
- app/views/framework_requests/steps/_step_6.html.erb
- app/views/framework_requests/steps/_step_7.html.erb
- spec/features/self-serve/faf/create_framework_request_no_dsi_spec.rb
- spec/features/self-serve/faf/create_framework_request_spec.rb
- spec/features/self-serve/faf/edit_framework_request_spec.rb
Step 3 for the non-dsi faf journey is now choosing School or Group and step 4 is the check your group/school page.
> Add group and school search to the non-dsi faf journey

- CHANGELOG.case_management.md
- CHANGELOG.md
- add missing release with date
> Add release-020 date to CHANGELOGs

- script/spec
- `script/spec` accepts multiple arguments to make changing seed and output format easier within docker
> Pass all arguments to rspec within docker

- CHANGELOG.md
- app/controllers/feedback_controller.rb
- app/forms/feedback_form.rb
- app/forms/feedback_form_schema.rb
- app/helpers/application_helper.rb
- app/models/user_feedback.rb
- app/views/feedback/_details_submitted.html.erb
- app/views/feedback/_feedback_submitted.html.erb
- app/views/feedback/edit.html.erb
- app/views/feedback/new.html.erb
- app/views/feedback/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20220216170254_create_user_feedback.rb
- db/migrate/20220218085717_add_user_data_to_user_feedback.rb
- db/schema.rb
- spec/factories/user_feedback.rb
- spec/features/self-serve/feedback/details_spec.rb
- spec/features/self-serve/feedback/feedback_spec.rb
- spec/features/self-serve/landing/environment_banner_spec.rb
- spec/helpers/self-serve/application_helper_spec.rb
- add user feedback page, model and form
https://user-images.githubusercontent.com/12530193/154666209-80dafbc3-937d-40ac-9ee7-9e2b9d7c12ac.mov
> UR Beta Banner - Feedback page

- app/controllers/feedback_controller.rb
- app/views/feedback/_details_submitted.html.erb
- config/locales/en.yml
- spec/features/self-serve/feedback/details_spec.rb
- spec/features/self-serve/feedback/feedback_spec.rb
- fix content issues in the feedback pages
> Update feedback page content

- .github/pull_request_template.md
- .github/workflows/deploy.yml
- .github/workflows/pr-tasks.yml
- .github/workflows/qa-cleanup.yml
- .github/workflows/qa-deploy.yml
- script/deploy-terraform
- script/empty-s3
- script/install-cf
- script/qa/destroy
- script/qa/seed
- terraform/app/locals.tf
- terraform/app/variables.tf
- New github actions workflow to create a QA app with "in-qa-env" label added
- New github actions workflow to remove a QA app when closing the PR
- Added "cf_space" variable to terraform config
Please complete the following tasks to allow merging of this feature:
Note: Check a task if it is not relevent to this PR.
Note: Please uncheck any relevent tasks if you make further changes to the code.
- Developers should add label "in-qa-env" when opening a PR
- The link to the QA evnironment will be posted as a comment on the PR
- Seeding will run `rails case_management:seed_shared_inbox_emails` and `rails case_management:seed` on the new environment
- @ryantk Will have to manually enable DSI redirect for each environment pending a chat with a DSI dev to automate the process.
> Qa app config and workflows

- .github/pull_request_template.md
- .github/workflows/continuous-integration.yml
- app/controllers/support/cases/emails/content_controller.rb
- app/controllers/support/cases/emails/types_controller.rb
- app/controllers/support/cases/emails_controller.rb
- app/controllers/support/interactions_controller.rb
- app/forms/support/case_email_content_form.rb
- app/forms/support/case_email_content_form_schema.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/email_templates.rb
- app/views/support/cases/case_history/_details.html.erb
- app/views/support/cases/emails/content/edit.html.erb
- app/views/support/cases/emails/content/show.html.erb
- app/views/support/cases/emails/templates/index.html.erb
- app/views/support/interactions/show.html.erb
- config/brakeman.ignore
- config/locales/en.yml
- config/locales/validation/support/en.yml
- db/schema.rb
- script/check-coverage
- script/test
- spec/features/support/emails/agent_sends_basic_email_spec.rb
- spec/features/support/emails/agent_sends_templated_email_spec.rb
- spec/models/support/case_spec.rb
- spec/spec_helper.rb
Ensured that when emails sent from CMS they are recorded correctly in the case history.
Please complete the following tasks to allow merging of this feature:
Note: Check a task if it is not relevent to this PR.
Note: Please uncheck any relevent tasks if you make further changes to the code.
> Record notify email correctly in case history

- app/views/layouts/_navigation_links.html.erb
- app/views/layouts/application.html.erb
- app/views/support/cases/show.html.erb
- spec/features/support/case_tabs_spec.rb
Removed the case owner link from the case history page.
Fixed the main header bar strange spacing issues.
> Remove case worker link

- app/controllers/framework_request_submissions_controller.rb
- app/controllers/framework_requests_controller.rb
- app/controllers/sessions_controller.rb
- app/services/submit_framework_request.rb
- config/locales/en.yml
- spec/controllers/framework_requests_controller_spec.rb
- Changed spellings of 'referer' to 'referrer'
- Added referrer from faf params
Please complete the following tasks to allow merging of this feature:
Note: Check a task if it is not relevent to this PR.
Note: Please uncheck any relevent tasks if you make further changes to the code.
> Referrer on FaF requests

- config/i18n-tasks.yml
- config/locales/en.yml
Replace missing translation keys
> replace removed email template keys

- app/controllers/specifications_controller.rb
- app/views/specifications/show.html.erb
- config/locales/en.yml
fixes:
* sidebar spacing on specification show page
* removes "you have not completed all tasks..." message in .docx when the journey is marked as finished
> correct sidebar and spec document finished message

- app/controllers/support/cases/previews_controller.rb
- app/controllers/support/cases_controller.rb
- app/forms/support/create_case_form.rb
- app/forms/support/create_case_form_schema.rb
- app/models/support/case.rb
- app/models/support/interaction.rb
- app/presenters/support/interaction_presenter.rb
- app/views/support/cases/case_history/_details.html.erb
- app/views/support/cases/forms/_create_case_form.html.erb
- app/views/support/cases/previews/new.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- spec/features/support/case_description_spec.rb
- spec/features/support/case_tabs_spec.rb
- spec/features/support/create_case_spec.rb
- spec/forms/support/create_case_form_spec.rb
- spec/models/support/case_spec.rb
- spec/models/support/interaction_spec.rb
- Add source and problem description to case creation
- Remove hub migration fields
> add case source and problem description to case creation

- config/initializers/rails_semantic_logger.rb
> Dont initialize rails semantic logger in test

- config/initializers/rails_semantic_logger.rb
- script/qa/get-free-dsi-redirect-route
There was a fault in the QA app URL assignment logic, one loop was using 0 based array indexing, the other was not so there was a mismatch and as a reesult qa app 1 was always being picked incorrectly.
> Fix qa url assignment

- app/controllers/support/cases/messages_controller.rb
- app/controllers/support/cases_controller.rb
- app/forms/support/messages/reply_form.rb
- app/forms/support/messages/reply_form_schema.rb
- app/services/support/messages/send.rb
- app/views/support/cases/emails/_read_badge.html.erb
- app/views/support/cases/messages/_actions.html.erb
- app/views/support/cases/messages/_outlook_message.html.erb
- app/views/support/cases/messages/_reply_form.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- spec/features/support/case_attachments/agent_can_save_attachments_to_case_spec.rb
- spec/features/support/emails/agent_can_mark_email_as_read_spec.rb
- spec/features/support/emails/agent_can_send_replies_spec.rb
- spec/forms/support/messages/reply_form_schema_spec.rb
- spec/services/support/messages/send_spec.rb
- add a reply form to incoming Outlook messages
> Add reply form to a message

- app/controllers/support/cases/messages/reply_controller.rb
- app/services/support/messages/send.rb
- app/services/support/messages/templates.rb
- app/views/support/cases/messages/_outlook_message.html.erb
- app/views/support/cases/messages/_reply_form.html.erb
- app/views/support/cases/messages/reply/edit.html.erb
- app/views/support/cases/messages/reply/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/support/emails/agent_can_preview_email_spec.rb
- spec/features/support/emails/agent_can_send_replies_spec.rb
- spec/services/support/messages/templates_spec.rb
- add email preview and edit pages to the new reply flow
> Preview email

- app/services/support/messages/outlook/synchronisation/steps/surface_email_on_case.rb
- spec/services/support/messages/outlook/synchronisation/steps/surface_email_on_case_spec.rb
Sent items should not mark case as action
> Do not mark outgoing messages as action

- app/views/support/cases/messages/replies/_form.html.erb
- config/routes.rb
Messages controller has to be "resources" to allow an id param in the path.
> Fix issue where reply didnt work

- app/assets/stylesheets/components/supported/_messages.scss
- app/views/support/cases/index.html.erb
- app/views/support/cases/searches/index.html.erb
An email in the system is pushing out the entire page due to not having word break.
> Fix word wrap

- app/assets/stylesheets/components/supported/_messages.scss
- app/javascript/components/tinymce.js
- disable the custom TinyMCE context menu
- fix formatting issues in the Messages tab in CMS
> Copy and paste function difficulties in CMS

- config/environments/production.rb
- add missing HTTP headers: `X-Frame-Options`, `X-Content-Type-Options`
> PWNN-364 Missing HTTP Security Headers

- app/controllers/support/cases_controller.rb
- app/views/support/cases/index.html.erb
- config/locales/en.yml
- spec/features/support/case_list_spec.rb
- Removed resolved cases from 'My cases' tab
- Still show resolved cases in 'All cases' tab
- Add 'View my resolved cases' link to the 'My cases' tab that goes to the case search results page with agent and status set to resolved pre-filtered
> Removal of Resolved Cases from "My Cases" List in CMS

- app/presenters/support/case_presenter.rb
> Fix rubocop issue

- .rubocop_todo.yml
- app/controllers/exit_survey/satisfaction_controller.rb
- app/models/exit_survey_response.rb
- db/migrate/20220824084204_add_survey_started_to_exit_survey_responses.rb
- db/schema.rb
- spec/models/exit_survey_response_spec.rb
Record the date an exit survey response goes into in_progress, useful for reporting analysis.
> Record exit survey start date

- .gitignore
- Gemfile.lock
- yarn.lock
> Update gems 280922

- .rubocop_todo.yml
- app/jobs/support/send_exit_survey_job.rb
- app/models/support/case.rb
- app/services/support/messages/outlook/synchronisation/steps/attach_email_to_case.rb
- spec/jobs/support/send_exit_survey_job_spec.rb
- spec/models/support/case_spec.rb
- spec/services/support/messages/outlook/synchronisation/steps/attach_email_to_case_spec.rb
- Make sure to check if email already sent out JUST BEFORE sending it
- Update case notes when an email reopens a case
> Exit survey bugs

- Gemfile.lock
- app/views/framework_requests/index.html.erb
- config/locales/en.yml
- spec/features/self-serve/framework_requests/start_page_spec.rb
- yarn.lock
> Updated request for support page content

- db/migrate/20221012130837_add_trust_name_to_support_organisations.rb
- db/schema.rb
- lib/school/mapper.rb
- lib/school/record_keeper.rb
- lib/school/schema.rb
- spec/lib/self-serve/school/mapper_call_spec.rb
- spec/lib/self-serve/school/record_keeper_spec.rb
- spec/lib/self-serve/school/schema_call_spec.rb
Added "Trusts (name)" from the GIAS CSV to the organisation sync.
> Added trust name to organisations

- .rubocop_todo.yml
- db/migrate/20221014140003_add_more_trust_fields_to_support_organisations.rb
- db/schema.rb
- lib/school/mapper.rb
- lib/school/record_keeper.rb
- lib/school/schema.rb
- spec/lib/self-serve/school/mapper_call_spec.rb
- spec/lib/self-serve/school/record_keeper_spec.rb
- spec/lib/self-serve/school/schema_call_spec.rb
- Added Trust Code and GOR Name
> Add new fields to organisation from spreadsheet

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/framework_requests/base_controller.rb
- app/controllers/framework_requests/start_controller.rb
- app/controllers/framework_requests_controller.rb
- config/application.rb
- lib/middleware/user_journey_tracking.rb
- spec/requests/user_journey/user_journey_tracking_spec.rb
Only track user journeys when it is a human user using the service
> Ignore bots when tracking user journeys

- app/forms/framework_requests/search_for_organisation_form.rb
- spec/forms/framework_requests/search_for_organisation_form_spec.rb
Addresses https://rollbar.com/dfe-digital/GHBS/items/747
- add missing validation to the Search for a school/academy page in the Request for Help form
> Add missing organisation validation in RFH

- lib/middleware/user_journey_tracking.rb
…uests
The current_user_journey helper was not working in non GET requests which is causing framework requests and cases to not be attached correctly to the journey.
> Fix bug where current_user_journey helper doesnt work for non GET requests

- app/assets/stylesheets/components/_page.scss
- fix link styling in Create A Spec
- change numbered list styling for sub-lists
> Specification CSS updates

- app/controllers/support/towers_controller.rb
- app/forms/support/case_filter_form.rb
- app/helpers/support/case_statistics_helper.rb
- app/models/support/case.rb
- app/models/support/case_statistics.rb
- app/views/support/case_statistics/show.html.erb
- app/views/support/case_statistics/towers/show.html.erb
- app/views/support/cases/forms/_simple_case_filters.html.erb
- config/locales/en.yml
- spec/features/support/case_statistics_spec.rb
- spec/features/support/towers_spec.rb
- spec/helpers/support/case_statistics_helper_spec.rb
- add links to the case statistics pages that lead to the tower view with relevant cases
> Add links to case statistics

- app/controllers/framework_requests/confirm_sign_in_controller.rb
- app/views/framework_requests/confirm_sign_in/index.html.erb
- spec/features/self-serve/framework_requests/create_framework_request_dsi_spec.rb
- set the inferred organisation in the RFH DSI journey
> Assign inferred org in RFH form

- app/models/framework_request.rb
- app/models/support/case.rb
- app/presenters/framework_request_presenter.rb
- app/services/submit_framework_request.rb
- app/views/framework_requests/show.html.erb
- app/views/support/cases/_case_attachments.html.erb
- config/locales/en.yml
- spec/factories/energy_bills.rb
- spec/features/support/case_attachments/agent_can_view_uploaded_bills_spec.rb
- spec/models/self-serve/framework_request_spec.rb
- spec/presenters/self-serve/framework_request_presenter_spec.rb
- spec/services/self-serve/submit_framework_request_spec.rb
- show uploaded bills in the case attachments tab
- show uploaded bills in the case history tab
- show uploaded bill count and change link on the RFH 'check your answers' page
> List energy bills in CMS

- app/views/framework_requests/index.html.erb
- app/views/static_pages/rising-energy-prices.html.erb
- updated content on the "What you can do about rising energy prices" page
> Update energy content

- app/controllers/framework_requests/bill_uploads_controller.rb
- app/controllers/framework_requests/confirm_sign_in_controller.rb
- app/controllers/framework_requests/emails_controller.rb
- app/controllers/framework_requests/messages_controller.rb
- app/controllers/framework_requests/select_organisations_controller.rb
- app/javascript/controllers/dropzone_controller.js
- app/javascript/controllers/dropzone_controller.test.js
- app/javascript/controllers/energy_bill_upload_controller.js
- app/views/framework_requests/bill_uploads/_form.html.erb
- app/views/framework_requests/bill_uploads/edit.html.erb
- config/routes.rb
- spec/controllers/framework_requests/confirm_sign_in_controller_spec.rb
- spec/controllers/framework_requests/emails_controller_spec.rb
- spec/controllers/framework_requests/messages_controller_spec.rb
- spec/controllers/framework_requests/select_organisations_controller_spec.rb
- spec/requests/energy_bill_upload_spec.rb
- add the ability to add/remove uploaded bills at the end of the RFH journey
> Add the ability to update uploaded bills

- app/controllers/support/cases_controller.rb
- app/presenters/support/agent_presenter.rb
- app/views/support/cases/_row.erb
- app/views/support/cases/forms/_filter_cases_form.html.erb
- app/views/support/cases/forms/_simple_case_filters.html.erb
- app/views/support/cases/index.html.erb
- config/locales/en.yml
- spec/features/support/towers/agent_can_view_tower_spec.rb
- spec/presenters/support/agent_presenter_spec.rb
- add the Tower tab to the cases index page
> PWNN-1027: Tower tab 1st iteration

- app/models/support/notification.rb
- app/models/support/notification_assignment.rb
- db/migrate/20230130100805_create_support_notifications.rb
- db/migrate/20230130100815_create_support_notification_assignments.rb
- db/schema.rb
- spec/factories/support/support_notifications.rb
- spec/models/support/notification_assignment_spec.rb
Part of PWMM-1079
Added basic models to enable Notifications work
> feat(notifications): added notification models

- app/helpers/support/collection_helper.rb
- app/models/support/category.rb
- spec/support/category_helpers.rb
Make sure to list "Or" options last in category dropdown
> fix: category options should list or last

- app/controllers/support/cases/summaries_controller.rb
- app/controllers/support/cases/summary_submissions_controller.rb
- app/forms/support/case_summary_form.rb
- app/forms/support/case_summary_form_schema.rb
- app/models/support/interaction.rb
- app/presenters/support/case_source_change_presenter.rb
- app/presenters/support/interaction_presenter.rb
- app/views/support/cases/case_history/_case_source_changed.html.erb
- app/views/support/cases/summaries/edit.html.erb
- app/views/support/cases/summary_submissions/edit.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- spec/factories/support/interaction.rb
- spec/features/support/agent_can_change_case_summary_spec.rb
- spec/forms/support/case_summary_form_schema_spec.rb
- spec/forms/support/case_summary_form_spec.rb
- spec/models/support/interaction_spec.rb
- spec/presenters/support/case_source_change_presenter_spec.rb
Added the ability to change the case source on the Case Summary page. A source change creates a record in the Case History tab of who made the change and what the source was changed from and to.
Jira: PWNN-1066
> PWNN-1066: Ability to update case source

- app/controllers/support/towers_controller.rb
- app/forms/support/case_filter_form.rb
- app/models/support/case.rb
- app/models/support/tower_statistics.rb
- app/services/support/filter_cases.rb
- app/views/support/case_statistics/towers/show.html.erb
- config/locales/en.yml
- db/migrate/20230203151247_update_support_tower_cases_to_version_3.rb
- db/schema.rb
- db/views/support_tower_cases_v03.sql
- spec/models/support/tower_statistics_spec.rb
- spec/services/support/filter_cases_spec.rb
Added a link to the Case Statistics page that shows all cases without an organisation.
Jira: PWNN-1070
> feat(cms): add cases without orgs to satistics

- .github/workflows/actions/build-docker-image/action.yml
- .github/workflows/actions/deploy/action.yml
- .github/workflows/ci-full-pipeline.yml
- .github/workflows/ci-release-production.yml
- .github/workflows/codeql.yml
- .github/workflows/qa-cleanup.yml
- .github/workflows/support-knapsack-generate-json.yml
Replaced all instances of `set-output` with writes to `$GITHUB_OUTPUT`.
Updated actions:
- `docker/login-action`
- `actions/checkout`
- `hashicorp/setup-terraform`
Jira: PWNN-873
> CI action and command updates

- app/forms/support/concerns/request_details_form_fields_schema.rb
- app/forms/support/create_case_form_schema.rb
> fix: remove validation on query text in cms

- app/presenters/support/case_presenter.rb
- app/views/support/cases/show/_case_details.html.erb
- app/views/support/cases/summary_submissions/edit.html.erb
- spec/presenters/support/case_presenter_spec.rb
Fixed case value presentation so that it separates thousands and has 2 decimal places.
Jira: PWNN-1280
> fix(cms): fix case value presentation

- app/helpers/date_helper.rb
- app/presenters/support/contract_presenter.rb
- app/presenters/support/message_presenter.rb
- app/views/support/cases/case_history/_interaction.html.erb
- app/views/support/cases/index/_detailed_case.html.erb
- app/views/support/cases/index/_simple_case.html.erb
- app/views/support/cases/index/_simple_cases.html.erb
- app/views/support/cases/message_threads/_logged_contact_thread.html.erb
- app/views/support/cases/message_threads/_templated_message_thread.html.erb
- app/views/support/cases/message_threads/_thread.html.erb
- app/views/support/cases/searches/_result.html.erb
- app/views/support/cases/show/_case_attachments.html.erb
- app/views/support/cases/show/_case_details.html.erb
- app/views/support/cases/show/_case_history.html.erb
- config/locales/en.yml
- spec/features/support/case_list_spec.rb
- spec/features/support/interactions/list_interactions_spec.rb
- spec/features/support/procurement_details/edit_existing_contract_spec.rb
- spec/features/support/procurement_details/edit_new_contract_spec.rb
- spec/helpers/self-serve/date_helper_spec.rb
Changed all the dates to relative and short-month formats.
Jira: PWNN-1226
> chore(cms): change date formats

- app/javascript/controllers/auto_filter_controller.js
- app/javascript/controllers/index.js
- app/views/support/cases/attachments/_filter.html.erb
Allow case attachment filters to be auto submitted when changing the values
> feat(cms): auto filter of case attachments

- app/controllers/referrals/referrals_controller.rb
- app/models/user_journey_step.rb
- config/application.rb
- config/routes.rb
- lib/middleware/user_journey_tracking.rb
- spec/controllers/referrals/referrals_controller_spec.rb
- spec/features/self-serve/auth/sign_out_spec.rb
- add referral routes and track them
Jira: PWNN-1004
> 1004 - feat: add referral routes

- app/views/support/cases/index/_detailed_case.html.erb
- app/views/support/cases/index/_detailed_cases.html.erb
- app/views/support/cases/index/_tab_all_cases.html.erb
- spec/features/support/case_list_pagination_spec.rb
- spec/features/support/case_list_spec.rb
- spec/features/support/filter_cases_spec.rb
- the 'All cases' tab now includes case notes
Jira: PWNN-1366
> feat(cms): all-cases tab includes notes

- app/controllers/support/cases/previews_controller.rb
- app/controllers/support/cases_controller.rb
- app/forms/framework_requests/procurement_amount_form.rb
- app/forms/support/create_case_form.rb
- app/forms/support/create_case_form_schema.rb
- app/presenters/support/create_case_form_presenter.rb
- app/services/support/forms/validate_procurement_amount.rb
- app/views/support/cases/forms/_create_case_form.html.erb
- app/views/support/cases/previews/new.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- spec/features/support/create_case_spec.rb
- spec/forms/framework_requests/procurement_amount_form_spec.rb
- spec/forms/support/create_case_form_schema_spec.rb
- spec/forms/support/create_case_form_spec.rb
- spec/presenters/support/create_case_form_presenter_spec.rb
- spec/services/support/forms/validate_procurement_amount_spec.rb
- added the ability to enter a procurement value on the Create a Case page
Jira: PWNN-1254
> feat(cms): add procurement value to create-a-case

- app/views/support/cases/messages/_reply_form_template.html.erb
- Adds the service disclaimer to the end of emails.
> refactor: Email service disclaimer.

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/components/_expander.scss
- app/assets/stylesheets/components/_tag-bar.scss
- app/assets/stylesheets/components/supported/_template-manager.scss
- app/controllers/support/management/email_templates_controller.rb
- app/forms/support/management/email_template_filter_form.rb
- app/helpers/support/expander_helper.rb
- app/helpers/support/tag_bar_helper.rb
- app/javascript/controllers/email_template_filters_controller.js
- app/javascript/controllers/email_templates_edit_controller.js
- app/javascript/controllers/expander_controller.js
- app/javascript/controllers/expander_controller.test.js
- app/javascript/controllers/index.js
- app/models/support/email_template.rb
- app/services/support/emails/templates/filter.rb
- app/views/support/helpers/_expander.html.erb
- app/views/support/helpers/_tag_bar.html.erb
- app/views/support/management/email_templates/template_manager/_filters.html.erb
- app/views/support/management/email_templates/template_manager/_templates.erb
- app/views/support/management/email_templates/template_manager/templates/_action_bar.html.erb
- app/views/support/management/email_templates/template_manager/templates/_summary.html.erb
- config/locales/en.yml
- spec/features/support/management/email_templates/admin_can_filter_templates_spec.rb
- spec/forms/support/management/email_template_filter_form_spec.rb
- spec/helpers/support/expander_helper_spec.rb
- spec/helpers/support/tag_bar_helper_spec.rb
- spec/services/support/emails/templates/filter_spec.rb
- add filtering to email templates
Jira: PWNN-1384
> feat(cms): email template filters

- app/controllers/support/cases/contact_details_controller.rb
- app/controllers/support/cases/organisations_controller.rb
- app/controllers/support/cases/summary_submissions_controller.rb
- app/cores/case_history/handle_case_state_changes.rb
- app/cores/case_management/assign_organisation_to_case.rb
- app/cores/case_management/update_case_contact_details.rb
- app/cores/case_management/update_case_summary_details.rb
- app/cores/case_management/update_case_support_level.rb
- app/forms/support/case_contact_details_form.rb
- app/forms/support/case_organisation_form.rb
- app/forms/support/case_summary_form.rb
- app/models/support/interaction.rb
- config/locales/en.yml
- spec/features/support/agent_can_change_case_summary_spec.rb
- spec/models/support/interaction_spec.rb
- spec/presenters/support/interaction_presenter_spec.rb
Record interations for:
- Organisation changes
- Contact changes
- Support level changes
> Record interactions for additional changes

- app/views/support/cases/index/_detailed_case.html.erb
- Deals with cases that do not have a support level set
> Handle cases without a support level.

- spec/features/support/emails/agent_can_send_new_emails_spec.rb
Fixes failing tests unique to Apple Silicon dev environment
- Reordered interactions with message 'show' buttons
> fix(cms): Agent can send email tests reliability

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/components/supported/_template-edit.scss
- app/assets/stylesheets/components/supported/_template-manager.scss
- app/controllers/support/document_downloads_controller.rb
- app/controllers/support/management/email_templates_controller.rb
- app/forms/support/management/email_template_form.rb
- app/javascript/controllers/email_templates_edit_controller.js
- app/javascript/controllers/email_templates_edit_controller.test.js
- app/models/support/email_template.rb
- app/models/support/email_template_attachment.rb
- app/views/support/management/email_templates/form/_form.html.erb
- app/views/support/management/email_templates/template_manager/templates/_template.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20230531145503_create_support_email_template_attachments.rb
- db/schema.rb
- spec/controllers/support/management/email_templates_controller_spec.rb
- spec/factories/support/email_template_attachment.rb
- spec/features/support/management/email_templates/admin_can_create_templates_spec.rb
- spec/features/support/management/email_templates/admin_can_edit_templates_spec.rb
- spec/forms/support/management/email_template_form_spec.rb
- spec/models/support/email_template_attachment_spec.rb
- spec/models/support/email_template_spec.rb
- spec/rails_helper.rb
- spec/support/sign_in_helpers.rb
Jira: PWNN-1388
- add email template attachments
> 1388 - feat(cms): add email template attachments

- app/controllers/support/cases_controller.rb
- app/controllers/support/concerns/filter_parameters.rb
- app/controllers/support/towers_controller.rb
- app/helpers/support/case_statistics_helper.rb
- app/models/support/case.rb
- app/models/support/tower.rb
- app/views/support/cases/forms/_simple_case_filters.html.erb
- app/views/support/cases/index.html.erb
- app/views/support/cases/index/_tab_triage_cases.html.erb
- config/locales/en.yml
- spec/features/self-serve/admin/show_spec.rb
- spec/features/support/case_list_spec.rb
- spec/features/support/towers_spec.rb
- spec/models/support/case_spec.rb
- spec/rails_helper.rb
- add triage tab for L1-L3 cases
- limit tower tabs to L3-L5 cases
- all under the `cms_triage_view` flag
Jira: PWNN-1459
> 1459 - feat(cms): triage view

- app/models/support/case.rb
- app/services/submit_framework_request.rb
- app/services/support/create_case.rb
- app/views/support/cases/show/_case_details.html.erb
- config/locales/en.yml
- db/migrate/20230627133137_add_user_selected_category_to_support_cases.rb
- db/schema.rb
- spec/features/support/case_tabs_spec.rb
- spec/models/support/case_spec.rb
- spec/services/self-serve/submit_framework_request_spec.rb
- spec/services/support/create_case_spec.rb
- persist user selected category on support case
Jira: PWNN-1520
> 1520 - feat(cms): persist user selected category on case

- app/controllers/support/cases/merge_emails_controller.rb
- app/models/support/case.rb
- app/services/support/merge_case_emails.rb
- app/views/support/cases/show/_case_actions.html.erb
- spec/features/support/case_merge_emails_spec.rb
- spec/services/support/merge_case_emails_spec.rb
- mail merge is now allowed for cases that are not "new"
Jira: PWNN-1536
> 1536 - feat(cms): always allow mail merge

- .rubocop_todo.yml
- app/controllers/support/cases/attachments_controller.rb
- app/cores/case_files/hide_attachment.rb
- app/models/support/case.rb
- app/models/support/case/state_changeable.rb
- app/models/support/email_attachment.rb
- app/models/support/email_attachment/de_dupable.rb
- app/models/support/email_attachment/hideable.rb
- spec/fixtures/text-file.txt
- spec/models/support/email_attachment/de_dupable_spec.rb
- spec/models/support/email_attachment/hideable_spec.rb
- spec/support/shared/duplicate_email_attachments.rb
Moved email attachment duplication logic into a concern.
Moved "hide" email attachment logic into a concern.
Added a few missing tests for the above.
Moved case state machine to a concern
> refactor: email attachment duplication logic moved to concern

- app/controllers/application_controller.rb
- app/views/application/maintenance.html.erb
- config/application.rb
- config/routes.rb
- lib/middleware/maintenance_mode.rb
Allow us to prevent user traffic during periods when we need to make changes to the infrastructure whihc might lead to data loss.
> feat: maintenance mode

- Gemfile.lock
- app/controllers/pages_controller.rb
- config/routes.rb
- yarn.lock
Previously when a random web request comes in e.g. `/CHANGELOG.txt` it gets routed to `PagesController` and then renders `errors/not_found`. This template was then, not found. 
The solution is just to redirect straight to 404.
> Fix page spamming

- app/controllers/application_controller.rb
- app/controllers/cms_entry_points_controller.rb
- app/controllers/concerns/manage_support_agents.rb
- app/controllers/concerns/support_agents.rb
- app/controllers/engagement/application_controller.rb
- app/controllers/engagement/management/base_controller.rb
- app/controllers/frameworks/application_controller.rb
- app/controllers/frameworks/dashboards_controller.rb
- app/controllers/specify/application_controller.rb
- app/controllers/support/application_controller.rb
- app/controllers/support/management/base_controller.rb
- app/helpers/application_helper.rb
- app/models/support/agent.rb
- app/policies/cms_portal_policy.rb
- app/views/frameworks/dashboards/index.html.erb
- app/views/layouts/_navigation_links.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/controllers/cms_entry_points_controller_spec.rb
- New frameworks portal
- New frameworks role
- Refactored some code around determining which portal you are on
> Framework evaluation portal groundwork

- app/views/support/cases/requests/show.html.erb
- app/views/support/cases/show/_case_details.html.erb
- show the email of the creator of E&O cases in cases details
Jira: PWNN-1555
> 1555 - feat(cms): show creator of E&O cases in CMS

- app/models/framework_request.rb
- app/models/support/case.rb
- app/models/support/case_organisation.rb
- app/services/submit_framework_request.rb
- app/services/support/create_case.rb
- db/migrate/20230824102420_create_support_case_organisations.rb
- db/migrate/20230825101049_add_support_case_to_framework_requests.rb
- db/schema.rb
- spec/services/specify/submit_framework_request_spec.rb
- spec/services/support/create_case_spec.rb
- persist schools selected in request on the case via the `support_case_organisations`table
Jira: PWNN-1539
> 1539 - feat(cms): persist procurement schools on case

- app/views/framework_requests/index.html.erb
- config/locales/en.yml
- spec/features/specify/framework_requests/start_page_spec.rb
> feat(rfh): update guidance

- app/views/framework_requests/index.html.erb
- config/locales/en.yml
- spec/features/specify/framework_requests/start_page_spec.rb
> Release RFH new guidance

- app/views/support/cases/requests/show.html.erb
- config/locales/en.yml
- show uploaded file names in the request tab
Jira: PWNN-1562
> 1652 - feat(cms): show uploaded files in request tab

- app/views/support/cases/requests/show.html.erb
- config/locales/en.yml
- https://github.com/DFE-Digital/buy-for-your-school/pull/1584
> Release 05/09/2023

- app/views/framework_request_submissions/_default.html.erb
- app/views/framework_request_submissions/_energy.html.erb
- app/views/framework_request_submissions/show.html.erb
- config/locales/en.yml
- add a default confirmation page for non-energy requests
Jira: PWNN-1668
> 1668 - fix(rfh): add default confirmation page

- Gemfile.lock
Updated the gem selenium-webdriver to fix the below issue when running rspec tests:
Selenium::WebDriver::Error::NoSuchDriverError:
Unable to obtain chromedriver using Selenium Manager;
> update selenium-webdriver gem

- app/forms/framework_requests/email_form.rb
- spec/features/specify/framework_requests/create_framework_request_guest_spec.rb
Edited the sky school email address that is allowed and is an exception to the sky. emails that are not permitted
> feat(rfh): change sky email that is permitted

- app/views/framework_request_submissions/_energy.html.erb
- app/views/specify/support_request_submissions/show.html.erb
- app/views/specify/support_requests/index.html.erb
- config/locales/en.yml
- spec/features/specify/support_requests/start_page_spec.rb
- spec/features/specify/support_requests/submit_support_request_spec.rb
Content and link edits to:
- Create a spec support form confirmation page
- Create a spec request help and support start form
- Request for help form confirmation page - energy
> 1661 feat(service): update links

- app/javascript/components/tinymce.js
- set TinyMCE options to leave relative links unchanged
> fix(cms): keep relative links unchanged in TinyMCE

- app/controllers/support/cases/transfer_to_framework_evaluation_controller.rb
- app/models/frameworks/evaluation.rb
- app/models/frameworks/evaluation/sourceable.rb
- app/models/frameworks/evaluation/transferable.rb
- app/models/support/case.rb
- app/models/support/case/transferable.rb
- app/models/support/case/transferer.rb
- app/models/support/interaction.rb
- app/presenters/support/case_transferred_presenter.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/record_action.rb
- app/views/frameworks/activity_log_items/activity/activity_event/evaluations/_evaluation_transferred.html.erb
- app/views/support/cases/show/_case_actions.html.erb
- app/views/support/cases/transfer_to_framework_evaluation/index.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- db/migrate/20231106164140_add_creation_source_to_frameworks_evaluations.rb
- db/schema.rb
- spec/features/support/agent_can_transfer_case_to_framework_evaluation_spec.rb
- spec/models/support/interaction_spec.rb
- add the ability to transfer/convert a new CMS case to a framework evaluation
Jira: PWNN-1646
> 1646 - feat(cms-fworks): transfer cases to evaluations

- app/assets/config/manifest.js
- app/controllers/application_controller.rb
- app/javascript/google-tag-manager/activate.js
- app/javascript/google-tag-manager/include.js
- app/views/cookie_preferences/update_cookies_accepted.js.erb
- app/views/layouts/application.html.erb
- Added GA to prod/staging/dev, removed google tag manager
> feat(service): collect google analytics data

- app/controllers/frameworks/frameworks_controller.rb
- app/models/frameworks/framework/filterable.rb
- app/models/frameworks/framework/filtering.rb
- app/models/frameworks/framework/searchable.rb
- app/views/frameworks/frameworks/_index_filters.html.erb
- spec/models/frameworks/framework/searchable_spec.rb
Added a search box to make it easier to find a specific framework.
> feat(fworks): search frameworks by name and ref

- .dockerignore
- Dockerfile
Switch to slim docker image to speed downloading of image
> build: switch to slim docker image

- app/controllers/support/notifications/mark_all_reads_controller.rb
- app/controllers/support/notifications/reads_controller.rb
- app/cores/notifications/mark_all_as_read.rb
- app/cores/notifications/mark_as_read.rb
- app/cores/notifications/mark_as_unread.rb
- app/models/support/agent.rb
- app/models/support/agent/notifyable.rb
- app/models/support/notification.rb
- spec/models/support/agent/notifyable_spec.rb
- spec/requests/support/notifications/mark_all_reads_spec.rb
- spec/requests/support/notifications/mark_as_read_spec.rb
Commits to move slowly away from cores bit by bit
> refactor notifications core

- config/locales/en.yml
> 1862 fix(rfh): RFH landing page typos

- app/controllers/concerns/manage_support_agents.rb
- app/cores/agents/create_agent.rb
- app/models/support/agent.rb
- app/views/support/management/agents/_agents.html.erb
- app/views/support/management/agents/index.html.erb
- config/locales/en.yml
> 1697 feat(CMS): Disable ProcOps staff & see disabled accounts

- Gemfile.lock
- Adds platform to gemfile lock
> Add platform to gemfile lock

- app/jobs/support/send_exit_survey_job.rb
- app/models/customer_satisfaction_survey_response.rb
- db/migrate/20240126131833_add_support_case_id_to_customer_satistfaction_survey_responses.rb
- db/schema.rb
- spec/jobs/support/send_exit_survey_job_spec.rb
Dont merge/close until team are clear on anonymity.
Record the case a satisfaction survey is referring to if sent by exit survey job.
> feat: customer sf survey records case id

- app/controllers/engagement/case_requests/contract_start_dates_controller.rb
- app/controllers/engagement/case_requests/same_suppliers_controller.rb
- app/controllers/engagement/case_requests/school_pickers_controller.rb
- app/controllers/engagement/case_requests_controller.rb
- app/models/case_request.rb
- app/models/case_request/contract_start_dateable.rb
- app/models/case_request/contract_start_dater.rb
- app/models/case_request/presentable.rb
- app/models/case_request/same_supplierable.rb
- app/models/case_request/same_supplierer.rb
- app/models/support/category.rb
- app/views/engagement/case_requests/contract_start_dates/edit.html.erb
- app/views/engagement/case_requests/same_suppliers/edit.html.erb
- app/views/engagement/case_requests/show.html.erb
- app/views/support/cases/request_details/show.html.erb
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20231130133327_add_details_to_case_requests.rb
- db/schema.rb
- spec/features/engagement/create_case_spec.rb
- Added same supplier and contract start date known to the E&O create a case form
- Energy and services show contract start date
- MAT picker more than one school picked shows same supplier
- New fields in CYA page and support case request details tab
> 1678 - feat(e&o): add questions to create a case

- app/helpers/date_helper.rb
- spec/helpers/specify/date_helper_spec.rb
- Changes the relative date format from being more than a year to anything but the current date
> 1891 - feat(cms): change relative date format

- app/models/framework_request.rb
> fix: underfined method is_energy_or_services

- .github/workflows/ci-full-pipeline.yml
Use inbuilt GITHUB_TOKEN rather than my own personal access token.
> ci: use GITHUB_TOKEN instead of PAT

- app/controllers/support/cases/searches_controller.rb
- app/helpers/support/case_helper.rb
- app/views/support/cases/case_list/case_panel/_case_panel.html.erb
- app/views/support/cases/case_list/case_panel/_top_right_pane.html.erb
- app/views/support/cases/school_details/show.html.erb
- config/locales/en.yml
- spec/features/support/agent_can_view_other_cases_raised_by_organisation_spec.rb
- spec/helpers/support/case_helper_spec.rb
- add the "View all" link to the cases view for cases that share the same organisation with at least 1 other case that is not closed
- add the "View all cases" link to the "School Details" tab for cases that share the same organisation with at least 1 other case that is not closed
Jira: PWNN-1821
> 1821 - feat(cms): view other cases raised by school

- app/models/customer_satisfaction_survey_response/satisfactionable.rb
- app/services/support/email_templates.rb
- app/views/customer_satisfaction_surveys/satisfaction_levels/edit.html.erb
- config/locales/en.yml
- spec/features/support/case_resolution_spec.rb
- spec/models/customer_satisfaction_survey_response/presentable_spec.rb
- spec/requests/customer_satisfaction_survey/customer_satisfaction_survey_flow_spec.rb
- spec/services/emails/customer_satisfaction_survey_spec.rb
- revert to previous answers for the satisfaction survey satisfaction levels
> 1938 - feat: revert to previous satisfaction levels

- app/helpers/support/collection_helper.rb
- app/models/support/procurement_stage.rb
- config/support/procurement_stages.yml
- db/migrate/20240304175129_update_procurement_substages.rb
- db/migrate/20240306124300_set_procurement_substage_lifecycle_orders.rb
- db/schema.rb
- spec/services/support/seed_procurement_stages_spec.rb
> pwnn-1941 feat(cms): update Procurement sub-stages

- db/migrate/20240318102215_remove_legacy_framework_from_case1614.rb
- db/schema.rb
- remove the legacy framework on case 1614
> 1950 - fix(cms): remove legacy framework on case 1614

- app/models/support/case_search.rb
- config/locales/en.yml
- db/migrate/20240319170615_rename_support_case_searches_email_column.rb
- db/migrate/20240319170710_update_support_case_searches_to_version_4.rb
- db/schema.rb
- db/views/support_case_searches_v04.sql
- spec/models/support/case_search_spec.rb
- enable users to find cases by contact email
> 1947 - feat(cms): find cases by contact email

- app/helpers/application_helper.rb
- app/models/customer_satisfaction_survey_response.rb
- app/views/specify/specifications/show.html.erb
- spec/features/specify/journeys/download_spec.rb
> pwnn-1949 feat(cms): Update CaS sidebar feedback link

- app/controllers/frameworks/dashboards_controller.rb
- app/models/frameworks/framework_datum.rb
- app/views/frameworks/evaluations/index.html.erb
- app/views/frameworks/frameworks/_index_filters.html.erb
- config/locales/en.yml
- db/migrate/20240415143752_create_frameworks_framework_data.rb
- db/schema.rb
- db/views/frameworks_framework_data_v01.sql
- doc/roles-and-portals.md
- spec/features/frameworks/register/agent_can_download_frameworks_register_csv_spec.rb
- spec/features/support/case_statistics_spec.rb
- spec/models/frameworks/framework_datum_spec.rb
- spec/requests/frameworks/download_frameworks_spec.rb
- Adds a button on frameworks page to give procops ability to download a csv of the frameworks register
- Fixes a couple of typos
> 1905 - feat(fworks): download frameworks register csv

- .github/workflows/actions/build-docker-image/action.yml
- .github/workflows/actions/deploy-az/action.yml
- .github/workflows/ci-full-pipeline.yml
- .github/workflows/codeql.yml
- .github/workflows/support-knapsack-generate-json.yml
- .github/workflows/support-update-ssl-cert-validation-implementation.yml
> Update GitHub actions

- db/migrate/20240610162322_reopen_two_live_cases.rb
- db/schema.rb
Re-opened 2 live cases: 003533 & 002850
> pwnn-1994 fix(cms): reopen two live closed cases

- db/migrate/20240611091424_move_emails_from_case_3533_to_2850.rb
- db/schema.rb
A migration that moves selected emails from case 3533 to case 2850.
> fix(cms): move selected emails from case 3533 to case 2850

- db/migrate/20240612085007_move_interactions_from_case_3533_to_2850.rb
- db/schema.rb
A migration that moves selected interactions from case 3533 to case 2850.
> fix(cms): move selected interactions from case 3533 to case 2850

- app/services/emails/confirmation.rb
- app/views/framework_requests/framework_request_submissions/_default.html.erb
- app/views/framework_requests/framework_request_submissions/_energy.html.erb
- app/views/specify/support_request_submissions/show.html.erb
- config/locales/en.yml
- spec/features/specify/framework_requests/edit_framework_request_dsi_spec.rb
- spec/features/specify/framework_requests/edit_framework_request_guest_spec.rb
- spec/features/specify/support_requests/start_page_spec.rb
- spec/features/specify/support_requests/submit_support_request_spec.rb
> pwnn-2006 fix(cms): change ProcOps SLA from 2 days to 5

- app/models/frameworks/activity_log_item.rb
- app/models/frameworks/activity_log_item/presentable.rb
- app/models/frameworks/activity_loggable/activity_log_presentable.rb
- app/views/frameworks/management/activity_logs/_list.html.erb
- Brings back some deleted code from a previous refactor to fix the internal server error message
- Now shows basic activity log table in the management area
> 1992 - fix(fworks): fix internal server error for activity log page

- app/controllers/frameworks/frameworks_controller.rb
- app/views/frameworks/frameworks/_form.html.erb
- app/views/frameworks/frameworks/show/_framework_details.html.erb
- app/views/frameworks/frameworks/show/_framework_provider.html.erb
- spec/features/frameworks/register/agent_can_browse_frameworks_register_spec.rb
- spec/features/frameworks/register/agent_can_create_framework_spec.rb
- spec/support/database_cleaner.rb
- Changes for pwnn 1977 & pwnn 1972 in this branch
- Framework reference is created automatically 
- Provider reference is saved correctly and displayed in the provider tab
- All ownership fields can be edited
- All the DfE ownership fields are shown in the framework details tab, not the provider tab
> 1977 - fix(fworks): fix bugs in edit and creating a framework

- db/migrate/20240716230644_update_support_case_data_to_version_11.rb
- db/schema.rb
- db/views/support_case_data_v11.sql
> pwnn-2004 bug(cms): empty rows in cases CSV

- app/controllers/support/cases/openings_controller.rb
- app/models/support/case.rb
- app/models/support/case/activity_loggable.rb
- app/models/support/case/notifiable.rb
- app/models/support/case/state_changeable.rb
- app/models/support/notification.rb
- app/views/support/cases/openings/new.html.erb
- app/views/support/cases/show/_case_actions.html.erb
- app/views/support/cases/show/_tabs.html.erb
- app/views/support/notifications/topics/_case_reopened.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/cores/case_management/open_case_spec.rb
- spec/features/support/case_closure_spec.rb
- spec/features/support/case_opening_spec.rb
- spec/features/support/case_tabs_spec.rb
- spec/features/support/case_view_spec.rb
- spec/requests/support/case_opening_spec.rb
Change in state_changeable to ensure the transition of state of case from closed to reopen, addition of notifications to the case owner.
> feat(cms): ability to re-open case

- db/migrate/20240729132111_remove_duplicate_framework_f62.rb
Removing a framework from production
> fix(crm): removing framework(F62) from production

- app/controllers/engagement/case_requests/school_pickers_controller.rb
- app/controllers/engagement/case_requests_controller.rb
- app/controllers/framework_requests/school_pickers_controller.rb
- app/controllers/support/case_requests/school_pickers_controller.rb
- app/controllers/support/case_requests_controller.rb
- app/controllers/support/cases/school_details/participating_schools_controller.rb
- app/forms/framework_requests/school_picker_form.rb
- app/helpers/school_picker_helper.rb
- app/models/support/organisation/filterable.rb
- app/models/support/organisation/filtering.rb
- app/views/components/school_picker/_school_picker_filters.html.erb
- app/views/engagement/case_requests/show.html.erb
- app/views/support/case_requests/show.html.erb
- config/locales/en.yml
> pwnn-2029 feat(cms): add school status filter to MSP

- app/assets/stylesheets/base/_frontend.scss
- app/views/engagement/management/base/index.html.erb
- app/views/support/management/agents/index.html.erb
- app/views/support/management/all_cases_surveys/index.html.erb
- app/views/support/management/base/index.html.erb
- app/views/support/management/categories/index.html.erb
- app/views/support/management/category_detections/new.html.erb
- app/views/support/management/email_templates/edit.html.erb
- app/views/support/management/email_templates/index.html.erb
- app/views/support/management/email_templates/new.html.erb
- app/views/support/management/sync_frameworks/index.html.erb
- package.json
- yarn.lock
> build: update govuk frontend

- app/controllers/support/cases/additional_contacts_controller.rb
- app/controllers/support/cases/contact_details_controller.rb
- app/cores/case_management/update_case_additional_contacts.rb
- app/forms/support/case_additional_contact_form.rb
- app/forms/support/case_additional_contact_form_schema.rb
- app/helpers/support/case_additional_contacts_helper.rb
- app/models/support/case.rb
- app/models/support/case_additional_contact.rb
- app/models/support/organisation.rb
- app/views/layouts/_messages.html.erb
- app/views/support/cases/additional_contacts/_form.html.erb
- app/views/support/cases/additional_contacts/edit.html.erb
- app/views/support/cases/additional_contacts/index.html.erb
- app/views/support/cases/additional_contacts/new.html.erb
- app/views/support/cases/contact_details/edit.html.erb
- app/views/support/cases/school_details/show.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- db/migrate/20240712131114_create_support_case_additional_contacts.rb
- db/migrate/20240722144936_add_organisation_id_to_case_additional_contacts.rb
- db/migrate/20240818210639_add_is_evaluator_to_case.rb
- db/schema.rb
- spec/factories/support/case_additional_contact.rb
- spec/features/support/case_additional_contacts_spec.rb
- spec/features/support/case_organisation_details_spec.rb
- spec/features/support/case_school_details_spec.rb
- spec/models/support/case_spec.rb
Adding multiple contacts against a case with roles
> feat(csm): Adding multiple additional contacts into case

- app/views/support/cases/school_details/participating_schools/show.html.erb
Disallow editing of participating schools when case is 'Resolved' or 'Closed'
> feat(crm): removing change button on beneficiary school page

- app/controllers/support/cases/summaries_controller.rb
- app/forms/support/case_contracts_form_schema.rb
- app/forms/support/case_savings_form_schema.rb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- db/migrate/20240903101832_update_precision_in_support_cases.rb
- db/schema.rb
- spec/features/support/procurement_details/edit_savings_spec.rb
Change the case value maximum number allowed
> feat(crm): updating precision in support case columns

- app/presenters/support/case_presenter.rb
Accessibility flag showing incorrectly - investigation needed
> fix(crm): fixing the accessibility flag

- app/views/support/cases/school_details/show.html.erb
Disable 'Pending beneficiary schools' in Staging
> fix(crm): removing pending beneficiary schools UI temporarily

- app/controllers/support/cases/additional_contacts_controller.rb
- app/forms/support/case_additional_contact_form_schema.rb
- app/models/support/case_additional_contact.rb
Changes in validation of Additional contacts
> changes in validation in additional contacts

- config/locales/validation/en.yml
- spec/forms/framework_requests/procurement_amount_form_spec.rb
- spec/forms/specify/request_form_schema_spec.rb
> increasing the value of procurement ammount

- db/migrate/20241004084539_update_support_case_data_to_version_14.rb
- db/schema.rb
- db/views/support_case_data_v14.sql
- Replace the support cases data view with Prathi's SQL file to fix some columns missing their values
> 2080 - fix(cms): reinstate missing fields

- db/migrate/20240821122951_add_columns_to_gias_data.rb
- lib/school/information.rb
- lib/school/mapper.rb
- lib/school/record_keeper.rb
- lib/school/schema.rb
- lib/support/establishment_groups/information.rb
- lib/support/establishment_groups/mapper.rb
- lib/support/establishment_groups/record_keeper.rb
- lib/support/establishment_groups/schema.rb
- spec/lib/specify/school/information_call_spec.rb
- spec/lib/specify/school/mapper_call_spec.rb
- spec/lib/specify/school/record_keeper_spec.rb
- spec/lib/specify/school/schema_call_spec.rb
- spec/lib/support/establishment_groups/information_call_spec.rb
- spec/lib/support/establishment_groups/mapper_call_spec.rb
- spec/lib/support/establishment_groups/record_keeper_spec.rb
- spec/lib/support/establishment_groups/schema_call_spec.rb
- Added closed date, reason establishment opened, reason establishment closed, archived, archived at to support organisations
- Added closed date, opened date, archived, archived at to support establishment groups
- Added archived, archived at to local authorities
> feat(cms): update gias import

- doc/getting-started/development-environment.md
Clarify how to configure the database, and fix the database initialisation command.
Documentation only.
> Improve dev env setup docs

- app/controllers/support/frameworks_controller.rb
- app/models/frameworks/framework/filterable.rb
**PWNN-2097 Ability to select DfE approved or CAB approved framework**
app/controllers/support/frameworks_controller.rb  - Added new condtion to filter approved framework
> PWNN-2097 Ability to select DfE approved or CAB approved framework

- doc/release-process.md
- Added git fetch as a command for the process
- Documented how to find the docker image for the release log
> Update release process documentation

- doc/README.md
- doc/feature-flags.md
- Adds documentation about feature flags - what they are, current flags, and where to find the username and passwords
> Add feature flag documentation

- .github/workflows/support-update-ssl-cert-validation-implementation.yml
It changes the profile name from stagingghbscdn to stagghbscdn which is how it appears in Azure, so that the script for checking and updating the SSL certification should run without errors.
> Fix ssl cert script

- .github/workflows/support-update-ssl-cert-validation-implementation.yml
- The fix of the profile name didn't work, so seeing if changing the domain name helps too
> Change customDomainName for staging

- app/controllers/cms_entry_points_controller.rb
- app/services/create_user.rb
- spec/services/specify/create_user_spec.rb
1. app/controllers/cms_entry_points_controller.rb - check  email_evaluator_link session and redirect to evaluator tasklist page
2. app/services/create_user.rb - updated dsi_uid to the support evaluators
> SC-78 Evaluator journey: accessing evaluation from a link 

- app/controllers/cms_entry_points_controller.rb
- app/controllers/evaluation/tasks_controller.rb
- app/views/specify/home/_default.html.erb
- app/views/specify/home/_evaluation.html.erb
- app/views/specify/home/show.html.erb
- config/locales/en.yml
- spec/features/evaluation/task_list_spec.rb
1. app/controllers/evaluation/application_controller.rb - Added new method to override default authenticate_user!
2. app/views/specify/home/_default.html.erb - Added new view file for default login page
3. app/views/specify/home/_evaluation.html.erb - Added new view file for evaluation journey login page
4. app/views/specify/home/show.html.erb - Added condition to render view file based on evaluation session value
5. config/locales/en.yml - Added new language varibale
> Sc 160 evaluator journey start page

- app/controllers/support/cases/review_evaluations_controller.rb
- app/presenters/support/case_presenter.rb
- app/views/evaluation/tasks/show.html.erb
- app/views/support/cases/document_uploads/_uploaded_documents.html.erb
- app/views/support/cases/review_evaluations/_form.html.erb
- app/views/support/cases/review_evaluations/edit.html.erb
- app/views/support/cases/show/_tasklist.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250127101817_add_evaluation_approved_to_support_evaluators.rb
- spec/features/support/agent_can_review_evaluations_spec.rb
1. app/controllers/support/cases/review_evaluations_controller.rb - Added new controller for review evaluation
2. app/views/support/cases/review_evaluations/_form.html.erb - Added new view file for review evaluation
3. app/views/support/cases/review_evaluations/edit.html.erb - Added new view file for review evaluation
4. app/views/support/cases/show/_tasklist.html.erb - Updated view file for review evaluation link
5. config/locales/en.yml - Added new language variable 
6. config/locales/validation/support/en.yml - Added new language variable
7. config/routes.rb - Added new routes
8. db/migrate/20250127101817_add_evaluation_approved_to_support_evaluators.rb - Added new migration file to update evaluation status
9. spec/features/support/agent_can_review_evaluations_spec.rb - Added new test …
> SC-91 Review Evaluation

- app/forms/support/case_evaluation_due_date_form_schema.rb
- spec/features/support/agent_can_add_evaluation_due_date_spec.rb
app/forms/support/case_evaluation_due_date_form_schema.rb - Added validation check the year 4 digit
spec/features/support/agent_can_add_evaluation_due_date_spec.rb - Added test spec for validation
> SC-210  Set due date - Internal Server Error

- app/views/support/cases/show/_tasklist.html.erb
- config/locales/en.yml
- spec/features/support/case_tasklist_spec.rb
1. app/views/support/cases/show/_tasklist.html.erb - Added new links for handover contract
2. config/locales/en.yml - Added new language variable for handover contract links
3. spec/features/support/case_tasklist_spec.rb - Added new validation
> SC-106 Handover journey: Handover contract task list

- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/controllers/support/cases/review_evaluations_controller.rb
- app/controllers/support/email_read_status_controller.rb
- app/models/email/actionable.rb
- doc/feature-flags.md
- spec/features/evaluation/upload_completed_documents_spec.rb
- spec/rails_helper.rb
- spec/requests/support/email_read_status_spec.rb
…mitted
1. app/controllers/support/email_read_status_controller.rb - Added a new condition for updating the action_required flag
2. app/controllers/support/cases/review_evaluations_controller.rb - Added a new method for updating the action_required flag
3. app/controllers/evaluation/upload_completed_documents_controller.rb - Added a new method for updating the action_required flag
4. app/models/email/actionable.rb - Added a new condition for updating the action_required flag
5. spec/features/evaluation/upload_completed_documents_spec.rb - Added a new test case to check action_required flag status
6. spec/rails_helper.rb - Included new feature flipper (sc_notify_procops)
7. spec/requests/support/email_read_status_spec.rb - Added a new test case to check action_required flag status
> SC-171 Notify Proc Ops (red dot) when an evaluation is submitted

- app/controllers/support/cases/contract_recipients_controller.rb
- app/models/support/case.rb
- app/models/support/contract_recipient.rb
- app/views/support/cases/contract_recipients/_form.html.erb
- app/views/support/cases/contract_recipients/destroy.html.erb
- app/views/support/cases/contract_recipients/edit.html.erb
- app/views/support/cases/contract_recipients/index.html.erb
- app/views/support/cases/contract_recipients/new.html.erb
- app/views/support/cases/show/_tasklist.html.erb
- config/locales/en.yml
- config/locales/validation/support/en.yml
- config/routes.rb
- db/migrate/20250224123310_add_contract_recipients.rb
- db/schema.rb
- spec/features/support/agent_can_add_contract_recipient_spec.rb
1. app/controllers/support/cases/contract_recipients_controller.rb - Added new controller for adding contract recipients
2. app/models/support/case.rb - Included contract recipient class
3. app/models/support/contract_recipient.rb - Added new Model for adding contract recipients
4. app/views/support/cases/contract_recipients/_form.html.erb - Added new view file for adding contract recipients
5. app/views/support/cases/contract_recipients/destroy.html.erb - Added new view file for delete contract recipients
6. app/views/support/cases/contract_recipients/edit.html.erb -  Added new view file for edit contract recipients
7. app/views/support/cases/contract_recipients/index.html.erb - Added new view file for list contract recipients
8. app/views/support/cases/contract_recipients/new.html.erb - …
> SC-111 Handover journey: Add contract recipients

- app/controllers/support/cases/upload_contract_handovers_controller.rb
- app/controllers/support/document_downloads_controller.rb
- app/models/support/case.rb
- app/models/support/case/document_uploadable.rb
- app/models/support/case/document_uploader.rb
- app/models/support/upload_contract_handover.rb
- app/presenters/support/case_presenter.rb
- app/views/support/cases/show/_tasklist.html.erb
- app/views/support/cases/upload_contract_handovers/_form.html.erb
- app/views/support/cases/upload_contract_handovers/_uploaded_documents.html.erb
- app/views/support/cases/upload_contract_handovers/destroy.html.erb
- app/views/support/cases/upload_contract_handovers/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250225120657_add_support_upload_contract_handovers.rb
- db/migrate/20250225122027_add_has_uploaded_contract_handovers.rb
- db/schema.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
1. app/controllers/support/cases/upload_contract_handovers_controller.rb - Added new controller for upload contract handover pack
2. app/controllers/support/document_downloads_controller.rb - Added new class object for download documents
3. app/controllers/support/document_downloads_controller.rb - Updated file for upload contract handover pack
4. app/models/support/case/document_uploadable.rb - Added new method for upload contract handover pack
5. app/models/support/case/document_uploader.rb - Added new method for upload contract handover pack
6. app/models/support/upload_contract_handover.rb - Added new model for upload contract handover pack
7. app/presenters/support/case_presenter.rb - Added new methods to check for upload contract handover pack status
8. …
> SC-112 Handover journey: Upload contract handover pack

- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/controllers/support/cases/review_evaluations_controller.rb
- app/controllers/support/email_read_status_controller.rb
- app/models/email/actionable.rb
- doc/feature-flags.md
- spec/rails_helper.rb
1. app/controllers/evaluation/upload_completed_documents_controller.rb - Updated feature flag 
2. app/controllers/support/cases/review_evaluations_controller.rb - Updated feature flag 
3. app/controllers/support/email_read_status_controller.rb - Updated feature flag 
4. app/models/email/actionable.rb - Updated feature flag 
5. doc/feature-flags.md - Removed sc_notify_procops information
6. spec/rails_helper.rb - Removed sc_notify_procops in helper file
> SC-171 Feature flag update from sc_notify_procops to sc_tasklist_tab

- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/controllers/support/cases/review_evaluations_controller.rb
- app/controllers/support/email_read_status_controller.rb
- app/models/email/actionable.rb
- app/views/support/cases/show/_tabs.html.erb
- doc/feature-flags.md
- spec/rails_helper.rb
1. app/controllers/evaluation/upload_completed_documents_controller.rb - Updated feature flag name
2. app/controllers/support/cases/review_evaluations_controller.rb - Updated feature flag name
3. app/controllers/support/email_read_status_controller.rb - Updated feature flag name
4. app/models/email/actionable.rb  - Updated feature flag name
5. app/views/support/cases/show/_tabs.html.erb  - Updated feature flag name
6. doc/feature-flags.md - Updated feature flag name
7. spec/rails_helper.rb - Updated feature flag name
> SC-171 Feature flag name updated from sc_tasklist_tab to sc_tasklist_case

- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/models/support/case/notifiable.rb
- app/views/support/notifications/topics/_evaluation_documents_uploaded.html.erb
- spec/features/evaluation/upload_completed_documents_spec.rb
1. app/controllers/evaluation/upload_completed_documents_controller.rb - Added email details when evaluation document submitted
2. app/models/support/case/notifiable.rb - Updated email details in notification
3. app/views/support/notifications/topics/_evaluation_documents_uploaded.html.erb - Updated notification template
4. spec/features/evaluation/upload_completed_documents_spec.rb - Updated test file to check notification
> SC-213 Added support email details when evaluation document submitted

- app/controllers/my_procurements/download_handover_packs_controller.rb
- app/controllers/my_procurements/tasks_controller.rb
- app/controllers/support/cases/upload_contract_handovers_controller.rb
- app/models/support/download_contract_handover.rb
- app/presenters/support/case_presenter.rb
- app/views/my_procurements/download_handover_packs/_document_list.html.erb
- app/views/my_procurements/download_handover_packs/show.html.erb
- app/views/my_procurements/tasks/show.html.erb
- app/views/support/cases/show/_tasklist.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250307112416_add_support_download_contract_handovers.rb
- db/schema.rb
- spec/features/my_procurements/download_handover_packs_spec.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
1. app/controllers/my_procurements/download_handover_packs_controller.rb - Added new controller file for download handover packs
2. app/controllers/my_procurements/tasks_controller.rb - Updated file to display downloaded status of handover packs
3. app/controllers/support/cases/upload_contract_handovers_controller.rb - Updated file to destroy downloaded entry when file has been deleted
4. app/models/support/download_contract_handover.rb - Added new model for download handover packs
5. app/views/my_procurements/download_handover_packs/_document_list.html.erb - Added new view file to display uploaded handover packs
6. app/views/my_procurements/download_handover_packs/show.html.erb - Added new view file for download handover packs
7. app/views/my_procurements/tasks/show.html.erb  - Updated …
> Added new files for download contract handover packs

- app/controllers/cms_entry_points_controller.rb
- app/controllers/my_procurements/signin_controller.rb
- app/controllers/my_procurements/tasks_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/specify/home_controller.rb
- app/views/my_procurements/signin/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/sessions_controller_spec.rb
- spec/features/my_procurements/signin_spec.rb
1. app/controllers/cms_entry_points_controller.rb - Updated file to redirect to school buyer page
2. app/controllers/my_procurements/signin_controller.rb - Added new controller for  school buyer start page
3. app/controllers/my_procurements/tasks_controller.rb - Updated file to redirect to school buyer page
4. app/controllers/sessions_controller.rb - Updated file to redirect to school buyer page
5. app/controllers/specify/home_controller.rb - Updated file to delete school buyer page session
6. app/views/my_procurements/signin/show.html.erb - Added new view file for  school buyer start page
7. config/locales/en.yml - Added new language variable
8. config/routes.rb - Added new route for school buyer start page
9. spec/controllers/sessions_controller_spec.rb - Updated new test case for …
> SC-261 School buying professional - start page

- app/views/my_procurements/tasks/show.html.erb
- config/locales/en.yml
1. app/views/my_procurements/tasks/show.html.erb - Removed body text
2. config/locales/en.yml - Removed language variable
> SC-115 UI Fix

- app/views/support/cases/messages/_reply_form_template.html.erb
Change date from 2024 to 2025 in the reply email template
> Change the year in the reply template from 2024 to 2025

- app/controllers/evaluation/download_documents_controller.rb
- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/controllers/my_procurements/download_handover_packs_controller.rb
- app/controllers/support/cases/contract_recipients_controller.rb
- app/controllers/support/cases/document_uploads_controller.rb
- app/controllers/support/cases/email_evaluators_controller.rb
- app/controllers/support/cases/evaluation_due_dates_controller.rb
- app/controllers/support/cases/evaluators_controller.rb
- app/controllers/support/cases/review_evaluations_controller.rb
- app/controllers/support/cases/share_handover_packs_controller.rb
- app/controllers/support/cases/upload_contract_handovers_controller.rb
- app/models/support/case/document_uploadable.rb
- app/models/support/interaction.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/evaluation_journey_tracking.rb
- spec/features/evaluation/download_documents_spec.rb
- spec/features/my_procurements/download_handover_packs_spec.rb
- spec/features/support/agent_can_add_contract_recipient_spec.rb
- spec/features/support/agent_can_share_handover_pack_spec.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
- spec/features/support/case_contract_handover_tasklist_spec.rb
- spec/models/support/interaction_spec.rb
1. app/controllers/evaluation/download_documents_controller.rb - Updated file for EvaluationJourneyTracking callback
2.  app/controllers/evaluation/upload_completed_documents_controller.rb - Updated file for EvaluationJourneyTracking callback
3. app/controllers/my_procurements/download_handover_packs_controller.rb - Added code to capture handover activity
4. app/controllers/support/cases/contract_recipients_controller.rb - - Added code to capture handover activity
5. app/controllers/support/cases/document_uploads_controller.rb - Updated file for EvaluationJourneyTracking callback
6. app/controllers/support/cases/email_evaluators_controller.rb - Updated file for EvaluationJourneyTracking callback
7. app/controllers/support/cases/evaluation_due_dates_controller.rb - Updated file for …
> SC-293 Capture Activity log for Handover Journey events

- app/views/support/cases/contract_recipients/_form.html.erb
- app/views/support/cases/contract_recipients/index.html.erb
- app/views/support/cases/evaluators/_form.html.erb
- app/views/support/cases/evaluators/destroy.html.erb
- app/views/support/cases/evaluators/index.html.erb
- spec/features/support/agent_can_add_contract_recipient_spec.rb
- spec/features/support/agent_can_add_evaluators_spec.rb
1. app/views/support/cases/contract_recipients/_form.html.erb - Updated delete button text colour
2. app/views/support/cases/contract_recipients/index.html.erb - Added recipient name in change link for accessibility fix
3. app/views/support/cases/evaluators/_form.html.erb - Updated delete button text colour
4. app/views/support/cases/evaluators/destroy.html.erb - Updated delete button text colour
5. app/views/support/cases/evaluators/index.html.erb - Added evaluator name in change link for accessibility fix
6. spec/features/support/agent_can_add_contract_recipient_spec.rb - Added test case to validate change link
7. spec/features/support/agent_can_add_evaluators_spec.rb - Added test case to validate change link
> SC-221 [Accessibility] Procurement task list - Add evaluators + Add Handover screen

- app/views/support/cases/contract_recipients/index.html.erb
- app/views/support/cases/evaluators/index.html.erb
1. app/views/support/cases/contract_recipients/index.html.erb - Updated change  link accessibility text
2. app/views/support/cases/evaluators/index.html.erb - Updated change  link accessibility text
> SC-221 - Updated change  link accessibility text

- app/controllers/evaluation/upload_completed_documents_controller.rb
- app/controllers/support/cases/document_uploads_controller.rb
- app/controllers/support/cases/email_evaluators_controller.rb
- app/controllers/support/cases/review_evaluations_controller.rb
- app/controllers/support/cases/share_handover_packs_controller.rb
- app/controllers/support/cases/upload_contract_handovers_controller.rb
- app/models/support/interaction.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/evaluation_journey_tracking.rb
- spec/features/support/agent_can_review_evaluations_spec.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
- spec/models/support/interaction_spec.rb
1. app/controllers/evaluation/upload_completed_documents_controller.rb - Updated code to capture incomplete event
2. app/controllers/support/cases/document_uploads_controller.rb - Updated code to capture incomplete event
3. app/controllers/support/cases/email_evaluators_controller.rb- Updated email format
4. app/controllers/support/cases/review_evaluations_controller.rb - Updated code to capture incomplete event
5. app/controllers/support/cases/share_handover_packs_controller.rb - Updated email format
6. app/controllers/support/cases/upload_contract_handovers_controller.rb - Updated code to capture incomplete event
7. app/models/support/interaction.rb - Updated code to capture incomplete event
8. app/presenters/support/interaction_presenter.rb - Updated code to capture incomplete event
9. …
> SC-156  Added new incomplete event for evaluation journey

- app/models/support/contract_recipient.rb
- app/models/support/evaluator.rb
- config/locales/en.yml
- spec/models/support/contract_recipient_spec.rb
- spec/models/support/evaluator_spec.rb
1. app/models/support/contract_recipient.rb - Added new validation
2. app/models/support/evaluator.rb - Added new validation
3. config/locales/en.yml - Added new language variable
4. spec/models/support/contract_recipient_spec.rb - Added new test case for validation
5. spec/models/support/evaluator_spec.rb -  Added new test case for validation
> SC-312 Procurement task list - Add users new 100 limit

- app/controllers/evaluation/download_documents_controller.rb
- app/controllers/evaluation/evaluation_approved_controller.rb
- app/models/support/interaction.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/evaluation_journey_tracking.rb
- app/views/evaluation/download_documents/_document_list.html.erb
- app/views/evaluation/download_documents/show.html.erb
- app/views/evaluation/evaluation_approved/show.html.erb
- app/views/evaluation/tasks/show.html.erb
- app/views/evaluation/upload_completed_documents/_form.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250328150747_add_has_downloaded_documents_to_support_evaluators.rb
- db/schema.rb
- spec/features/evaluation/download_documents_spec.rb
- spec/features/evaluation/evaluation_approved_spec.rb
- spec/features/evaluation/task_list_spec.rb
- spec/features/evaluation/upload_completed_documents_spec.rb
- spec/models/support/interaction_spec.rb
1. app/controllers/evaluation/download_documents_controller.rb - Updated file to store download confirmation
2. app/controllers/evaluation/evaluation_approved_controller.rb - Added new controller for evaluation approved page
3. app/models/support/interaction.rb - Added new event to capture all file downloaded 
4. app/presenters/support/interaction_presenter.rb - Added new event to capture all file downloaded 
5. app/services/support/evaluation_journey_tracking.rb - Added new method to capture all file downloaded event
6. app/views/evaluation/download_documents/_document_list.html.erb - Removed green tick icon
7. app/views/evaluation/download_documents/show.html.erb - Added new download confirmation radio options
8. app/views/evaluation/evaluation_approved/show.html.erb - Added new view …
> SC-308 UR Enhancements to the Evaluation Journey

- app/controllers/my_procurements/download_handover_packs_controller.rb
- app/controllers/support/cases/email_evaluators_controller.rb
- app/controllers/support/cases/share_handover_packs_controller.rb
- app/models/support/interaction.rb
- app/presenters/support/case_presenter.rb
- app/presenters/support/interaction_presenter.rb
- app/services/support/evaluation_journey_tracking.rb
- app/views/evaluation/tasks/show.html.erb
- app/views/my_procurements/download_handover_packs/_document_list.html.erb
- app/views/my_procurements/download_handover_packs/show.html.erb
- app/views/my_procurements/tasks/show.html.erb
- db/migrate/20250403085542_add_has_downloaded_documents_to_support_contract_recipients.rb
- db/schema.rb
- spec/features/my_procurements/download_handover_packs_spec.rb
- spec/features/support/agent_can_review_evaluations_spec.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
- spec/features/support/case_contract_handover_tasklist_spec.rb
- spec/models/support/interaction_spec.rb
1. app/controllers/my_procurements/download_handover_packs_controller.rb - Updated file for download all documents event 
2. app/models/support/interaction.rb - Added new download all documents event
3. app/presenters/support/case_presenter.rb - Updated file for download all documents event activity
4. app/presenters/support/interaction_presenter.rb - Added new download all documents event
5. app/services/support/evaluation_journey_tracking.rb - Updated file for download all documents event 
6. app/views/evaluation/tasks/show.html.erb - Updated file for download all documents event 
7. app/views/my_procurements/download_handover_packs/_document_list.html.erb - Removed tick icon form download screen
8. app/views/my_procurements/download_handover_packs/show.html.erb - Added new downloaded …
> SC-336 UR Enhancements to the Contract handover Journey

- app/models/support/contract_recipient.rb
- app/models/support/evaluator.rb
- config/locales/validation/en.yml
- spec/models/support/contract_recipient_spec.rb
- spec/models/support/evaluator_spec.rb
Added max length validation for evaluator first name & last name and contract recipient  first name & last name
> SC-287 Add Evaluators or Contract Recipients - First and Last name validation

- app/javascript/controllers/date_validation_controller.js
- app/javascript/controllers/index.js
- app/views/support/cases/evaluation_due_dates/edit.html.erb
1. app/javascript/controllers/date_validation_controller.js - Added new date field validation JavaScript file
2. app/javascript/controllers/index.js - Updated file for date field validation
3. app/views/support/cases/evaluation_due_dates/edit.html.erb -  Updated file for date field validation
> SC-209 Set due date - Error state clears all data from field when it shouldnt

- .github/actions/build-docker-image/action.yml
- .github/workflows/ci-full-pipeline.yml
- .github/workflows/codeql.yml
- .github/workflows/support-knapsack-generate-json.yml
- _typos.toml
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
> Fix build for GitHub breaking changes

- app/presenters/support/interaction_presenter.rb
- app/views/support/cases/show/_case_history.html.erb
- config/locales/en.yml
- spec/features/support/agent_can_add_contract_recipient_spec.rb
- spec/features/support/agent_can_add_evaluation_due_date_spec.rb
- spec/features/support/agent_can_add_evaluators_spec.rb
- spec/features/support/agent_can_review_evaluations_spec.rb
- spec/features/support/agent_can_upload_contract_handover_pack_spec.rb
- spec/features/support/agent_can_upload_evaluation_documents_spec.rb
1. app/presenters/support/interaction_presenter.rb - Added condition to hide additional content
2.  app/views/support/cases/show/_case_history.html.erb - Removed condition to display all evaluation and handover journey   interaction message
3. config/locales/en.yml - Added new language variable
4. spec/features/support/agent_can_add_contract_recipient_spec.rb - Added new test case to check the case history
5. spec/features/support/agent_can_add_evaluation_due_date_spec.rb - Added new test case to check the case history
6. spec/features/support/agent_can_add_evaluators_spec.rb -  Added new test case to check the case history
7. spec/features/support/agent_can_review_evaluations_spec.rb - Added new test case to check the case history
8. …
> SC-264 Case History for Evaluation Journey Events

- Dockerfile
GitHub has added a new Dockerfile validation service, and it has raised some warnings. This fixes those, along with some other warnings found with hadolint.
> Fix docker warnings

- Gemfile.lock
- app/components/submit_button_component.html.erb
- app/components/submit_button_component.rb
- app/controllers/energy/application_controller.rb
- app/controllers/energy/school_selections_controller.rb
- app/forms/energy/school_selections_form.rb
- app/forms/energy/school_selections_form_schema.rb
- app/views/energy/onboarding/before_you_start.html.erb
- app/views/energy/onboarding/guidance.html.erb
- app/views/energy/onboarding/join_the_scheme.html.erb
- app/views/energy/school_selections/_form.html.erb
- app/views/energy/school_selections/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- spec/features/energy/school_selections_spec.rb
- spec/rails_helper.rb
1. app/components/submit_button_component.html.erb - Added new file for submit button component 
2. app/components/submit_button_component.rb -  Added new file for submit button component 
3. app/controllers/energy/school_selections_controller.rb - Added new controller for school selections 
4. app/forms/energy/school_selections_form.rb - Added new form for school selection 
5. app/forms/energy/school_selections_form_schema.rb - Added new file for school selection validation
6. app/views/energy/school_selections/show.html.erb - Added new view file for school selections 
7. app/views/energy/school_selections/_form.html.erb - Added new view file for school selections 
8. config/locales/en.yml - Added new language variable
9. config/locales/validation/en.yml - Added new language variable for …
> ES-269 Onboarding screen 4.5: School selection

- app/controllers/energy/onboarding_controller.rb
- app/controllers/sessions_controller.rb
New session variable to trigger post sign-in redirect to first screen of the onboarding flow
> Post sign-in redirect to school picker screen

- app/controllers/customer_satisfaction_surveys/clear_to_use_ratings_controller.rb
- app/controllers/customer_satisfaction_surveys/easy_to_use_ratings_controller.rb
- app/controllers/customer_satisfaction_surveys/improvements_controller.rb
- app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb
- app/controllers/customer_satisfaction_surveys/research_opt_ins_controller.rb
- app/controllers/customer_satisfaction_surveys/satisfaction_levels_controller.rb
- app/controllers/customer_satisfaction_surveys/satisfaction_reasons_controller.rb
- app/controllers/customer_satisfaction_surveys_controller.rb
- app/services/emails/customer_satisfaction_survey.rb
- app/services/support/email_templates.rb
- spec/controllers/customer_satisfaction_surveys/easy_to_use_ratings_controller_spec.rb
- spec/features/support/case_resolution_spec.rb
- spec/requests/customer_satisfaction_survey/customer_satisfaction_survey_flow_spec.rb
1. app/controllers/customer_satisfaction_surveys/clear_to_use_ratings_controller.rb - Updated redirect path for NPS
2. app/controllers/customer_satisfaction_surveys/easy_to_use_ratings_controller.rb - Updated redirect path for NPS
3. app/controllers/customer_satisfaction_surveys/improvements_controller.rb -  Updated redirect path for NPS
4. app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb - Updated redirect path for NPS
5. app/controllers/customer_satisfaction_surveys/research_opt_ins_controller.rb - Updated redirect path for NPS
6. app/controllers/customer_satisfaction_surveys/satisfaction_levels_controller.rb - Moved question to end of survey 
7. app/controllers/customer_satisfaction_surveys/satisfaction_reasons_controller.rb -  Moved question to …
> SC-310 Move to Net Promoter Score (NPS)

- .rubocop_todo.yml
- app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb
1. app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb -fixed callback action issue
> SC-310 Move to Net Promoter Score (NPS) - error fix

- app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb
1. app/controllers/customer_satisfaction_surveys/recommendation_likelihoods_controller.rb - Updated survey started in new  NPS flow
> SC-310 Move to Net Promoter Score (NPS) -  (survey started fix)

- app/controllers/energy/tasks_controller.rb
- app/views/energy/tasks/show.html.erb
- config/locales/en.yml
- config/routes.rb
1. app/controllers/energy/tasks_controller.rb - Added new task controller
2. app/views/energy/tasks/show.html.erb - Added new view file
3. config/locales/en.yml - Added new language variable
4. config/routes.rb - Added new route for tasks list
> ES-163 Screen 9: Provide information about your school task list [placeholder]

- app/controllers/application_controller.rb
- app/controllers/cec/application_controller.rb
- app/controllers/cec/management/agents_controller.rb
- app/controllers/cec/management/base_controller.rb
- app/controllers/cec/onboarding_cases_controller.rb
- app/controllers/cms_entry_points_controller.rb
- app/models/support/agent/role_assignable.rb
- app/policies/cms_portal_policy.rb
- app/views/cec/management/base/index.html.erb
- app/views/cec/onboarding_cases/index.html.erb
- app/views/layouts/_navigation_links.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/controllers/cms_entry_points_controller_spec.rb
- spec/features/cec/management/admin_can_create_an_agent_spec.rb
- Add CEC Admin and CEC Staff Member roles
- Add CEC permissions and redirects
- Create placeholder homepage and management page within /cec
> ES-288 - Create CEC Admin and CEC Staff Member roles and portal

- app/controllers/energy/authorisation_controller.rb
- app/controllers/energy/school_selections_controller.rb
- app/controllers/energy/switch_energy_controller.rb
- app/forms/energy/form.rb
- app/forms/energy/switch_energy_form.rb
- app/forms/energy/switch_energy_form_schema.rb
- app/models/energy/case_creatable.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/authorisation/show.html.erb
- app/views/energy/switch_energy/_form.html.erb
- app/views/energy/switch_energy/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- spec/factories/energy/onboarding_case_organisations.rb
- spec/factories/energy/onboarding_cases.rb
- spec/features/energy/switch_energy_spec.rb
1. app/controllers/energy/application_controller.rb - Added new application controller for Energy module 
2. app/controllers/energy/switch_energy_controller.rb - Added new controller file for switch energy
3. app/forms/energy/form.rb - Added new form for validation 
4. app/forms/energy/switch_energy_form.rb - Added new form for validation
5. app/forms/energy/switch_energy_form_schema.rb - Added new form schema for validation 
6. app/models/energy/switch_energy.rb - Added new model for switch energy
7. app/views/energy/switch_energy/_form.html.erb - Added new view file
8. app/views/energy/switch_energy/index.html.erb - Added new view file
9. config/locales/en.yml - Added new language variable
10. config/locales/validation/en.yml - Added new language variable for validation
11. …
> ES-160 Are you switching electricity, gas, or both?

- app/controllers/energy/gas_meter_controller.rb
- app/controllers/energy/gas_suppliers_controller.rb
- app/models/energy/gas_meter.rb
- app/views/energy/gas_meter/index.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- spec/features/energy/gas_meter_summary_spec.rb
1. [4600412](https://github.com/DFE-Digital/buy-for-your-school/pull/2110/commits/460041228b027ab7eccfc47f2634cba9f07a41c8) -  Updated files for MPRN summary page
> ES-212 Screen 7.3: Gas info - MPRN summary (multi meter only)

- app/controllers/energy/electric_suppliers_controller.rb
- app/controllers/energy/gas_suppliers_controller.rb
- app/controllers/energy/switch_energies_controller.rb
- app/forms/energy/electric_supplier_form.rb
- app/forms/energy/electric_supplier_form_schema.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/electric_suppliers/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- spec/features/energy/current_electric_supplier_spec.rb
- spec/features/energy/current_gas_supplier_spec.rb
- spec/support/shared/energy_suppliers.rb
This PR similar to gas supplier details. It appears only based on the user's switch energy type. This will update electric_current_supplier and electric_current_contract_end_date on the energy_onboarding_case_organisations table.
> ES-216 Add current electricity supplier details - Screen 8

- app/controllers/energy/gas_bill_consolidations_controller.rb
- app/forms/energy/gas_bill_consolidation_form.rb
- app/forms/energy/gas_bill_consolidation_form_schema.rb
- app/views/energy/gas_bill_consolidations/_form.html.erb
- app/views/energy/gas_bill_consolidations/show.html.erb
- app/views/energy/gas_meter/index.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250505093641_add_gas_bill_consolidation_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/gas_bill_consolidation_spec.rb
[80bff30](https://github.com/DFE-Digital/buy-for-your-school/pull/2112/commits/80bff30d6d13d3418ed940761f7f5a88c315ef01)  - Added new files for gas bill consolidation
> ES-213 Gas info - MPRNs bill consolidation (multi meter only)

- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_bill_consolidations_controller.rb
- app/forms/energy/electricity_meter_type_form.rb
- app/forms/energy/electricity_meter_type_form_schema.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/electricity_meter_types/_form.html.erb
- app/views/energy/electricity_meter_types/show.html.erb
- app/views/energy/tasks/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250506122947_add_electricity_meter_type_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/electricity_meter_type_spec.rb
[60d384d](https://github.com/DFE-Digital/buy-for-your-school/commit/60d384d66d46562ae94b96b9e56fa6988fe2201f) Added new files for electricity info - single or multi meter site
> ES-217 Screen: 8.1: Electricity info - single or multi meter site

- app/controllers/energy/electric_suppliers_controller.rb
- app/controllers/energy/gas_suppliers_controller.rb
- app/forms/energy/electric_supplier_form.rb
- app/forms/energy/electric_supplier_form_schema.rb
- app/forms/energy/gas_supplier_form.rb
- app/forms/energy/gas_supplier_form_schema.rb
- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/gas_suppliers/_form.html.erb
- config/locales/validation/en.yml
This PR introduces additional date validation and adds a toggle option for cases where the user selects an other supplier.
> ES-162 Add extra date validation and other supplier toggle

- app/controllers/energy/application_controller.rb
- app/controllers/energy/electric_suppliers_controller.rb
- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_bill_consolidations_controller.rb
- app/controllers/energy/gas_meter_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- app/controllers/energy/gas_suppliers_controller.rb
- app/controllers/energy/switch_energies_controller.rb
- app/forms/energy/gas_single_multi_form.rb
- app/forms/energy/gas_single_multi_form_schema.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/gas_single_multis/_form.html.erb
- app/views/energy/gas_single_multis/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250502153702_add_gas_single_multi_to_energy_onboarding_case_organisations.rb
- db/schema.rb
- spec/features/energy/gas_single_multi_spec.rb
- spec/models/support/establishment_search_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/ES-164
> Add single multi gas meter screen

- app/views/energy/onboarding/guidance.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-204
> Correct content of guidance page

- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-135
> Correct content for Join screen

- app/controllers/energy/application_controller.rb
- app/controllers/energy/electricity_meter_controller.rb
- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_meter_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/electricity_meter/index.html.erb
- app/views/energy/gas_meter/index.html.erb
- app/views/energy/tasks/show.html.erb
- spec/features/energy/electricity_meter_summary_spec.rb
- spec/features/energy/gas_meter_summary_spec.rb
[269b61d](https://github.com/DFE-Digital/buy-for-your-school/pull/2125/commits/269b61d940d0688c2c35167323145b6b5233bba1) - Updated redirect path to unblock the end-to-end flow
> [Energy] Updated redirect path to unblock the end-to-end flow

- config/locales/en.yml
[c87b9ac](https://github.com/DFE-Digital/buy-for-your-school/commit/c87b9ac9441c2efdb9b25f04df1a2440b748498b) - Updated content as per new prototype
> ES-211 Content update

- app/controllers/energy/tasks_controller.rb
- app/models/energy/task_list.rb
- app/views/energy/tasks/show.html.erb
- config/locales/en.yml
- spec/factories/energy/electricity_meters.rb
- spec/factories/energy/gas_meters.rb
- spec/factories/energy/onboarding_case_organisations.rb
- spec/models/energy/task_list_spec.rb
This is the task list for information about your schools. Its not the final version as we haven't completed all the screens. 
There will be more work to this task list on later stages,
Currently Tasklist class has tests for only available screens, Need to add more tests later stage including feature test.
> ES-163 | Add energy Task list

- app/controllers/cec/onboarding_cases_controller.rb
- app/helpers/application_helper.rb
- app/helpers/support/sort_helper.rb
- app/models/support/case/filterable.rb
- app/views/cec/onboarding_cases/case_list/_case_list.html.erb
- app/views/cec/onboarding_cases/case_list/_filters.html.erb
- app/views/cec/onboarding_cases/case_list/case_panel/_case_panel.html.erb
- app/views/cec/onboarding_cases/case_list/case_panel/_top_left_pane.html.erb
- app/views/cec/onboarding_cases/case_list/case_panel/_top_right_pane.html.erb
- app/views/cec/onboarding_cases/index.html.erb
- app/views/cec/onboarding_cases/index/_tab_all_cases.html.erb
- app/views/cec/onboarding_cases/index/_tab_my_cases.html.erb
- spec/features/cec/case_list_spec.rb
- spec/support/shared/cec_agent.rb
- Add all cases and my cases to the homepage
- Show list of support cases with a sub-category of DfE Energy for Schools
- Include filters and sort
- Look similar to procops support cases list
> ES-287 cec homepage

- app/controllers/energy/electric_bill_consolidations_controller.rb
- app/controllers/energy/gas_bill_consolidations_controller.rb
- app/controllers/energy/site_contact_details_controller.rb
- app/forms/energy/site_contact_details_form.rb
- app/forms/energy/site_contact_details_form_schema.rb
- app/models/energy/task_list.rb
- app/views/energy/site_contact_details/_form.html.erb
- app/views/energy/site_contact_details/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250513125900_add_site_contact_to_onboarding_case_organisations.rb
- db/schema.rb
- spec/features/energy/site_contact_details_spec.rb
[102b535](https://github.com/DFE-Digital/buy-for-your-school/commit/102b5353e2e408863c48f8079f0d3893d6287900) - Added new files for site contact details
[d7121c9](https://github.com/DFE-Digital/buy-for-your-school/pull/2131/commits/d7121c95986ade456341d2f742dccaa9f43143f6) - Removed alphabet validation for first_name and last_name
> ES-220 Screen 10: Site contact details

- app/forms/energy/electric_supplier_form_schema.rb
- app/forms/energy/gas_supplier_form_schema.rb
- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/gas_suppliers/_form.html.erb
- config/locales/validation/en.yml
- spec/features/energy/current_electric_supplier_spec.rb
- spec/features/energy/current_gas_supplier_spec.rb
- spec/support/shared/current_energy_contract.rb
- spec/support/shared/energy_suppliers.rb
This is rework PR for ticket: [ES-162](https://dfedigital.atlassian.net.mcas.ms/browse/ES-162), Add more date validation and improved styling.
> improve date validation and resolve minor styling issues

- app/views/energy/electric_bill_consolidations/_form.html.erb
- app/views/energy/electric_bill_consolidations/show.html.erb
- app/views/energy/gas_bill_consolidations/_form.html.erb
- app/views/energy/gas_bill_consolidations/show.html.erb
This is a rework of  previously QAd ticket.
https://dfedigital.atlassian.net.mcas.ms/browse/ES-219
> ES-219 | fix styling issue

- app/controllers/energy/authorisation_controller.rb
- app/controllers/energy/switch_energies_controller.rb
- config/locales/en.yml
- spec/features/energy/electricity_meter_summary_spec.rb
- spec/features/energy/gas_meter_summary_spec.rb
- spec/features/energy/switch_energy_authorisation_spec.rb
[68224b1](https://github.com/DFE-Digital/buy-for-your-school/pull/2136/commits/68224b1441194f6a10ceb5897654995f78b8a3e5) - Added Onboarding case - return rule
> ES-360 Onboarding case - return rule (allow more than one case per Org)

- app/controllers/energy/gas_meter_controller.rb
[f099724](https://github.com/DFE-Digital/buy-for-your-school/pull/2133/commits/f099724c1b12cb952458ba0646ab22b1ba602074) - Updated back URL path
> ES-212 - Back URL path update

- app/controllers/energy/electricity_meter_controller.rb
[20d3087](https://github.com/DFE-Digital/buy-for-your-school/commit/20d308709ef0269e22c2854fe330f6d642d61ef3) - Updated back url path
> ES-218 - Back URL path update

- app/views/usability_surveys/new.html.erb
- config/locales/en.yml
Minor fixes to styling of form labels and text
> Fix Usability survey copy and styling

- app/forms/energy/electric_supplier_form_schema.rb
- app/forms/energy/gas_supplier_form_schema.rb
- app/models/energy/task_list.rb
- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/gas_suppliers/_form.html.erb
- app/views/energy/tasks/show.html.erb
- spec/models/energy/task_list_spec.rb
- Slight improvement to task list.
- Set max length to gas and electrical other supplier input box
> ES-163 | improve and rework task list

- app/controllers/energy/electricity_meter_controller.rb
- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_meter_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- app/models/energy/task_list.rb
- app/views/energy/electricity_meter/index.html.erb
- app/views/energy/gas_meter/index.html.erb
- config/locales/en.yml
[dec0f14](https://github.com/DFE-Digital/buy-for-your-school/commit/dec0f14f7e23401b47645d113bd1796651f7b2cd) - Updated back url path
> ES-165 Updated back url path

- app/controllers/energy/site_contact_details_controller.rb
- app/forms/energy/site_contact_details_form_schema.rb
- app/models/energy/task_list.rb
- config/locales/en.yml
- config/locales/validation/en.yml
- spec/features/energy/site_contact_details_spec.rb
[1cd82dd](https://github.com/DFE-Digital/buy-for-your-school/commit/1cd82ddaae579156b9f2d55d3c6bd0e37957466f) - Removed last name mandatory validation and updated error message.
> ES-220 - Removed last name mandatory validation

- app/controllers/energy/application_controller.rb
- app/controllers/energy/electricity_meter_controller.rb
- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_meter_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- app/models/energy/task_list.rb
- config/locales/en.yml
[77dc63e](https://github.com/DFE-Digital/buy-for-your-school/commit/77dc63ed8440696b6e2a409abe660b8eb8dcf61f) -  Set rule to add more MPRN/MPAN button and updated back button logic
> ES-218 Set rule to add more MPRN/MPAN button

- app/controllers/energy/vat_certificates_controller.rb
- app/controllers/energy/vat_person_responsibles_controller.rb
- app/controllers/energy/vat_rate_charges_controller.rb
- app/forms/energy/vat_certificate_form.rb
- app/forms/energy/vat_certificate_form_schema.rb
- app/views/energy/vat_certificates/_form.html.erb
- app/views/energy/vat_certificates/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250516112444_add_vat_certificate_declared_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/vat_certificate_spec.rb
[0fcc1f1](https://github.com/DFE-Digital/buy-for-your-school/commit/0fcc1f12cdbf07d0d9695aa381e0272fa38f00ed) Added new files for VAT certificate of declaration
[3693b0d](https://github.com/DFE-Digital/buy-for-your-school/pull/2144/commits/3693b0d2ceae4436025ae5efa27ad10b8133bf9c) - Updated redirect path when vat rate set as 20%
> ES-327 Screen 11.3 VAT certificate of declaration

- app/controllers/energy/billing_preferences_controller.rb
- app/controllers/energy/vat_certificates_controller.rb
- app/forms/energy/billing_preferences_form.rb
- app/forms/energy/billing_preferences_form_schema.rb
- app/models/energy/onboarding_case_organisation.rb
- app/views/energy/billing_preferences/_form.html.erb
- app/views/energy/billing_preferences/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250516133110_add_billing_preferences_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/billing_preferences_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-167
> ES-167 Billing prefs

- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- app/controllers/energy/switch_energies_controller.rb
- spec/features/energy/electricity_meter_type_spec.rb
- spec/features/energy/gas_single_multi_spec.rb
- spec/features/energy/switch_energy_spec.rb
…type
[6c6f7fd](https://github.com/DFE-Digital/buy-for-your-school/commit/6c6f7fde36433a189b3b92e74bc47a3d942499f4) - Updated files to reset data when user switch energy type and switch meter type
> ES-392 Remove energy meter data when choices are changed. (screens 6, 7.1 & 8.1)

- app/components/energy_form_buttons_component.html.erb
- app/components/energy_form_buttons_component.rb
- app/controllers/energy/application_controller.rb
- app/controllers/energy/billing_address_confirmations_controller.rb
- app/controllers/energy/billing_preferences_controller.rb
- app/forms/energy/billing_address_confirmation_form.rb
- app/forms/energy/billing_address_confirmation_form_schema.rb
- app/views/energy/billing_address_confirmations/_form.html.erb
- app/views/energy/billing_address_confirmations/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250519110728_add_billing_address_confirmation_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/billing_address_confirmation_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/ES-340
> Add confirm billing address

- app/controllers/energy/vat_person_responsibles_controller.rb
Ticket: https://dfedigital.atlassian.net/browse/ES-325
> Es 325 fix erroring redirect

- .rubocop_todo.yml
- app/models/energy/gas_meter.rb
- config/locales/validation/en.yml
- spec/features/energy/gas_meter_details_spec.rb
[36a3e1d](https://github.com/DFE-Digital/buy-for-your-school/commit/36a3e1dcafdb1ebd4240a9be6ba831b0596af6db) - Updated error message and MPRN uniqueness
> Screen 7.2.1 MPRN validation on Gas meter details

- app/controllers/energy/vat_alt_person_responsibles_controller.rb
- app/forms/energy/vat_alt_person_responsible_form.rb
- app/forms/energy/vat_alt_person_responsible_form_schema.rb
- app/views/energy/vat_alt_person_responsibles/_form.html.erb
- app/views/energy/vat_alt_person_responsibles/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- db/migrate/20250516113342_add_vat_alt_person_responsible_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/vat_alt_person_responsible_spec.rb
Ticket: [ES-326](https://dfedigital.atlassian.net/browse/ES-326)
This PR is to add VAT alternative contact information, screen 11.2
- Without establishment group
- With establishment group
> ES-326 | Add VAT alternative contact information

- app/controllers/energy/confirmations_controller.rb
- app/views/energy/confirmations/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/energy/confirmations_spec.rb
[ES-214](https://dfedigital.atlassian.net/browse/ES-214)
This is final screen Information Submitted, its a static page
> Es 214 | Add final screen Information submitted

- app/controllers/energy/school_selections_controller.rb
- app/controllers/energy/service_availability_controller.rb
- app/views/energy/service_availability/_email_body.html.erb
- app/views/energy/service_availability/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/energy/service_availability_spec.rb
[2a69fad](https://github.com/DFE-Digital/buy-for-your-school/commit/2a69fad50e3131f6cce82b0fe0303f4a8832b30e) - Added new files for organisational group selection error page
[5ead8b8](https://github.com/DFE-Digital/buy-for-your-school/pull/2155/commits/5ead8b8325069dddc600bc37fdb0c317e9a45f8c) - Fixed spec error
> ES-343 - Screen 4.5.1: Error screen for organisational group selection (not establishment)

- app/controllers/energy/authorisation_controller.rb
- config/locales/en.yml
[81b7a74](https://github.com/DFE-Digital/buy-for-your-school/commit/81b7a7421b93ed3bd1389ea7757bda8a5e5ff9ff) - Updated flash message when organisation have multiple cases
> ES-360 - Onboarding case - return rule  - Updated flash message

- app/controllers/energy/vat_person_responsibles_controller.rb
- spec/features/energy/vat_person_responsible_spec.rb
Rework ticket: Update redirect url to alternate VAT contact page when the user select No from the VAT declaration form.
> ES-326 | Rework update redirect url to alternate VAT contact page

- app/controllers/energy/electricity_meter_controller.rb
- app/controllers/energy/gas_meter_controller.rb
[2acf2c7](https://github.com/DFE-Digital/buy-for-your-school/commit/2acf2c7e6ddecebb9a9af8330435f02fa26a76d3) - Fixed back link URL of gas meter/electricity meter
> Energy: Gas meter / Electricity meter back url issue fix

- .rubocop_todo.yml
- app/models/energy/electricity_meter.rb
- spec/features/energy/electricity_meter_details_spec.rb
[7883071](https://github.com/DFE-Digital/buy-for-your-school/commit/7883071c742545037bb3ec4719f9842d66e8ea51) - updated MPAN uniqueness check
> ES-331 - MPAN validation on Electricity meter details - updated MPAN uniqueness check

- app/controllers/energy/authorisation_controller.rb
- app/views/energy/authorisation/_email_body.html.erb
- config/locales/en.yml
- spec/features/energy/switch_energy_authorisation_spec.rb
[34256cf](https://github.com/DFE-Digital/buy-for-your-school/commit/34256cf82f1157d3ca008aa1f427df4b509ef532) - Updated email body text for support link
> ES-360 - Onboarding case - return rule - Updated email body text for support link

- app/views/usability_surveys/new.html.erb
Change heading on Usability Survey from H2 to H1
> Change heading on Usability Survey from H2 to H1

- app/controllers/energy/vat_rate_charges_controller.rb
- app/forms/energy/vat_rate_charge_form.rb
- app/forms/energy/vat_rate_charge_form_schema.rb
- app/views/energy/vat_rate_charges/_form.html.erb
- spec/features/energy/vat_rate_charge_spec.rb
[c3ab0ff](https://github.com/DFE-Digital/buy-for-your-school/commit/c3ab0ff9bed04afb740c5aa6728b5ca2fb25bd18) - Updated number validation in form schema
[5792d23](https://github.com/DFE-Digital/buy-for-your-school/pull/2179/commits/5792d2320d1fd4747d4c3a439ea294c0c6b2e90d) -  reset reduced rate of VAT and VAT registration number when VAT rate set as 20%
> ES-413 VAT % rate - Inconsistent validation methods 

- app/controllers/energy/letter_of_authorisations_controller.rb
- app/forms/energy/letter_of_authorisation_form.rb
- app/forms/energy/letter_of_authorisation_form_schema.rb
- app/views/energy/letter_of_authorisations/_form.html.erb
- app/views/energy/letter_of_authorisations/show.html.erb
- config/locales/en.yml
- config/locales/validation/en.yml
- config/routes.rb
- db/migrate/20250526141056_add_loa_agreed_to_onboarding_case_organisation.rb
- db/schema.rb
- spec/features/energy/confirmations_spec.rb
- spec/features/energy/letter_of_authorisation_spec.rb
This PR is to add letter of authority screen (screen 14), New boolean filed was added to energy_onboarding_case_organisations table to store all 3 check boxes value as a single.
.......
.......
> ES-169 | Add letter of authority - Screen 14

- app/controllers/energy/electricity_meter_types_controller.rb
- app/controllers/energy/gas_single_multis_controller.rb
- spec/features/energy/electricity_meter_type_spec.rb
- spec/features/energy/gas_single_multi_spec.rb
[834fe6a](https://github.com/DFE-Digital/buy-for-your-school/commit/834fe6a901b6856487d8a8918258ff5b65b506d6) - Reset meter data when the user switches meter type
> ES-392 - Remove energy meter data when choices are changed

- app/views/energy/letter_of_authorisations/show.html.erb
- config/locales/en.yml
https://dfedigital.atlassian.net.mcas.ms/browse/ES-169
- This is part of a copy changes. Replacing placeholder with actual school name within translations
> ES-169 - replace placeholder with school name

- .rubocop_todo.yml
- app/controllers/energy/vat_alt_person_responsibles_controller.rb
- app/controllers/energy/vat_rate_charges_controller.rb
- app/models/energy/task_list.rb
- spec/features/energy/tasklist_spec.rb
- spec/features/energy/vat_alt_person_responsible_spec.rb
- spec/features/energy/vat_rate_charge_spec.rb
- spec/models/energy/task_list_spec.rb
- Redirect from the task list to the meter type pages for gas and electric if it hasn't been selected before (clicked discard and go to task list rather than saved on the meter type screen)
- Changes logic so if vat rate declared is false then it's in progress rather than complete (so user can't progress unless boxes are ticked)
- Remove vat data relating to 5% vat rate when vat rate is changed to 20%
- Set default address when vat details are incorrect and there are no addresses to choose from on the vat contact screen
> ES-395 fixes

- app/assets/stylesheets/components/supported/_case-summary.scss
[1466c00](https://github.com/DFE-Digital/buy-for-your-school/commit/1466c00bf5b744a8177915740b84522a0794902e) -  updated option group 5 and 6 color
> ES-401 stages on Energy cases - updated option group 5 and 6 color 

- app/controllers/energy/letter_of_authorisations_controller.rb
- spec/controllers/energy/letter_of_authorisations_controller_spec.rb
This PR is to temporarily stop any energy form submission email send out functionality.
> stop form submission email sending

- app/controllers/cec/application_controller.rb
- app/controllers/support/cases/message_threads_controller.rb
- app/controllers/support/notifications/mark_all_reads_controller.rb
- app/controllers/support/notifications/reads_controller.rb
- app/controllers/support/notifications_controller.rb
- app/views/layouts/_navigation_links.html.erb
- app/views/layouts/_navigation_links_notifications.html.erb
- app/views/support/cases/message_threads/show.html.erb
- app/views/support/notifications/_notification.html.erb
- app/views/support/notifications/index.html.erb
- app/views/support/notifications/topics/_case_assigned.html.erb
- app/views/support/notifications/topics/_case_closed.html.erb
- app/views/support/notifications/topics/_case_email_received.html.erb
- app/views/support/notifications/topics/_case_reopened.html.erb
- config/routes.rb
- spec/features/cec/cec_agent_can_view_notifications_spec.rb
- spec/requests/cec/notifications/mark_all_reads_spec.rb
- spec/requests/cec/notifications/mark_as_read_spec.rb
- spec/support/sign_in_helpers.rb
[adf9f53](https://github.com/DFE-Digital/buy-for-your-school/commit/adf9f53f500ea5b1795be94dae39aeb077eaf27f) - Updated files to enable notifications to the cec portal
> ES-472 - Enable Notifications view in CEC interface

- app/controllers/support/cases/searches_controller.rb
- app/views/layouts/_navigation_links.html.erb
- app/views/support/cases/forms/_simple_case_filters.html.erb
- app/views/support/cases/searches/_result.html.erb
- app/views/support/cases/searches/index.html.erb
- app/views/support/cases/searches/new.html.erb
- config/routes.rb
- spec/features/cec/search_cases_spec.rb
[414cb74](https://github.com/DFE-Digital/buy-for-your-school/commit/414cb74599ae265422de8ed2aeed1690639959f7) - Updated files for CEC case search
> ES-470 - Search for a case from CEC interface

- app/services/energy/documents/check_your_answers.rb
- app/services/energy/documents/letter_of_authority.rb
- app/services/energy/documents/vat_declaration_form_edf.rb
- app/services/energy/documents/vat_declaration_form_total.rb
- app/services/energy/generate_documents_and_send_email.rb
- spec/features/energy/letter_of_authorisation_spec.rb
- spec/services/energy/documents/vat_declaration_form_edf_spec.rb
- spec/services/energy/documents/vat_declaration_form_total_spec.rb
- spec/support/shared/attachable_pdfs.rb
> add main service to generate document and send email

- app/views/energy/onboarding/join_the_scheme.html.erb
- config/locales/en.yml
https://dfedigital.atlassian.net/browse/ES-519
Minor content changes on start page
> ES-519 | content change - start page

- app/controllers/support/application_controller.rb
- app/controllers/support/cases/application_controller.rb
- app/controllers/support/cases/message_threads_controller.rb
- app/controllers/support/email_read_status_controller.rb
- app/views/support/cases/message_threads/_thread.html.erb
- app/views/support/cases/message_threads/outlook/_actions.html.erb
- config/routes.rb
- spec/requests/cec/email_read_status_spec.rb
[ece3b1a](https://github.com/DFE-Digital/buy-for-your-school/commit/ece3b1aeb9dae0bd5d7a20db762a1c8ef73ae7d8)  -  Updated the files to handle email read status updates.
> ES-506 CEC User - Messages getting "Content missing" 

- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/gas_suppliers/_form.html.erb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-518
> ES-518 Associate "other" label with field

- app/controllers/energy/authorisation_controller.rb
- spec/features/energy/multi_case_for_school_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-510
> ES-510 Multi case for school

- app/controllers/support/management/email_template_groups_controller.rb
- app/controllers/support/management/email_templates_controller.rb
- app/views/cec/management/base/index.html.erb
- app/views/support/management/email_templates/edit.html.erb
- app/views/support/management/email_templates/form/_form.html.erb
- app/views/support/management/email_templates/index.html.erb
- app/views/support/management/email_templates/new.html.erb
- app/views/support/management/email_templates/template_manager/templates/_template.html.erb
- config/routes.rb
- spec/features/cec/management/admin_can_create_templates_spec.rb
[fec1f8f](https://github.com/DFE-Digital/buy-for-your-school/commit/fec1f8f0bdcea4e6dc32919a9d0e7e9b892f3ee6) - enabled email template link for cec staff
> ES-471 - Ability to create email templates

- app/views/energy/vat_rate_charges/show.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net/browse/ES-426
> ES-426 Fix wrong copy on VAT rate page

- app/models/energy/electricity_meter.rb
- app/models/energy/gas_meter.rb
- app/models/energy/onboarding_case.rb
- app/models/energy/onboarding_case_organisation.rb
- app/presenters/support/case_presenter.rb
- spec/models/energy/electricity_meter_spec.rb
- spec/models/energy/gas_meter_spec.rb
- spec/models/energy/onboarding_case_organisation_spec.rb
…e updated
[dd5c218](https://github.com/DFE-Digital/buy-for-your-school/commit/dd5c218665c0aa722a6fb097db56238518b88224) - updates the updated_at timestamp in Support::Case when onboarding case updated
> ES-501 - Update Case “Updated” Status on Frontend Save

- app/views/energy/billing_preferences/_form.html.erb
[18934a0](https://github.com/DFE-Digital/buy-for-your-school/commit/18934a0bd02daa89ad08e6dc004c4d749a07ecd1) - Fixed form legend issue
> ES-526 - Fieldset and Legend Usage for Clearer Screen Reader

- app/views/energy/electric_suppliers/_form.html.erb
- app/views/energy/electric_suppliers/show.html.erb
- app/views/energy/gas_suppliers/_form.html.erb
- app/views/energy/gas_suppliers/show.html.erb
- config/locales/en.yml
- spec/features/energy/check_your_answers_spec.rb
- spec/features/energy/tasklist_spec.rb
- spec/support/shared/current_energy_contract.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-476
> ES-476 Fix gas/elec contract screen content

- db/migrate/20250716154247_revert_form_submitted_at_to_case_6299.rb
- db/schema.rb
ticket: https://dfedigital.atlassian.net/browse/ES-588
This migration PR will reset form_submitted_email_sent and submitted_at fields on energy_onboarding_cases table.This will allow Milldene Primary School to resubmit the energy form and allow them to amend the form.
> ES-588 | Allow Milldene Primary School to resubmit energy form

- app/services/energy/documents/vat_declaration_form_edf.rb
- spec/services/energy/documents/vat_declaration_form_edf_spec.rb
ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-644
This PR will update customer name to "Department for Education" and update first line of address accordingly. 
removed **Not record** county, joins **locality and city.**
Before:
After
> ES-644 | update customer name on EDF VAT form

- app/controllers/energy/site_contact_details_controller.rb
- app/controllers/energy/vat_alt_person_responsibles_controller.rb
- app/forms/energy/site_contact_details_form_schema.rb
- app/forms/energy/vat_alt_person_responsible_form_schema.rb
- app/forms/schema.rb
- app/models/concerns/sanitise_meter_numbers.rb
- app/models/energy/electricity_meter.rb
- app/models/energy/gas_meter.rb
- app/models/energy/meter_number_format.rb
- spec/features/energy/electricity_meter_details_spec.rb
- spec/features/energy/gas_meter_details_spec.rb
- spec/features/energy/site_contact_details_spec.rb
- spec/features/energy/vat_alt_person_responsible_spec.rb
- spec/support/shared/awkward_space_characters.rb
[2009cb0](https://github.com/DFE-Digital/buy-for-your-school/commit/2009cb00efd0e89d7d5dbbece5409f981f6038ff) - Updated validation for MPAN/MPRN/Phone number
> ES-517 - Allow spaces in numeric input fields (phone number/MPAN/MPRN)

- app/models/energy/task_list.rb
- app/views/energy/check_your_answers/show.html.erb
- config/locales/en.yml
[9da9c84](https://github.com/DFE-Digital/buy-for-your-school/commit/9da9c849ee890a98d19c0e670e11c6e42f23ec01) - Updated files for change link accessibility
> ES-524 - Check your answers - link purpose

- app/controllers/framework_requests/framework_requests_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/specify/create_a_specification_controller.rb
[7dcc271](https://github.com/DFE-Digital/buy-for-your-school/commit/7dcc27140d177b18c89f72d40a255e33f6dd915a) - Updated the redirect URL after school user sign-out
> ES-628 - Energy Onboarding journey sign-out

- app/controllers/energy/application_controller.rb
- app/controllers/energy/onboarding_controller.rb
- app/views/layouts/application.html.erb
- spec/features/specify/layout_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-485
> ES-485 Add link to accessibility gov web page

- app/components/table_component.html.erb
- app/views/energy/onboarding/before_you_start.html.erb
- app/views/energy/onboarding/guidance.html.erb
- config/locales/en.yml
https://dfedigital.atlassian.net/browse/ES-474
Content changes on guidance page with new amendments.
> ES-474 | content changes - guidance page and before you start pages

- app/controllers/energy/application_controller.rb
- app/controllers/energy/onboarding_controller.rb
- app/controllers/energy/service_availability_controller.rb
- app/views/energy/onboarding/start.html.erb
- app/views/energy/service_availability/show.html.erb
- config/initializers/energy_constants.rb
- config/locales/en.yml
- spec/features/energy/service_availability_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/ES-534
> ES-534 Update MAT availability info

- app/views/energy/gas_meter/_form.html.erb
[0d7639b](https://github.com/DFE-Digital/buy-for-your-school/commit/0d7639b934d402e70cb3ff8d6a8cd98784ad9496) - Removed autofocus from the MPRN field
> ES-573 - Do not set autofocus on page load

- config/locales/en.yml
[a8f435e](https://github.com/DFE-Digital/buy-for-your-school/commit/a8f435ebba16bac16dce0a44fbbaaf3842d5b9ae) - Updated the alt text content
> ES-452 - Ineffective alt text on MPAN half hour image

- app/controllers/support/cases/resolutions_controller.rb
- spec/features/cec/case_resolution_spec.rb
- Disable exit survey when it's a dfe energy for schools category case
> ES-725 - Disable exit survey when it's a dfe energy for schools category case

- app/models/email/template_parser.rb
- app/services/energy/emails/direct_debit_vat_edf_mailer.rb
- app/services/energy/emails/direct_debit_vat_edf_variable_parser.rb
- app/services/energy/generate_documents_and_send_email.rb
- app/views/energy/letter_of_authorisations/_direct_debit_vat_edf_email_template.erb
- doc/feature-flags.md
- spec/rails_helper.rb
- spec/services/energy/emails/direct_debit_vat_edf_variable_parser_spec.rb
[82ca3bf](https://github.com/DFE-Digital/buy-for-your-school/commit/82ca3bfd1b45dd6c6db19b3abf2914233216c199) - updated files to send auto email vat and dd
> ES-714 - Auto send combined email of VAT and DD to school - Electricity (EDF)

- app/services/energy/emails/direct_debit_vat_total_mailer.rb
- app/services/energy/emails/direct_debit_vat_total_variable_parser.rb
- app/services/energy/generate_documents_and_send_email.rb
- app/views/energy/letter_of_authorisations/_direct_debit_vat_total_email_template.erb
- doc/feature-flags.md
- spec/services/energy/emails/direct_debit_vat_total_variable_parser_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/ES-715
> ES-715 Auto VAT & Direct Debit email for gas (Total)

- app/views/energy/letter_of_authorisations/_direct_debit_vat_edf_email_template.erb
- app/views/energy/letter_of_authorisations/_onboarding_form_dd_edf_email_template.erb
- app/views/energy/letter_of_authorisations/_onboarding_form_vat_edf_email_template.erb
> Updated EDF email template

- app/services/energy/emails/base_mailer.rb
- app/services/energy/emails/onboarding_form_dd_edf_mailer.rb
- app/services/energy/emails/onboarding_form_dd_total_mailer.rb
- app/services/energy/emails/onboarding_form_vat_edf_mailer.rb
- app/services/energy/generate_documents_and_send_email.rb
[fc2c8bc](https://github.com/DFE-Digital/buy-for-your-school/commit/fc2c8bc037b81e7c09235b14dddf178be287b173) - Updated files to attach the respective documents to the auto-sent emails
> Updated files to attach the respective documents to the auto-sent emails

- app/views/specify/create_a_specification/_closing.html.erb
- app/views/specify/create_a_specification/_default.html.erb
- app/views/specify/create_a_specification/_start_button.html.erb
- app/views/specify/create_a_specification/show.html.erb
- config/locales/en.yml
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-625
> ES-625: Add page for "Create a specification is closing" message

- app/views/energy/site_contact_details/show.html.erb
- app/views/energy/vat_certificates/_form.html.erb
Tickets: https://dfedigital.atlassian.net/browse/ES-454, https://dfedigital.atlassian.net/browse/ES-455
Update hint text for site addition and vat certificate pages.
> ES-454, ES-455 update hint text

- config/locales/en.yml
- spec/features/support/case_tasklist_spec.rb
Ticket: https://dfedigital.atlassian.net.mcas.ms/browse/ES-683
> ES-683: Rename 'Handover contract' on ProcOps task list

- _typos.toml
- app/models/frameworks/evaluation/status_changeable.rb
- spec/features/specify/feedback/details_spec.rb
[143aba0](https://github.com/DFE-Digital/buy-for-your-school/commit/143aba01b702f5789c27b81bf70e1709853cb587) - Fixed issue with typos in CI pipeline
> Fixed issue with typos in CI pipeline
