DFE-Digital/buy-for-your-school

.github/workflows/continuous-integration.yml

Heroku is waiting for a passing CI test before automatically deploying, but previously CI would only run on pull requests and not on the resulting merges to develop or main branches. This changes that behaviour, so tests run on any push to those branches as well as any PR.

Run GitHub CI action on merges to main and develop

---

Procfile

Adds a release stage to the `Procfile` so that Heroku will run database migrations during release stages.

Perform database migrations as part of Heroku release stages

---

CHANGELOG.md
Gemfile
Gemfile.lock
app/controllers/answers_controller.rb
app/controllers/application_controller.rb
app/controllers/questions_controller.rb
app/models/question.rb
app/views/pages/planning_start_page.html.erb
app/views/plans/show.html.erb
app/views/questions/new.html.erb

Parent pull request that should be reviewed first: https://github.com/DFE-Digital/buy-for-your-school/pull/12
- install the DfE form builder gem
- iterate the basic planning form so that it's styled with GOV.UK for consistency
- iterate the form so that it uses an `answer` resource instead of generating a very basic post request

[21] Users can see a GOV.UK styled planning form

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/models/answer.rb
app/views/questions/new.html.erb
spec/features/visitors/anyone_can_start_a_planning_journey_spec.rb
spec/models/answer_spec.rb

The last in a sequence of pull requests aimed at delivering story 21! 🎉 
- add basic presence validation for `Answer.response` 
- use default rails error messages for now, we can change these in Rails locales later if needed
- use default styling etc from the DfE form builder gem

[21] Planning form has basic validation

---

.env.example
.env.test
CHANGELOG.md
Gemfile
Gemfile.lock
app.json
app/controllers/questions_controller.rb
app/services/create_planning_question.rb
app/services/get_contentful_entry.rb
app/services/get_contentful_question.rb
app/views/errors/contentful_entry_not_found.html.erb
config/initializers/dotenv.rb
config/locales/en.yml
spec/features/visitors/anyone_can_start_a_planning_journey_spec.rb
spec/rails_helper.rb
spec/services/create_planning_question_spec.rb
spec/services/get_contentful_entry_spec.rb
spec/services/get_contentful_question_spec.rb
spec/support/contentful_helpers.rb

- replace the first question in the planning journey with a real Contentful API request
- the Contentful client is configurable through environment variables in keeping with a 12 factor app
- the first question we ask for is also configurable through an environment variable as opposed to hardcoding it this allows us a little flexibility
- handle the exceptional case where we ask Contentful for an Entry and it wasn't found, fail quickly and loudly to the user and report to the team via Rollbar. The rollbar includes 2 pieces of technical information to help us debug Contenful: `entry_id` and `space_id`
It's worth noting the relevant risk error we've identified to the ability to delete Contentful entries https://trello.com/c/cSuRk7Kj. Given they _can_ be deleted by users we should (and now …

Replace contentful fixture with real API request

---

app/services/create_planning_question.rb
app/services/get_contentful_entry.rb
spec/services/create_planning_question_spec.rb
spec/services/get_contentful_entry_spec.rb
spec/support/contentful_helpers.rb

This pull request has been extracted from the work being done to address https://trello.com/c/2r44iApA. In order to make this change I found some friction around reusing the `GetContentfulEntry` service. I think this refactoring offers improvement regardless of additional work.
Change the way we handle the Contentful API response so we pass down an object of the Contentful gem, rather than a blob of JSON (though we still do store the raw JSON).

Refactor the getting of Contentful Entries to return an object instead

---

spec/fixtures/contentful/no-next-question-example.json
spec/fixtures/contentful/radio-question-example.json

Tiny change to correct 2 fixtures that attempt to replicate a response for entries with no 'next' element.
You can verify this by making a Contentful API request manually for an entry that has no next element, no `next` key is returned.

Entry fixtures without next element are more realistic

---

CHANGELOG.md

- address rails-template TODO
- any user can see a start page for the planning journey
- use GOV.UK Frontend framework
- users can see a basic form to start the planning journey sourced by a
Contentful fixture
- planning form is styled as a GOV.UK form
- validate that an answer is provided to a question
- the first planning question comes directly from Contentful
- handle the exceptional case when a Contentful entry is missing
- multiple radio questions can be answered in sequence
- users can be asked to answer a short text question
- Contentful can redirect users to preview endpoints

release-001

---

app/controllers/plans_controller.rb
app/models/answer.rb
app/models/question.rb
app/services/answer_factory.rb
app/views/plans/show.html.erb
config/environments/test.rb
db/migrate/20201112123028_remove_answer_table.rb
db/schema.rb
spec/factories/answer.rb
spec/factories/question.rb
spec/models/answer_spec.rb
spec/models/question_spec.rb
spec/services/answer_factory_spec.rb

This deployment of https://github.com/DFE-Digital/buy-for-your-school/pull/33 is currently failing on line https://github.com/DFE-Digital/buy-for-your-school/blob/develop/db/migrate/20201111144757_create_radio_answer_table.rb#L12 and requires a fix.
I believe [the new #answer method](https://github.com/DFE-Digital/buy-for-your-school/blob/develop/app/models/question.rb#L13) was conflicting with the migrations that were intending to ask for `answer` through an ActiveRecord association, however our method of the same name was unintentionally found and used instead.
The presence of that method hid the fact that `Answer` had been removed from the code base at the time of the migration and that `question.answer` was no longer viable to handle the radio and short text migrations in all cases. …

Fix RadioAnswer and ShortTextAnswer database migrations

---

CHANGELOG.md
db/migrate/20201116142721_add_foreign_key_constraint.rb
db/schema.rb

This proposal attempts to ensure we have better data integrity between our associations. 
I found when debugging locally and on staging that the database was starting to get into unexpected states. For example we could have an `answer` without a `question`, or the potential for a `question` to not have a `plan`. Adding cascade constraints will help us delete records in a reliable manner. Deleting a plan will delete all associated questions, and all questions will delete associated answers. The result of deleting a plan will now leave no orphan records that have no way of ever being referenced.
We may wish to use `:restrict` in future if we want to guard against accidental deletions.
[As pointed out in the Rails documentation we can do this in the model or at the database level for a …

Add foreign key contraints to the database

---

.github/workflows/continuous-integration.yml
Dockerfile
README.md
config/puma.rb
docker-compose.ci.yml
docker-compose.test.yml
docker-compose.yml
docker-entrypoint.sh
script/server
script/test

- Puma workers reduced from 2 to single process. If we want to scale the app with more resources we can go horizontally with more containers, rather than horizontally.
- Docker Compose can be used to run local dev servers using Docker, included `script/server`
- Docker Compose can be used to run local test servers using Docker, included in the readme. Both Docker and Non-Docker options are referenced in the Readme as there are trade-offs to using each
- Refactor the Dockerfile into build layers to help debug a problem with the assets being unavailable only on CI

(53) Docker Compose used on CI and usable in dev

---

app.json
heroku.yml

Based ontop of https://github.com/DFE-Digital/buy-for-your-school/pull/40 which should be merged first.
I've spun up a [new Heroku app](https://dashboard.heroku.com/apps/dfe-bfys-docker-test) to test this, it can be looked at here https://dfe-bfys-docker-test.herokuapp.com/. The preview app works but should be deploying using the old buildpack strategy. 
Heroku will intercept the current git push and continue taking control of the deployment as it does now. This means GitHub Actions and Heroku will do duplicate Docker builds on the same Git SHA. There was potential for more work here to get GitHub Actions to build and push to a container registry and then instruct Heroku to pull and deploy the same artifact, reducing build times and deploying the exact artifact that was tested would be …

(53) Deploy to heroku with containers

---

app/services/contentful_connector.rb
app/services/get_contentful_entry.rb
spec/services/contentful_connector_spec.rb
spec/services/get_contentful_entry_spec.rb
spec/support/contentful_helpers.rb

Contentful interactions are now handled by the `ContentfulConnector` class, to better separate concerns and reduce duplication when different kinds of Contentful API calls are made in future.

Refactor Contentful interactions into dedicated interface class

---

app/services/get_contentful_entry.rb
spec/requests/contentful_caching_spec.rb

Addresses https://rollbar.com/dxw/dfe-buy-for-your-school/items/31/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification
A string was being passed into the Redis cache that could not be parsed back out by `JSON.parse`. I should have run it locally one last time before creating the PR.
Instead of blindly storing the `entry.raw` JSON blob, we now serialise and deserialise it with `JSON.dump` and `JSON.restore`. 
Here's an illustration for how the data should change along the way before and after:
Before: 
```
Set -> 
"{\"sys\"=>{\"space\"…
Get -> 
JSON.parse('{"sys"=>{"space"…) -> 💥 JSON::ParseError
```
After: 
```
Set -> 
"{"sys"=> {"space"=>".to_json -> "{\"sys\":{\"space\"
JSON.dump("{\"sys\":{\"space\":) -> "\"{\\\"sys\\\":{\\\"space\\\": # This is what goes …
```

(112) Fix reading from the Redis cache

---

CHANGELOG.md
app/services/cache.rb
app/services/concerns/cacheable_entry.rb
app/services/get_contentful_entry.rb
spec/services/cache_spec.rb

- generic Redis caching methods extracted into reusable caching object which introduces the opportunity for more unit test coverage, which I take
- specific Contentful Entry caching logic extracted into a reusable mixin. A new class didn't feel appropriate given the specificity of the contents
These changes should make it easier to add cache behaviour in the automated nightly task that is going to warm up the cache. Instead of getting an individual Entry and caching, it will get all Entries and cache every result.

(171) Refactor contentful caching for reuse

---

app/controllers/steps_controller.rb
app/services/create_journey_step.rb
config/routes.rb
spec/requests/contentful_caching_spec.rb
spec/services/create_journey_step_spec.rb

- [fix DoubleRenderError](https://rollbar.com/dxw/dfe-buy-for-your-school/items/34/)
- fix bug which allowed a user to easily refresh a question page to get to the next question. You can test this by going to https://dfe-buy-for-your-school-beta-s.herokuapp.com/plans/b313b903-319f-45fb-9bb5-f0cc1a2608ca/questions/new and refreshing your browser. After this change it is still technically possible for this to happen *if* a user manually edits/hacks the URL back to `question/new`. The chances of this are small, the impact is the plan#show blows up. We may wish to add additonal guard logic to question#new to protect against this if it becomes a problem. I'm concious not all steps will require answers so it might be better to wait.

Fix form flow failures

---

README.md

The docker-compose service in docker-compose.test.yml is called `test` rather than `web` so this command didn't work.

Docker test instruction fixed

---

app/services/contentful_connector.rb
app/services/get_all_contentful_entries.rb
spec/services/contentful_connector_spec.rb
spec/services/get_all_contentful_entries_spec.rb
spec/services/get_contentful_entry_spec.rb

Adds a new `GetAllContentfulEntries` class which retrieves all entries from a Contentful instance.
This class will be used by subsequent work on mapping and cache-warming.

Add class to retrieve all entries from Contentful

---

CHANGELOG.md
app/models/step.rb
app/services/create_journey_step.rb
app/views/journeys/show.html.erb
app/views/steps/new.paragraphs.html.erb
config/locales/en.yml
db/migrate/20201202105320_add_body_to_steps.rb
db/migrate/20201202150359_add_contentful_model_to_step.rb
db/schema.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/static-content-example.json
spec/models/step_spec.rb
spec/services/create_journey_step_spec.rb
spec/support/contentful_helpers.rb

This work is based on top of the fixes here https://github.com/DFE-Digital/buy-for-your-school/pull/61 without them the test suite fails.
- accept a new Contentful model of `StaticContent` that has the type `paragraphs`
- content steps don't require an answer, the journey show page doesn't add a line summary for steps that don't have answers
- we store the `ContentfulModel` on the step so we can start to ask questions of Steps to help with presentation. Instead of showing steps if they have or don't have associated answers, we can make the assumption that if the step is of type "staticContent" then they'll never have an answer, but questions always should!

(179) Show static content from Contentful as a journey step

---

CHANGELOG.md

- add database foreign key constraints for better data integrity
- Contentful entry requests use a new Redis read cache
- service name included in the header
- refactor name of "Plan" to "Journey"
- refactor name of "Question" to "Step"
- refactor redis caching into reusable class
- users can be shown a step in the journey that is only static content

release-003

---

CHANGELOG.md
config/application.rb
db/migrate/20201203103421_change_long_text_answer_to_uuid.rb
db/schema.rb

Noticed this problem when pairing yesterday
- migrate `LongTextAnswer` from using sequential ID to UUID
- add a little config to decrease the chances of future us forgetting/missing this again 
Having a non reversible migration usually feels icky. Given we have no real production data or users that could see past answers, an alternative could be to blow away the table and add it back in over 2 migrations?

LongTextAnswer table also has UUID as the type of primary key

---

.env.example
.env.test
CHANGELOG.md
Gemfile
Gemfile.lock
app/jobs/warm_entry_cache_job.rb
app/services/cache.rb
app/services/concerns/cacheable_entry.rb
app/services/get_contentful_entry.rb
config/application.rb
config/initializers/sidekiq.rb
config/schedule.yml
config/sidekiq.yml
doc/architecture/decisions/0008-use-sidekiq-for-asynchronous-tasks.md
docker-compose.yml
heroku.yml
spec/fixtures/contentful/multiple-entries-example.json
spec/jobs/warm_entry_cache_job_spec.rb
spec/requests/contentful_caching_spec.rb
spec/services/cache_spec.rb

- install Sidekiq to enable asynchronous tasks
- install Sidekiq Cron to enable schedule asynchronous tasks. When Sidekiq is initialised the contents of the schedule.yml is automatically seeded into Redis
- refactor the way we send cache key information to the Cache class to make it reusable for this work
- get all Contentful entries and update their cached values **every night at 3am**
Remember if you'd like to test this locally to turn caching on with the `CONTENTFUL_ENTRY_CACHING` environment variable.

(171) Automatically warm Contentful cache every night

---

CHANGELOG.md
app/models/step.rb
app/services/create_journey_step.rb
app/views/steps/new.long_text.html.erb
app/views/steps/new.paragraphs.html.erb
app/views/steps/new.radios.html.erb
app/views/steps/new.short_text.html.erb
config/locales/en.yml
db/migrate/20201207171647_add_primary_call_to_action_text_to_step.rb
db/schema.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/no-primary-button-example.json
spec/fixtures/contentful/primary-button-example.json
spec/services/create_journey_step_spec.rb
spec/support/contentful_helpers.rb

- primary form button text is configurable through a new optional Contentful model field called `primaryCallToAction`.

(187) Form button text is configurable through Contentful

---

CHANGELOG.md
app/controllers/journeys_controller.rb
app/models/single_date_answer.rb
app/models/step.rb
app/services/answer_factory.rb
app/services/create_journey_step.rb
app/views/journeys/_single_date_answer.html.erb
app/views/steps/new.single_date.html.erb
config/environments/test.rb
config/locales/en.yml
db/migrate/20201208110342_create_single_date_answer.rb
db/schema.rb
spec/factories/answer.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/single-date-example.json
spec/models/long_text_answer_spec.rb
spec/models/single_date_answer_spec.rb
spec/models/step_spec.rb

- add missing test coverage for LongTextAnswer that was noticed during this
- Single date questions can be asked
The language "Single" was picked because I expect we'll have to add support for another type of question where we need to ask for 2 dates to form a "Range".

(221) Users can be asked a single date question

---

CHANGELOG.md
Gemfile
Gemfile.lock
spec/spec_helper.rb

Using Webmock will give the team more explicit feedback on any failures due to a real request being made.
Instead of seeing a real Contentful 404 we should see a Webmock error that explains that a real HTTP request was detected and that we should look to stub it.

Test suite detects external HTTP requests

---

CHANGELOG.md
app/controllers/journey_maps_controller.rb
app/services/build_journey_order.rb
app/views/journey_maps/new.html.erb
config/locales/en.yml
config/routes.rb
spec/features/visitors/anyone_can_see_the_map_of_journey_steps_page_spec.rb
spec/fixtures/contentful/closed-path-with-multiple-example.json
spec/fixtures/contentful/multiple-entries-example.json
spec/jobs/warm_entry_cache_job_spec.rb
spec/services/build_journey_order_spec.rb
spec/services/create_journey_step_spec.rb
spec/support/contentful_helpers.rb

- a new hidden page at `/journey_map/new` for viewing the live map of all entries used in journey
- this map only supports a single linear journey, it starts from `ENV["CONTENTFUL_PLANNING_START_ENTRY_ID']` and continues until no `next` element can be found
- it doesn't read from the cache as we specified it should be live and reloadable
- it doesn't write back to the cache yet as that would introduce a cache busting mechanic, I think we should do the work to validate the paths look healthy before adding them to the cache
When designing the `EntryPathFinder` service and thinking about how this work could be extended to support multiple branches. We could replace the whole thing with a graphing tool or change this service so that it starts to build a proper tree data structure instead of a …

(115) Journey map endpoint which shows the sequence of Contentful entries shown to a user

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/helpers/step_helper.rb
app/models/checkbox_answers.rb
app/models/step.rb
app/services/answer_factory.rb
app/services/create_journey_step.rb
app/views/journeys/_checkboxes_answer.html.erb
app/views/steps/checkboxes.html.erb
app/views/steps/radios.html.erb
db/migrate/20201209122555_create_checkbox_answers.rb
db/schema.rb
spec/factories/answer.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/checkbox-example.json
spec/helpers/step_helper_spec.rb
spec/models/checkbox_answers_spec.rb
spec/models/step_spec.rb

A Contentful Entry to test this locally is: `1DqhwF2XkJJ0Um6NSweWlZ`.
- refactor existing `radio_options` method to a helper before we add the new `checkbox_options` method
- a new `CheckboxAnswers` resource allows us to capture one or more answers for a checkbox question - it's the first plural Answers resource
- an extra step to ensure presence validation fires correctly when no checks are made
To make sure the approach of storing an Array of Strings as the `response` as well as the approach of stripping blank options (`""`) options submitting by the form. I added a quick Edit journey in to make sure the form could render back the selected options. You're able to see that output in the screenshots attached.
We store an Array of Strings, rather than a different type like an `hstore` as …

(222) Users can be asked a question with multiple checkboxes

---

CHANGELOG.md
app/controllers/journey_maps_controller.rb
app/services/build_journey_order.rb
app/views/errors/repeat_step_in_the_contentful_journey.html.erb
app/views/errors/too_many_steps_in_the_contentful_journey.html.erb
config/locales/en.yml
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/features/visitors/anyone_can_see_the_map_of_journey_steps_page_spec.rb
spec/fixtures/contentful/repeat-entry-example.json
spec/services/build_journey_order_spec.rb

Based on https://github.com/DFE-Digital/buy-for-your-school/pull/76
Do we need more rules? Can we think of any other reasons to invalidate a journey for now?
My plan is that this is the first of a 2 parter. If this validation is OK then I'll look to apply it when warming the cache. If an error occurs we can extend the TTL of the existing entries to ensure a happy journey always persists.
- when the journey shows the user the same step twice we infer an infinite loop and show an error on `journey_map/new`
- when the journey steps a user see exceeds 50 we infer there's no end and show an error on `journey_map/new`
- generating a real fixture for 50+ entries slows down the test suite considerably (+2mins) so we opt for stubbing the limit to a lower value. I have a hunch it's to do with the …

(121) Part 1 - Only generate a journey map if the journey path is valid

---

CHANGELOG.md
app/models/step.rb
app/services/create_journey_step.rb
db/migrate/20201216150806_add_contentful_id_to_step.rb
db/migrate/20201216160028_change_step_raw_field_to_json_b.rb
db/schema.rb
spec/factories/step.rb
spec/models/step_spec.rb
spec/services/create_journey_step_spec.rb
spec/support/contentful_helpers.rb

This change is a prior refactor ahead of the linking of Journeys to the [creation of their Specification](https://trello.com/c/5plFnXEs). We know that each Step will need to be linked to another Contentful Entry as part of this work.
I imagine that for a Journey we would:
1. Get the Specification Entry
2. Loop through each of the linked Specification Block Entries
3. For each Block Entry, find an associated Step
4. Add it to a new document based on the answer
Step 3 is what this pull request seeks to make easier. Instead of having to go into the `raw` attribute of each step we can do something like: `journey.steps.find(contentful_id: block_entry_id)`
- a new `contentful_id` column exists on Steps
- we were storing the Contentful ID in the raw attribute. We can use this to migrate all …

(225) Refactor Steps so they now include an Contentful entry ID as a unique field

---

db/migrate/20201216150806_add_contentful_id_to_step.rb

[Currently staging migrations are failing](https://rollbar.com/dxw/dfe-buy-for-your-school/items/43/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification). 
The migration worked locally until I removed the temporary method that parsed the string into a hash in a later commit 🤦  https://github.com/DFE-Digital/buy-for-your-school/pull/84/commits/c3c5096bb14cf0c58bd5bc8323be5a69c8fa45a7#diff-d0a4710bfb2223d4b6f70da35e5d63f599611786b7b688571d372362c2f57df4L27
This change moves that code into the migration so it can run regardless of the state of the step methods.
I've tested this on the staging console on real data to check it definitely works:

Fix Contentful ID migration so it can run

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/controllers/steps_controller.rb
app/views/journeys/_long_text_answer.html.erb
app/views/journeys/_radios_answer.html.erb
app/views/journeys/_short_text_answer.html.erb
app/views/steps/_edit_form_wrapper.html.erb
config/locales/en.yml
config/routes.rb
spec/factories/answer.rb
spec/features/visitors/anyone_can_edit_their_answers_spec.rb

-  The `Check Your Answers` page displays a `Change` link for each step and relating answer
- The `Edit` and `Update` actions are implemented to allow users to edit their answers once given

(118) Users can edit their answers

---

db/migrate/20201216160028_change_step_raw_field_to_json_b.rb

Applying this straight away fails because of course the new field has no value at all. This shouldn't have got through local testing but alas it did and now we have to fix it.
Create the new temp field without validation, and add it at the end. By adding it at the end, after populating the columns, we should the be told if we still have missing values. That failure is the one we want.

Fix migration so presence validation is applied at the end

---

CHANGELOG.md
app/jobs/warm_entry_cache_job.rb
app/services/cache.rb
spec/fixtures/contentful/multiple-entries-example.json
spec/jobs/warm_entry_cache_job_spec.rb
spec/services/cache_spec.rb

Based on https://github.com/DFE-Digital/buy-for-your-school/pull/80
We use the validation added in https://github.com/DFE-Digital/buy-for-your-school/pull/80 in the nightly cache warming task.
If we find an error in the journey we no longer add it to the cache, instead we will extend all previous entries on the assumption that they were valid.

(121) Part 2 - Only warm the cache with entries that form valid journeys

---

app/views/journeys/_checkboxes_answer.html.erb
app/views/journeys/_single_date_answer.html.erb

Whilst adding the ability to change your answer we also added new types. These new types also need the change buttons.

Add missing change links to the new types of step (checkbox and date)

---

CHANGELOG.md

- fix primary key type on long_text_answers table to UUID
- nightly task to warm the Contentful cache for all entries
- form button content is configurable through Contentful
- users can be asked to provide a single date answer
- add Webmock to prevent real http requests in the test suite
- content users can see a journey map of all the Contentful steps
- users can be asked to provide multiple answers via a checkbox question
- journey map shows an error to the content team if a duplicate entry is detected
- journey map shows an error to the content team if the journey doesn't end within 50 steps
- refactor how we store and access a Step's associated Contentful Entry ID
- users can edit their answers
- only add Contentful entries that form part of a valid journey to the cache

release-004

---

spec/requests/contentful_caching_spec.rb
spec/support/contentful_helpers.rb

We expect the raw method to return a `hash`. This expectation ensures we can reliably interogate it with methods such as `fetch`.
In starting another piece of work I found that a couple of tests [1] that don't use `fake_contentful_entry` but instead only rely on `stub_get_contentful_entry` to stub out a fake Contentful response to use as the `raw` value. I found that the behaviour differs between methods. In `stub_get_contentful_entry` we set `raw` to the string contents of the file, but in `fake_contentful_entry` we have an extra step to parse the string into JSON. We find that where only `stub_get_contentful_entry` is used, `raw` is in fact a string.
This change removes the redundant code in `stub_get_contentful_entry`. We can see that only 1 test actually fails. We change that failure …

Fix test so that step.raw returns as a hash rather than string

---

docker-compose.yml

When we start the webserver it creates a pid file in tmp/.
When running the server locally with docker compose and you turn off your machine without gracefully terminating the server process the file remains.
When you start the server again you get an error asking you to remove the existing pid file.
This change automates this step so we don't have to do this manual step each time.
It doesn't affect production environments.

Docker Compose server start auto purges any leftover pid file

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/presenters/checkboxes_answer_presenter.rb
app/presenters/long_text_answer_presenter.rb
app/presenters/radio_answer_presenter.rb
app/presenters/short_text_answer_presenter.rb
app/presenters/single_date_answer_presenter.rb
app/views/journeys/_checkboxes_answer.html.erb
app/views/journeys/_long_text_answer.html.erb
app/views/journeys/_radios_answer.html.erb
app/views/journeys/_short_text_answer.html.erb
app/views/journeys/_single_date_answer.html.erb
app/views/steps/radios.html.erb
db/migrate/20210118123111_add_further_information_to_radio_answer.rb
db/schema.rb
spec/factories/answer.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/closed-path-with-multiple-example.json
spec/fixtures/contentful/extended-radio-question-example.json
spec/presenters/checkboxes_answer_presenter_spec.rb
spec/presenters/long_text_answer_presenter_spec.rb
spec/presenters/radio_answer_presenter_spec.rb
spec/presenters/short_text_answer_presenter_spec.rb
spec/presenters/single_date_answer_presenter_spec.rb

To review locally you can use Entry ID `QvmpHjUCDyx0EofNDn9hX` in your .env as the starting entry.
Use this [1] pattern from the DFE Form builder gem. We take the behaviour that is applied to the 'Other' option in the example and make it applicable to any radio option, or none.
This change also includes a refactoring of teh way we present answers to different answer types. Moving the logic from the view into tested presenters. These commits are on the end and can be easily removed if controversial in any way. The goal is to chip away at a secondary problem in passing.
- Contentful always supplies JSON for a list of options. It is now possible to provide more than a simple list of values in thei JSON blob. If the Content user provides keys `display_further_information` and …

(185) Users can be asked Radio questions that prompt for additional text

---

app/views/steps/checkboxes.html.erb
app/views/steps/long_text.html.erb
app/views/steps/radios.html.erb
app/views/steps/short_text.html.erb
app/views/steps/single_date.html.erb

- make radio questions "XL" again inline with all other question types
- reduce all question label size down one notch to "L" given the length of real questions we are starting to see
Radio questions had very form small labels/page title:
Radio questions now have slightly bigger labels:
Real questions looked _really_ big:
We make them slightly smaller:

Fix radio question label size inconsistency

---

lib/specification_templates/catering.production.liquid

The remaining questions now exist in Contentful for all the steps that are currently identified. https://miro.com/app/board/o9J_lb34sdM=/?moveToWidget=3074457352505279555&cot=14.
NB. The extended radio questions are set up with the old and new options configuration. They will not present their further information back into the spec until it is collected by the new question pattern.
The ordering logic for presenting the spec is coming from this word document https://docs.google.com/document/d/1LAxX2ysWk3cBn3LOjkdjeKhx4S28p4pOSlk0EG2FLkU/edit#heading=h.pfdijzqb68v9
I've added some comments to help us connect word doc, contentful and this template whilst we have to keep hardcoding the changes in.

Update the specification template for remaining Food and Menu questions

---

CHANGELOG.md
config/locales/en.yml

- I noticed a message/[decision made about the service name in Slack](https://ukgovernmentdfe.slack.com/archives/C0148EM740M/p1610470150119900) and I had 5 minutes to fill. If it's a controversial one I'm very happy to close this for now.
- It seems unecessary to push this change further than what the user sees. For example in application.rb and on the github repo we still use "Buy for your School". As our service name could change multiple times as a result of research, it did not seem worth the effort of changing?

Update service with newest service name

---

app/controllers/journeys_controller.rb
lib/specification_templates/catering.production.liquid
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb

This fixes an immediate issue we can see where radio answers show "Yes" without the `futher_information`. It should be "Yes - Further information" and the logic already exists within presenters.
We need to get a fix for this quickly to unblock the production deploy. I've left a note to prompt us to refactor this controller code the next time we pass it.
The last answer is now a composite value.

Responses used in Specifications are formatted by presenters

---

CHANGELOG.md

- users can see an initial slice of their specification as HTML at the end of their journey
- users can download their specification as a document in the .docx format
- checkbox answers are editable
- radio and select questions are created with the new `ExtendedOptions` field
- questions are now all loaded at the start of a journey, rather than step by step
- users start the journey at the task list instead of the first question
- check your answers pattern has been replaced by a task list
- radio questions can be configured to ask the user for additional text
- update the service name to the latest decision
Production Journeys all need to be destroyed for the migrations to succeed. Do so just before we deploy with `Journey.destroy_all`

release-005

---

app/controllers/preview/entries_controller.rb
spec/features/visitors/anyone_can_preview_a_journey_step_spec.rb
spec/requests/entry_preview_spec.rb

`liquid_template` is a required part of a `Journey` which was not being provided whilst previewing a question, leading to the `Journey` not being persisted and a redirect to the step within the journey being impossible.
This commit adds a very short stub template to preview journeys.
It also adds a feature spec to ensure that a user attempting to preview a step does reach the intended view.

Previewing a question now specifies a liquid_template

---

spec/factories/step.rb

The step factory was also creating associated answers every time a step was created. This does not mirror the behaviour of the system; answers are only created at the point a user provides one, not when a step is created.

Step factories no longer create associated answers

---

CHANGELOG.md
app/views/journeys/_resume_journey_notice.html.erb
app/views/journeys/show.html.erb
config/locales/en.yml
public/robots.txt
spec/features/visitors/anyone_can_resume_a_journey_spec.rb

- Users are now told how they can resume a journey (either by bookmarking a page to return to, or revisiting the same address) and an address is provided for this on the journey task list. This functionality has always been available, just never promoted.
- `robots.txt` now excludes all journey and step pages. Although these are (currently) accessible by anyone, they should not be easily discoverable.

Tell a user how they can recover their current journey

---

CHANGELOG.md
app/views/journey_maps/new.html.erb
config/locales/en.yml
spec/features/visitors/anyone_can_see_the_map_of_journey_steps_page_spec.rb

A collection of improvements to make the journey map easier to understand, and more useful for the content team.
- The journey map is now clearer about what happens when you click a link
- The journey map now includes links to preview a step
- The journey map now displays markup to include a step's answer in the specification template

Improvements to journey map to assist content team

---

CHANGELOG.md
app/helpers/step_helper.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/steps/checkboxes-question.json
spec/helpers/step_helper_spec.rb
spec/presenters/checkboxes_answer_presenter_spec.rb

The desired behaviour is that fields as displayed to the user in checkbox questions are provided exactly as in Contentful. This commit changes the behavior of `checkbox_options` in `StepHelper` to no longer capitalise options.
NB: This does _not_ modify how checkbox options are rendered in specification output, as further work is planned to provide a wider range of options in output (such as an actual array of checked options) which will supersede this.

Options are no longer capitalised in checkbox questions

---

CHANGELOG.md
app/controllers/journeys_controller.rb
app/helpers/journey_helper.rb
app/services/create_journey.rb
app/views/journeys/show.html.erb
spec/factories/step.rb
spec/features/visitors/anyone_can_edit_their_answers_spec.rb
spec/features/visitors/anyone_can_view_a_list_of_tasks_spec.rb
spec/fixtures/contentful/categories/multiple-sections-and-steps.json
spec/fixtures/contentful/sections/multiple-long-text-section.json
spec/fixtures/contentful/sections/multiple-radio-section.json
spec/helpers/journey_helper_spec.rb
spec/services/create_journey_spec.rb

Sections and steps are now ordered correctly, fixing a bug that appeared when a specific combination of named sections were presented incorrectly.
We change the type of data structure we store for the `journey.section_group` and are explicit about the `order` we expect each section and each step (starting from 0).
- minor improvement to the Step factory to make the `contentful_id` dynamic with each new fake step
This is what Contentful specifies the order to be:
This is the order where we can see the bug:
And after the bug is fixed:

(372) Fix ordering of sections and steps

---

app/views/journeys/show.html.erb

This better matches the pattern as given by the GOV.UK Design Framework.
- Move the "resume journey" notification banner from the bottom of the task list to the top.

(374) Move "resume journey" notification directly below title

---

CHANGELOG.md
app/controllers/journeys_controller.rb
app/models/currency_answer.rb
app/models/step.rb
app/presenters/currency_answer_presenter.rb
app/services/answer_factory.rb
app/services/create_journey_step.rb
app/services/find_all_journey_answers.rb
app/views/steps/currency.html.erb
config/environments/test.rb
db/migrate/20210202120716_create_currency_answer.rb
db/schema.rb
spec/factories/answer.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/currency-question.json
spec/fixtures/contentful/sections/currency-section.json
spec/fixtures/contentful/steps/currency-question.json
spec/models/currency_answer_spec.rb
spec/presenters/currency_answer_presenter_spec.rb
spec/services/answer_factory_spec.rb

- Users can answer questions which expect a currency
- Currency is saved as a decimal with precision 11 to ensure that all currency amounts required for this service are valid
Currency step view has a prefix text of a `£` value to indicate that it requires a currency input
An error is thrown when non numerical values are entered
Currency values are saved as decimals in the database
The specification displays the currency with the full currency formatting to include the `£` and all appropriate commas

Users can answer questions which expect a currency 

---

CHANGELOG.md
app/models/journey.rb
app/views/journeys/show.html.erb
config/locales/en.yml
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb
spec/models/journey_spec.rb

Use warning text pattern from the design system https://design-system.service.gov.uk/components/warning-text/
When there are any (visible) incomplete tasks we show a warning
When all visibl steps are complete, we hide the warning.

(352) Users see a spec warning when there are incomplete steps

---

app/controllers/answers_controller.rb
app/helpers/date_helper.rb
app/models/single_date_answer.rb
app/services/save_answer.rb
config/application.rb
config/locales/models/single_date_answer.en.yml
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/helpers/date_helper_spec.rb
spec/models/single_date_answer_spec.rb
spec/services/save_answer_spec.rb

Incorrect values for dates will return an error to the user, rather than causing [a crash](https://rollbar.com/dxw/dfe-buy-for-your-school/items/72/?item_page=0&item_count=100&#traceback). 
When the user adds `0, 0, 2` into the 3 fields Ruby would fail to parse this as a Date when assigning to the answer object. This happens before traditional model validation can take place, leaving us a bit stuck.
Using the [MOJ Form builder we can do this by adding a widget](https://github.com/ministryofjustice/gov_uk_date_fields#3-tell-your-models-attributes-are-gov_uk_dates) called `acts_as_gov_uk_date`. This does not appear to be present in the DfE Form builder which we are using, and that is very much part of our service (not something easily swapped out to).
Given that we have spent many days on …

(343) Fix date validation

---

app/services/toggle_additional_steps.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb

* Before this change the user could show a question and it would go and show all dependent questions regardless of them having answers, or indeed answers that were required.
* This change turns the `matching_answer?` method into a functional method so it can be reused within the recursion as well as outside it
* We continue to hide all dependent child questions regardless of their answer

Only reshow hidden questions that qualify

---

.env.example
.env.test
CHANGELOG.md
config/initializers/redis.rb
config/initializers/sidekiq.rb
docker-compose.ci.yml
docker-compose.test.yml
docker-compose.yml

The Heroku Redis addon controls the REDIS_URL environment variable. Sometimes this value changes[1] and the host and/or port changes leading to connection failures after a random interval, and without warning.
This commit changes our approach from making the database number configurable through ENV (using `REDIS_CACHE_URL` and `REDIS_SIDEKIQ_URL`) to being hardcoded into each service that uses Redis: Sidekiq and Redis for caching.
[1] https://data.heroku.com/datastores/49f12bfc-2341-465f-ae43-70f7c4edabcd#settings
> Please note that these credentials are not permanent.
Heroku rotates credentials periodically and updates applications where this datastore is attached.

Fix redis connection failures by depending only on REDIS_URL

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/helpers/step_helper.rb
app/models/step.rb
app/views/steps/checkboxes.html.erb
db/migrate/20210217145518_add_further_information_to_checkboxes.rb
db/schema.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/extended-checkboxes-question.json
spec/fixtures/contentful/sections/extended-checkboxes-section.json
spec/fixtures/contentful/steps/extended-checkboxes-question.json
spec/helpers/step_helper_spec.rb

Users can now be asked to provide further information for the choice they've made, if Contentful has specified that behaviour for the given answer
There should be no surprises here since we are following the precedent set by the extended-radio pattern. Fortunately the [DfE Form builder gem supports this "Other" mechanism](https://govuk-form-builder.netlify.app/form-elements/checkboxes/#generating-checkboxes-with-a-conditionally-revealed-text-field) in the same way. 
With multiple options we can save multiple bits of further info:

(342) Users can answer using the extended checkbox pattern

---

app/views/steps/checkboxes.html.erb
spec/fixtures/contentful/steps/extended-checkboxes-question.json

\We already had `display_further_information` for radio questions and this has been used with our real questions. The addition of extended checkbox questions made an error with how it's fixture was produced. Switch this back to the original key name.
I've gone through Contentful `master` and `develop` and corrected all checkbox questions that had the wrong key and updated the help text on the Content Model.

Fix inconsistent reference to Contentful attribute

---

CHANGELOG.md
app/services/toggle_additional_steps.rb
spec/fixtures/contentful/steps/hidden-field-that-shows-an-additional-question.json
spec/fixtures/contentful/steps/show-additional-question.json
spec/services/create_journey_step_spec.rb
spec/services/toggle_additional_steps_spec.rb

Before this change we allowed the content user to "bolt on" **one** additional question if the answer matched an expected pattern.
This change allows them to show as many additional questions as they like. Though the current need is for 2 additonal questions. We do this by accepting an array of identifiers rather than a single string.
The amount of calculation required to determine and follow the question branches through to their resolution is not ideal and we know this. A better approach would be to keep track of the state of the tree of questions and make the required database updates with fewer database queries. This would require more time than we have in the last sprint so we are opting for something that works and accepting the technical debt will need to be repaid.
For this …

(409) Multiple optional questions can be shown and hidden

---

app/views/steps/checkboxes.html.erb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/steps/extended-checkboxes-question.json

..When one is not provided
We instead don't show a label at all.

Checkbox info fields no longer try and create their own label

---

app/controllers/answers_controller.rb
app/controllers/journeys_controller.rb
app/controllers/steps_controller.rb
app/models/step.rb
app/presenters/step_presenter.rb
app/views/journeys/show.html.erb
app/views/steps/_edit_form_wrapper.html.erb
app/views/steps/_new_form_wrapper.html.erb
app/views/steps/checkboxes.html.erb
app/views/steps/currency.html.erb
app/views/steps/long_text.html.erb
app/views/steps/number.html.erb
app/views/steps/paragraphs.html.erb
app/views/steps/radios.html.erb
app/views/steps/short_text.html.erb
app/views/steps/single_date.html.erb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/nil-help-text-radios.json
spec/fixtures/contentful/categories/nil-help-text-short-text.json
spec/fixtures/contentful/sections/nil-help-text-radios-section.json
spec/fixtures/contentful/sections/nil-help-text-short-text-section.json
spec/fixtures/contentful/steps/nil-help-text-radios.json
spec/fixtures/contentful/steps/nil-help-text-short-text.json

Since we weren't correctly guarding against empty `help_text` for some question types, when the `help_text` was empty we would try call methods on it that did not exist.
To make this easier to understand and cleaner for people in future, this also spends some time making sure the individual step views make use of `StepPresenter` instead of the `Step` object directly and moves the `help_text_html` into this presentation layer.

Fix cases where empty help text would cause errors

---

CHANGELOG.md
app/services/create_journey_step.rb
app/services/toggle_additional_steps.rb
db/migrate/20210223102716_change_additional_step_rule_name.rb
db/schema.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/features/visitors/anyone_can_edit_their_answers_spec.rb
spec/fixtures/contentful/categories/show-one-additional-question.json
spec/fixtures/contentful/sections/show-one-additional-question-section.json
spec/fixtures/contentful/steps/hidden-field-that-shows-an-additional-question.json
spec/fixtures/contentful/steps/show-multiple-additional-questions.json
spec/fixtures/contentful/steps/show-one-additional-question.json
spec/services/create_journey_step_spec.rb
spec/services/toggle_additional_steps_spec.rb

Based on https://github.com/DFE-Digital/buy-for-your-school/pull/176
This is the final part of the work to allow the content team to specify proper branching questions. Instead of a palm tree (where we could only add or remove questions from the same trunk) we can now branch in different directions. Each branch can have an arbitrary length.
- The structure of the Contentful `Show additional question` field has changed. Instead of requiring only one rule object we now expect an array of rules. The names of these fields have been updated to better reflect the plurality of the contents:
```
[
{
"required_answer": "Breakfast",
"question_identifiers": [
"ZoOchclnfw6tPZ0xfYL0h",
"1DqhwF2XkJJ0Um6NSweWlZ"
]
},
{
"required_answer": "Dinner",
"question_identifiers": [
"wSeEY4HlESoDJSUsE2wJQ"
]
}
] …
```

(409) User answers can fork a journey into multiple paths

---

app/models/step.rb
spec/services/get_answers_for_steps_spec.rb

Refactor our implementation of `step.answer`.
Instead of trying each association in order we are selective about the query we expect to make. This changes the outcome of method, reducing the maximum of 7 database queries (if the step is currency) to always being at most 1 query. To do this we interogate the `contentful_type` field.
For example, this is the database output when asking a checkbox step for it's answer (and how I spotted this issue). You can see we make 4 redundant SELECT queries before checking for a checkbox answer: 
We now only make one query we always expect to retrieve something or raise a RecordNotFound:

Optimise expensive database queries

---

.github/workflows/continuous-integration.yml
app/controllers/journeys_controller.rb
app/views/journeys/show.html.erb
config/brakeman.ignore
script/test

- add this as a testing steip to script/test in keeping with the 'One script to rule them all' pattern
- disregard the output so brakeman doesn't open an interactive prompt, we could add the report to a file but the container is ephemeral
We have an existing security warning to address as part of this work now as we had a period of time where we weren't running these checks.
CI will now explode (with a level 1 error and a fake level 3) ![Screenshot 2021-02-24 at 11 44 23](https://user-images.githubusercontent.com/912473/108995919-a8da1000-7695-11eb-8f9b-1f7b203bea32.png)

Brakeman runs on CI again

---

CHANGELOG.md
app/views/steps/checkboxes.html.erb
app/views/steps/radios.html.erb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/extended-long-answer-checkboxes-question.json
spec/fixtures/contentful/categories/extended-long-answer-radio-question.json
spec/fixtures/contentful/sections/extended-long-answer-checkboxes-section.json
spec/fixtures/contentful/sections/extended-long-answer-radio-section.json
spec/fixtures/contentful/steps/extended-long-answer-checkboxes-question.json
spec/fixtures/contentful/steps/extended-long-answer-radio-question.json

Radio answers and checkbox answers now have the option to either display a `single` or `long` text box for their further information text box
This is the `single` option:
This is the `long` option:

Create an extended further information text box option

---

app/presenters/checkboxes_answer_presenter.rb
spec/presenters/checkboxes_answer_presenter_spec.rb
spec/services/get_answers_for_steps_spec.rb

Our test didn't have an accurate case for how we are storing answers. We store a machine readable `morning_break` in  the `response` field (so we can reliably set field labels etc). Our test set the database value as "Morning break" which is close but let through this bug where all values are formatted in the machine readable format, rather than a human readable one.
We now strip the underscores from the value if it as multiple words during presentation.

Checkbox answers are now human readable in a spec

---

config/locales/en.yml
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb

This warning message has been changed to help be more explicit in it's messaging.

Update warning message for an incomplete specification

---

CHANGELOG.md
app/views/steps/checkboxes.html.erb
app/views/steps/radios.html.erb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/radio-question-with-separator.json
spec/fixtures/contentful/sections/radio-with-separator-section.json
spec/fixtures/contentful/steps/radio-with-separator-question.json

This change allows Radio questions within Contentful to specify a new attribute within it's existing `option` field called `separated_by_or`.
If omitted or set to false, no separator will be shown.
```
[
{
"value": "Yes"
},
{
"value": "No",
"separated_by_or": true
}
]
```

(354) Radio questions can be configured to show an OR separator

---

app/views/steps/radios.html.erb

When the radio question does NOT have a further_information of any sorts then when the user selects an option, the radio elements will jump slightly on the page.
This is caused by a new HTML element being added by the gem when `f.govuk_radio_button` is passed an empty block. In order to avoid this jump, we default back to the old (slightly repetitive) version of the code that has an else condition that uses this method without passing any block. This fixes the issue.
>  block (Block) — Any supplied HTML will be wrapped in a conditional container and only revealed when the radio button is picked [1]
[1] https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder/Builder#govuk_radio_button-instance_method
The same pattern is still used on checkboxes so there …

Fix page jump for radio questions without further info

---

CHANGELOG.md
app/helpers/answer_helper.rb
app/presenters/radio_answer_presenter.rb
app/services/get_answers_for_steps.rb
app/views/steps/checkboxes.html.erb
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb
spec/fixtures/contentful/categories/extended-checkboxes-question.json
spec/fixtures/contentful/categories/extended-radio-question.json
spec/helpers/answer_helper_spec.rb
spec/presenters/radio_answer_presenter_spec.rb
spec/services/get_answers_for_steps_spec.rb

Based atop https://github.com/DFE-Digital/buy-for-your-school/pull/189
The liquid template has a new variable available to it for every Radio and Checkbox answer, called `extended_answer_x`. This is _aswell as_ the previous `answer_x`.
```
answer_x => "Yes"
extended_answer_x => [
{ 
"response" => "Yes",
"further_information" => "Some further information to tell you about" 
}
]
answer_x => "Yes, no"
extended_answer_x => [
{ 
"response" => "Yes",
"further_information" => "Some further information to tell you about" 
}
{ 
"response" => "No",
"further_information" => "" 
}
]
```
The hope is that by making both available the content team will have the flexiblity to list the checklist answers only OR start to mixin the further information fields too, where relevant.
There is a small piece of …

(373) Extended options for Radio and Checkbox answers are now available for use in the specification

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/models/checkbox_answers.rb
app/models/step.rb
app/services/create_journey_step.rb
app/views/steps/checkboxes.html.erb
db/migrate/20210301151653_add_skippable_to_step.rb
db/migrate/20210302110746_add_skipped_to_checkbox_answers.rb
db/schema.rb
spec/factories/answer.rb
spec/factories/step.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/categories/skippable-checkboxes-question.json
spec/fixtures/contentful/sections/skippable-checkboxes-section.json
spec/fixtures/contentful/steps/skippable-checkboxes-question.json
spec/models/checkbox_answers_spec.rb
spec/models/step_spec.rb
spec/services/create_journey_step_spec.rb
spec/support/contentful_helpers.rb

The user need here is for a user to "complete" a step where no provided options are relevant to them. We need to be able to distinguish a user who has not yet answered and one who has chosen none are relevant. This allows us to mark the spec builder journey as complete and stop prompting the user to complete a step by showing an "complete" label in the task list.
There is no pattern for this checkbox form in the Design system.
[We had found one in DfE Claim](https://trello.com/c/Tdrjhtde/419-none-of-the-above-radio-option-on-checkbox-lists) but it doesn't appear to work properly. Crucially you cannot deselect the radio option once selected. Label clicks for the radio input also toggle checks to the check box selections too. We decided that it was too much work to try and salvage the …

(419) Checkbox questions can be explicitly skipped/set as irrelevant

---

.github/pull_request_template.md

In an effort to help us keep our documentation in Confluence up to date for how content is managed, include a prompt in our Pull request template.
The majority of changes do not require documentation changes so the prompt can be commented in if applicable.

Pull request template includes Confluence prompt

---

CHANGELOG.md
app/views/pages/planning_start_page.html.erb
spec/features/visitors/anyone_can_see_a_planning_start_page_spec.rb

The link included the prototype link of /start which doesn't exist. In this change we add a test for the link which was missed, the correct link and ensure it has the correct class for styling.

Planning page links back to the start page correctly

---

app/views/steps/checkboxes.html.erb
app/views/steps/radios.html.erb
spec/factories/answer.rb
spec/features/visitors/anyone_can_edit_their_answers_spec.rb

When a user selects the human readable `Pots, plans or cooking utensils` as a checkbox or radio answer we persist `pots,_pans_or_cooking_utensils` in the database instead of `Pots, plans or cooking utensils`.
`f.govuk_check_box :response` is now set to `option["value"]`, which saves the human readble value, `Pots, plans or cooking utensils`.
This fixes a problem where branching required the content user to pass in a machine readable value, often requiring the content user to have to guess the formatting of this value.

Checkbox and radio answers store the human readable choice

---

CHANGELOG.md
app/presenters/checkboxes_answer_presenter.rb
app/presenters/currency_answer_presenter.rb
app/presenters/long_text_answer_presenter.rb
app/presenters/number_answer_presenter.rb
app/presenters/radio_answer_presenter.rb
app/presenters/short_text_answer_presenter.rb
app/presenters/single_date_answer_presenter.rb
app/services/get_answers_for_steps.rb
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb
spec/fixtures/contentful/categories/extended-checkboxes-question.json
spec/presenters/checkboxes_answer_presenter_spec.rb
spec/presenters/currency_answer_presenter_spec.rb
spec/presenters/long_text_answer_presenter_spec.rb
spec/presenters/number_answer_presenter_spec.rb
spec/presenters/radio_answer_presenter_spec.rb
spec/presenters/short_text_answer_presenter_spec.rb
spec/presenters/single_date_answer_presenter_spec.rb
spec/services/get_answers_for_steps_spec.rb

The variables and their data structure that we make available to the specification through the template has breaking changes.
We remove the concept of `extended_answer` by merging all of its responsibility into `answer` by changing it from a `string` to a `hash`.
We go from:
```
answer_123 => "The option the user picked"
extended_answer_123["response"] => "the_option_the_user_picked"
extended_answer_123["further_information"] => "extra information"
```
To:
```
answer_123 => {
response: ["Foo", "Bar"],
concatenated_response: "Foo, Bar",
skipped: false,
selected_answers: [
{
machine_value: :foo,
human_value: "Foo",
further_information: "More yes info"
},
{
machine_value: :bar,
human_value: "Bar",
further_information: nil
}
]
}
```
This addresses several issues:
1. the distinction between …

(452) Part 1 - Change how information about all answers is shared with the specification builder

---

CHANGELOG.md
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb
spec/fixtures/contentful/categories/skippable-checkboxes-question.json

Based on https://github.com/DFE-Digital/buy-for-your-school/pull/210
Checkbox answers that are skipped by the user, are now able to be explicitly identified in the specification.
Before this we could and were inferring this state by checking for an answer variable that exists (since only answered questions have `answer` records) with an empty response.

(452) Part 2 - Content team can identify skipped questions in the specification

---

app/views/steps/radios.html.erb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/steps/extended-radio-question.json

When `further_information_help_text` isn't provided, it now no longer auto-generates it's own label. 
Instead it doesn't show a label at all.

Radio further information fields no longer auto-generates it's own label

---

CHANGELOG.md
app/services/toggle_additional_steps.rb
spec/services/toggle_additional_steps_spec.rb

This change fixes a bug where one question with branching logic could not unlock the same question baed on more than one required answer.
For example, if question A should show question B if the answer was "Blue" **or** question B if the answer was "Red". The rules would be iterated through one at a time, the first rule would correctly unlock the first question, but the second rule would incorrectly hide it again (straight away). The behaviour we want is: if any rule matches we show it and it stays shown until updated again.
We can achieve this by simply switching the order in which we go through the show and hide rules. If we go through all the hides first we avoid the case where we can ever re hide a question that was shown in the same toggle action.

(425) Multiple answers can unlock the same branching question

---

app/controllers/answers_controller.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb

The previous version of this code `answer.assign_attributes({:response=>nil})` did not change the response column. Probably because at a database level a column with the type Array cannot be set to nil so the update request was silently ignored.
Setting this to an empty array `[]` has the same result, nothing changes.
The only way I found to remove the old choices is to set an empty string in the array.

(457) Fix skipping answers so that previous choices are removed

---

CHANGELOG.md
app/controllers/journeys_controller.rb
app/controllers/specifications_controller.rb
app/views/journeys/show.html.erb
app/views/pages/planning_start_page.html.erb
app/views/specifications/show.html.erb
config/brakeman.ignore
config/locales/en.yml
config/routes.rb
spec/features/visitors/anyone_can_download_their_catering_specification_spec.rb
spec/features/visitors/anyone_can_see_a_planning_start_page_spec.rb
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb

Move the specification, the warning and the download button away from the task list and onto its own page.
Include a back link so the user can return to the task list, using the pattern we added for the planning start page.

(434) Specification is shown on its own page

---

.gitignore

This was a recent learning from a dxw incident review to protect contributors from accidentally committing files that include sensitive information to GitHub.

Prevent sensitive files that may be comitted by accident

---

CHANGELOG.md
app/controllers/answers_controller.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/fixtures/contentful/steps/extended-checkboxes-question.json

We were accidentally blocking further information `params` as the key didn't match an expected pattern. This caused them not to be saved on the record and the choice appeared to be ignored because we don't raise when an unexpected param was found (maybe we should?).
Flesh out the feature test to cover this regression with the "Other, please specify" option that's used a lot on live.
This value is now being persisted and is visible when returning to the question:

(465) Further information is now saved for options with commas (or other special characters)

---

app/services/toggle_additional_steps.rb
spec/services/toggle_additional_steps_spec.rb

Before this change any branches that had child nodes with had a _single_ rule worked fine.
When any child node had _more than one_ rule then we got a `TypeError: can't cast Array` [1].
This was happening because `journey_steps.where(contentful_id: [["8"]])` returns an object called `Step::ActiveRecord_AssociationRelation` which is automatically presented as an array of objects.
The problem comes when a second ID is passed and `flatten` isn't used: `journey_steps.where(contentful_id: [["8"], ["9"]])`. This code only returns a `Step::ActiveRecord_AssociationRelation` object and doesn't present itself as an array of steps. This fails to query for steps but doesn't explode. We see the problem when we then call `.update` upon it.
[1] https://rollbar.com/dxw/dfe-buy-for-your-school/items/91/?ite …

(467) Fix Branching so that questions can still be hidden when any child node includes **multiple** rules

---

app/controllers/specifications_controller.rb
app/services/specification_renderer.rb
config/brakeman.ignore
spec/services/specification_renderer_spec.rb

Previously, all rendering work for the specification was done in the journey controller. This moves the job of combining the template and the answers into a rendered output into a new service object, which gives us a clearer separation of which bit of code is responsible for the rendering.
This was originally planned to be a first step in adding an 'incomplete spec' warning message to the .docx output, but that work has had its priorities changed and there's no point this (entirely functional) refactoring languishing around unmerged.

Move specification rendering into a service object

---

CHANGELOG.md
app/presenters/checkboxes_answer_presenter.rb
spec/presenters/checkboxes_answer_presenter_spec.rb

Looks like the application of the `parameterize` method with it's parameters were not applied everywhere and our test suite had holes in it for keys that had special characters! 
`other-please-specify_further_information` did not equal the expected pattern of `other_please_specify_further_information` so no value was added to the variables given to Liquid. 
We reuse the `AnswerHelper` and this time check that `parameterize` is no longer defined in the rest of the code base. The test case covers an exact case from live.

Further info for variables with special chars is available to the spec

---

CHANGELOG.md
app/controllers/specifications_controller.rb
app/services/specification_renderer.rb
config/locales/en.yml
spec/features/visitors/anyone_can_download_their_catering_specification_spec.rb
spec/services/specification_renderer_spec.rb

We change the filename and include a simple paragraph at the top of the document which cannot intentionally or accidentally  reordered by the `specification_template`.
[The language used is taken from this document that the content team prepared](https://docs.google.com/document/d/11BOARCY9u6p846oS_NGq0hm3RE2EOOcBzFUyjarejt0/edit).
I'm unhappy with the feature test and the subsequant lack of complete coverage we have. [I've explained the different options I went through on the commit](https://github.com/DFE-Digital/buy-for-your-school/pull/227/commits/d4bab9cef9c8df183afb7e7756f3a9467c023e78). If there's a way anyone can think to improve this without changing the testing stack to include a non headless config I'd love to hear it!
Note the filename doesn't include "incomplete":
No warning …

(398) Specification document includes incomplete warnings

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/presenters/radio_answer_presenter.rb
app/services/save_answer.rb
app/views/steps/radios.html.erb
db/migrate/20210316114040_change_further_information_to_json_for_radio_answers.rb
db/schema.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb
spec/features/visitors/anyone_can_see_their_catering_specification_spec.rb
spec/presenters/radio_answer_presenter_spec.rb
spec/services/get_answers_for_steps_spec.rb
spec/services/save_answer_spec.rb

If there are multiple options within a radio question where expanded information is switched on, only the value from the last option is saved. This is the case even if the input is hidden, which means that unless the user chooses the last option in the list it will appear as their input has not been saved.
We fix this for presenting questions to the user by treating extended radio options like checkboxes and storing a hash of `further_information`. This also means that if a user changes their radio selection at a later date, their original response to further information will also be stored should they change back in future.
For rendering the result in the specification, as we prepare variables for the liquid template we only use the `further_information` value for the key which matches …

(426) Fix bug where radio questions with multiple expanded options only saves response to last in sequence

---

LICENCE

DfE work in the open and MIT is the default license [1]
[1] https://github.com/DFE-Digital/technical-guidance/blob/master/source/documentation/standards/licencing-software-or-code.html.md.erb#L15

Add MIT Licence

---

CHANGELOG.md
app/views/layouts/_messages.html.erb
app/views/layouts/application.html.erb

- We add the existing (but unused) messages partial into the layout
- Flash messages can now be set by controllers that will appear as an undissmisable notification banner
- Use design system styling for the notificaiton component

Flash messages can be shown as notification banners

---

CHANGELOG.md
app/controllers/answers_controller.rb
spec/features/visitors/anyone_can_complete_a_journey_spec.rb

When a checkbox answer was skipped, any later updates to this answer were not saving. `further_information_params` was only setting the skipped value to true. It now reassigns the skipped value to false when any checkbox choices are later selected.

Fix checkbox answer to save choices after previously skipping

---

config/initializers/default_url_options.rb

`APPLICATION_URL` was recently added and as an initialiser causes the docker build process to fail.
There is no way to provide a real URL during the build stage since we don't know what environment the docker image will be used in. Instead we guard against this variable being unset and if it is, we do nothing, reverting back to Rails defaults.
When the container is started off this image, the initialisers should re run and have the environment variables available to set this as originally intended.

Docker build succeeds without needing environment variables

---

CHANGELOG.md
app/controllers/dashboard_controller.rb
app/controllers/sessions_controller.rb
app/views/dashboard/show.html.erb
app/views/journeys/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/school_buying_professionals/complete_a_journey_spec.rb
spec/features/school_buying_professionals/download_their_catering_specification_spec.rb
spec/features/school_buying_professionals/see_their_catering_specification_spec.rb
spec/features/school_buying_professionals/view_a_dashboard_spec.rb
spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
spec/features/visitors/anyone_can_sign_in_with_dfe_sign_in_spec.rb
spec/features/visitors/anyone_can_view_a_dashboard_spec.rb
spec/features/visitors/see_a_specification_start_page_spec.rb
spec/support/journey_helpers.rb
spec/support/sign_in_helpers.rb

After sign in, users are now sent to the Specification Dashboard (instead of starting a new spec), from where they can choose to create a new specification.
A subsequent PR will add the ability to view existing specifications.

Add a new dashboard page with ability to create new specifications

---

config/initializers/vcap_services.rb
lib/vcap_parser.rb
spec/lib/vcap_parser_spec.rb

[GPaaS provides a VCAP_SERVICES environment variable which contains JSON
with information about services bound to the application](https://docs.cloudfoundry.org/buildpacks/ruby/ruby-service-bindings.html).
From the JSON we need to extract the REDIS_URL and any other environment
variables we have put into a user provided service.
This is based on the work we had done for [RODA](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/commit/52e38600b70c22bcaffd7e17ebd51d14dccb5b4b) and [CCS RMI](
Crown-Commercial-Service/DataSubmissionServiceAPI#376) and others

REDIS_URL is now available to the app when running on GPaaS environments

---

config/environments/production.rb
config/initializers/vcap_services.rb
spec/lib/vcap_parser_spec.rb

* The previous implementation had the vcap_parser called in an initialiser. Rails calls these files in alphabetical order [1] which meant it was being run after the redis initialiser. Causing REDIS_URL to be missing
* The Vcap parser only needs to run in the live environment as that's the only place `ENV["VCAP_SERVICES"]` will ever exist.
* I could have numbered the files and ordered vcap before session store but this felt fragile. Someone could easily change the order without realising the consequences.
[1] https://guides.rubyonrails.org/configuring.html#using-initializer-files

Load REDIS_URL and other GPaaS variables before initialisation

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/controllers/application_controller.rb
app/controllers/journeys_controller.rb
app/controllers/preview/entries_controller.rb
app/controllers/specifications_controller.rb
app/controllers/steps_controller.rb
app/models/journey.rb
app/models/user.rb
app/services/create_journey.rb
app/views/dashboard/show.html.erb
app/views/journeys/index.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20210325145645_set_up_user_journey_association.rb
db/schema.rb
spec/factories/journey.rb
spec/features/school_buying_professionals/edit_their_answers_spec.rb
spec/features/school_buying_professionals/resume_a_journey_spec.rb
spec/features/school_buying_professionals/view_a_dashboard_spec.rb
spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
spec/features/school_buying_professionals/view_existing_journeys_spec.rb
spec/features/visitors/anyone_can_sign_in_with_dfe_sign_in_spec.rb
spec/models/journey_spec.rb
spec/requests/authorisation_spec.rb
spec/requests/entry_preview_spec.rb
spec/services/create_journey_spec.rb
spec/support/sign_in_helpers.rb

**This is based atop #238, which should be merged first.**
* There is a new view which lists all existing specifications
* The dashboard now has a new link to the view of existing specifications
* Every new journey now belongs to a a single User
* Users can only see the journeys (and associated steps and answers) that they belong to
* Improve `CreateJourney` service so it fails loudly if for some reason it can't create a journey we can use
Log in as User A:
View a single attached journey:
Log in as User B
View does not contain journey from User A
* It should be easier to identify which specification is which
* Distinguish between 'in progress' and 'completed' specifications

Existing specifications can be viewed from the dashboard

---

terraform/app/README.md
terraform/app/backend.tf

A new S3 bucket has been created in the `sct-terraform` space, which is where the terraform state is now stored.
This PR updates the terraform backend, and Readme

Update terraform state location

---

.github/workflows/deploy.yml

The generated docker image environment variable is needed in the deploy stage
This creates it as an output from the build stage, which can be used in later stages

Pass docker image environment variable to deploy stage

---

.github/workflows/deploy.yml

Staging deployments aren't working with GitHub Actions https://github.com/DFE-Digital/buy-for-your-school/runs/2235529241?check_suite_focus=true
This looks to be because the new docker image is not set: `- docker_image               = "***:latest" -> null`
Try using the syntax found in this documentation to access the docker image name of the image we built in the previous job: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
I see there's a warning about this variable which may also be to blame that GitHub Actions thinks it's a secret (which it isn't) 
This points to the case where it GitHub may think it contains a secret. Some or all of the variable we are setting is probably being included in …

Debug GitHub Action deployment failure

---

app/models/journey.rb
app/models/section.rb
db/migrate/20210401100528_create_sections.rb
db/schema.rb
spec/models/journey_spec.rb
spec/models/section_spec.rb

Currently, only Journeys & Steps are models in the application, and Sections
are stored as a json blob `section_groups` on Journeys.
We want to add a new model type to Contentful & the application between Section
and Step ("Tasks") and to do so it makes sense to add Sections as a concrete
model in the application, and later add Tasks as a model as well.
This PR is the first step in the process. Sections are added as a model,
attached to a Journey. Eventually we will add tasks as a `has_many` association
to Sections, and Steps as a `has_many` association to Tasks.

Add Sections as a model in the application

---

CHANGELOG.md
app/views/layouts/application.html.erb
spec/features/visitors/see_a_planning_start_page_spec.rb

As per Gov.uk guidelines, all pages on the application should have a "robots"
meta tag with the content "noindex,nofollow"

Add noindex,nofollow meta tag to all pages

---

CHANGELOG.md
app/controllers/api/contentful/entries_controller.rb
spec/requests/cache_invalidation_spec.rb

The webhook that Contentful fires to tell us of a change [has been failing since Faye came back and started making changes](https://rollbar.com/dxw/dfe-buy-for-your-school/items/109/?utm_campaign=item_velocity_message&utm_medium=slack&utm_source=rollbar-notification) to content.
I tried to debug this locally but couldn't replicate the exact issue, though I did find a CSRF problem which I also fixed.
On my journey to debug what was happening I couldn't find a way to debug Rails's basic auth mechanism. I stumbled across this [Thoughtbot article](https://thoughtbot.com/blog/token-authentication-with-rails) which allowed me to debug it but only whe using the Token mechanism. Turns out this token based auth mechanism is also what the initial implementation should probably have been using! I …

Fix contentful webhook authentication issue

---

app/controllers/preview/entries_controller.rb
spec/features/school_buying_professionals/preview_a_journey_step_spec.rb
spec/requests/entry_preview_spec.rb

The "preview" endpoints are for the Preview environment only. Hitting this
endpoint on the non-preview environment creates cruft entries in the database.
Resolve this by checking on the sole preview controller that we are on the 
Preview environment. If we are not, return `not_found`

Do not allow access to the Preview endpoints on non-preview environment

---

README.md
doc/console-access.md

When debugging a staging issue I needed to get a rails console on. This change documents what I did and refers back to [how we did this on BEIS](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/console-access.md) with some minor modifications.

Document console access to GPaaS

---

.env.example

DSI doesn't work in development unless we have DSI environment configured to work with localhost.
So that the app starts for new devs with the minimum amount of fuss, disable this so the OmniAuth developer mode is used for signing in.

In development DSI is disabled by default

---

app/assets/stylesheets/components/_specification.scss

If these lines are not provided the Contentful specification template field has to include all the HTML classes. There are a lot and are easily missed.
If `optional!` is not used the app errors out saying these classes are unavailable. This is a mystery to me. The extensions above don't have this issue so the load order of the frontend CSS is seemingly correct.

(412) Include govuk table styling

---

app/jobs/warm_entry_cache_job.rb

The [stacktrace from the error message](https://rollbar.com/dxw/dfe-buy-for-your-school/items/131/) for NotImplementedError wasn't helpful so this change is based on trial and error. 
I was able to confirm that Sidekiq was not connecting to Redis. On the Heroku research environment this was further confused by the fact the worker wasn't enabled at all. I stripped the various configuration parts out until finding that removing `sidekiq_options` fixed the issue. This is surprising because [Sidekiq include this in the documentation for setting up a job with ActiveJob](https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling).
I checked that the Sidekiq patch upgrade that was applied 5 days didn't introduce this issue.
There isn't a suggested way to configure retry limits …

(569) Fix Sidekiq connection failure due to NotImplementedError

---

.env.example
CHANGELOG.md
app/jobs/delete_stale_journeys_job.rb
app/models/journey.rb
app/services/create_journey.rb
app/services/delete_stale_journeys.rb
app/services/save_answer.rb
config/schedule.yml
db/migrate/20210330105313_add_started_state_to_journey.rb
db/migrate/20210330111201_add_stale_time_stamp_to_journey.rb
db/schema.rb
spec/factories/journey.rb
spec/jobs/delete_stale_journeys_job_spec.rb
spec/models/journey_spec.rb
spec/services/create_journey_spec.rb
spec/services/delete_stale_journeys_spec.rb
spec/services/save_answer_spec.rb

Everytime a user starts a specification journey within the service it creates 100-200 database rows. Each row represents a copy of Contentful content, most commonly a question. We make this copy to ensure that the journey remains future proof if the content in Contentful changes (versioning) and if the Contentful service becomes unavailable.
We are finding that we are creating approximately 10,000 a week on staging on our Heroky hobby database which is the limit. Whilst our live database will have millions of rows the problem remains that many thousands of rows will become occupied over time and there is a big potential that many of them will serve no value. There is no option or need for users to delete old specifications we present in the dashboard so for now the service is going to …

(490) Automatically remove stale Journey records

---

CHANGELOG.md
app/models/section.rb
app/models/task.rb
app/services/create_journey.rb
app/services/create_section.rb
app/services/create_task.rb
app/services/get_tasks_from_section.rb
db/migrate/20210401105730_create_tasks.rb
db/migrate/20210407111600_add_contentful_id_to_sections.rb
db/schema.rb
spec/factories/section.rb
spec/fixtures/contentful/sections/tasks-section.json
spec/fixtures/contentful/tasks/checkboxes-task.json
spec/models/section_spec.rb
spec/models/task_spec.rb
spec/services/create_journey_step_spec.rb
spec/services/create_section_spec.rb
spec/services/create_task_spec.rb
spec/services/get_tasks_from_section_spec.rb
spec/support/contentful_helpers.rb

- Add Tasks as a model. A Task is a new Contentful model which sits between Section and Steps. A Section can have many Tasks, and a Task can have many Steps.
- When creating a new Journey in the database, we iterate over the Sections and add them to the database. We Then iterate over the Tasks in the section, and add them to the database.
- Currently the Tasks are not visible in the UI, this will be added in later commits. 
- Currently Steps are still grouped by their Sections in the code, not by referring to their parent sections. This will be added in a later commit.

Add Tasks to the database when iterating through Contentful sections

---

app/jobs/delete_stale_journeys_job.rb
app/jobs/warm_entry_cache_job.rb

We saw recently on our first job that including sidekiq_options threw a `NotImplementerError`. We fixed it by removing the retry configuration but the root cause remains a mystery. https://github.com/DFE-Digital/buy-for-your-school/pull/283
The same error happens here so to quickly get moving we remove the retry count and use the Sidekiq defaults. https://rollbar.com/dxw/dfe-buy-for-your-school/items/107/occurrences/160269956473/. If we really do need retry in the future we can invest more time in figuring out why this happens. It is presumably a problem with sidekiq or some conflicting configuration we have that we haven't found yet.
This change should mean this asynchronous starts running at 2am again.

(490) Delete stale journey does not raise NotImplementedError

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/services/get_answers_for_steps.rb
app/services/save_answer.rb
app/services/string_sanitiser.rb
spec/services/get_answers_for_steps_spec.rb
spec/services/save_answer_spec.rb
spec/services/string_sanitiser_spec.rb

- refactor how params are passed to `SaveAnswer` depending on the different types of `Answer` before we begin extending the `SaveAnswer` with sanitisation logic
- strip unsafe tags from all user answers so that we only store safe values in the database. If an answer.response is used with `.html_safe` then no script will be executed in the clients browser
User input given to LongTextAnswer was being unintentionally escaped by using `.to_param` within 
[GetAnswersForSteps](https://github.com/DFE-Digital/buy-for-your-school/blob/develop/app/services/get_answers_for_steps.rb#L26).
User input given to `ShortTextAnswer` or `further_information` fields within `Radios` or `CheckboxAnswers` was not being stripped by `to_param` in the same way so scripts were executed when viewing the spec. …

(568) Sanitise user answers before persisting and on rendering

---

CHANGELOG.md

- Add `noindex,nofollow` meta tag to all pages, as per Gov.UK guidance
- fix API auth by switching mechanism from Basic to Token
- remove `Returning to this specification` URL from task list
- Add Tasks to the database when iterating through Sections from Contentful
- fix XSS vulnerability by sanitising all user answers
- Terraform a new CDN to support the custom host name

release-007

---

.github/workflows/deploy.yml
CHANGELOG.md

[Our research environment currently doesn't work](https://buy-for-your-school-research.london.cloudapps.digital/). This is in part because environment variables hadn't been set yet. In order to propagate those changes I noticed that there was no automatic dpeloyment of that environment configured yet. 
On pushes to the research branch, deploy terraform.

Pushes to research branch auto deploy research environment

---

script/deploy-terraform

* The terraform environment variables need to be in the format
`TF_VAR_variable_name`, however GitHub Secrets capitalizes the name,
making it `TF_VAR_VARIABLE_NAME`
* This PR ensures that all characters after `TF_VAR_` are lowercase

Fix TF_VAR environment names

---

CHANGELOG.md
app/assets/stylesheets/components/_specification.scss
app/services/create_journey.rb
app/services/get_category.rb
spec/features/school_buying_professionals/see_their_catering_specification_spec.rb
spec/fixtures/contentful/categories/multiple-specification-templates.json
spec/services/get_category_spec.rb
spec/support/contentful_helpers.rb

The field coming back from Contentful for a Category called `specification_template` has a problem in that we have added more than 50,000 characters to it. The team still need to add more but we think it is unlikely it will ever need to be more than 100k.
Given Categories are generic and may be reused for Catering as well as future categories like Energy, we should keep our field naming approach generic too. For instance, "specification_template_food_section" would not make sense when creating a Energy section and vice versa.
There are 27 unique sections of the specification at the moment. This is far too many to make a single field per section as every new section would require a code change. Eg. `specification_template_section_28` etc.
The solution we've gone for here is to allow the …

(573) Support specification templates that exceed 50k characters

---

config/initializers/content_security_policy.rb

We don't want scripts or images being loaded from external sites.
Following the principle defence in depth this could be possible if user data was not correctly sanitised. They could inject a `<img src="evil.com">` into the client that would enable malicious activity.
Turning this policy on tells clients not to try and load content from anywhere that's not the current domain(self) and HTTPS.
https://guides.rubyonrails.org/security.html#content-security-policy

(588) Enable Rails Content Security Policy

---

CHANGELOG.md
config/environments/production.rb

This does several things that make our app more secure:
1. Redirects any HTTP traffic to HTTPS
1. Enables [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers which ensure user agents change HTTP into HTTPS before the request is made
1. Marks cookies as secure so they are not sent over the wire in the clear
https://github.com/rails/rails/blob/794252d70990162d14da17ee854ad353e74297ee/actionpack/lib/action_dispatch/middleware/ssl.rb

(590) Force SSL in production

---

CHANGELOG.md
Dockerfile
app/controllers/answers_controller.rb
app/controllers/journeys_controller.rb
app/controllers/specifications_controller.rb
app/controllers/steps_controller.rb
docker-compose.ci.yml
docker-compose.test.yml
script/test

- CI has been running RSpec but RSpec hasn't had any files to test in 1 month https://github.com/DFE-Digital/buy-for-your-school/pull/245. [For example this is a feature 11 days ago with missing rspec ourput](https://github.com/DFE-Digital/buy-for-your-school/runs/2354797149?check_suite_focus=true#step:4:40) (action history doesn't go back that far)
- Fix this issue by copying spec files into the image (remember this used to be `COPY . .` so this change isn't conceptually new)
- Fix missed docker-compose redis configuration problem we now get when running rspec again
Please investigate the Test action for this pull request and verify that the output of RSpec is actually testing our ~359 examples!

RSpec now runs on all examples when run by CI

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml

We recently failed to notice that [all deployments to all environments were silently failing](https://github.com/DFE-Digital/buy-for-your-school/pull/312).
This was fixed but this change introduces Slack notifications to improve the process so that it proactively tells us when failures are occuring.
We can change the output by following the documentation here https://github.com/8398a7/action-slack.

Notify the team on failed deployments

---

CHANGELOG.md
app/views/journeys/index.html.erb
config/locales/en.yml
spec/features/school_buying_professionals/view_a_dashboard_spec.rb

The Existing Specification page displays a useful message when no specifications exisit

Existing Specification page displays useful message when no specs exisit

---

CHANGELOG.md
app/views/steps/long_text.html.erb
app/views/steps/short_text.html.erb

Fixes text input fields width and now displays to full width

Text input field width is now to set to `full` to fit the screen width

---

app/controllers/api/contentful/entries_controller.rb

Webhooks are successfully received but we are finding that the right redis key is not being deleted. Check we are unpacking the params correctly.

Log webhook information to Rollbar for debugging

---

.github/workflows/continuous-integration.yml

The slack channel is going to get very noisy if we notify on test failures for pull request test runs. The dev should already be looking at the pull request to go green before moving it into review so an additional Slack message isn't necessary, I don't think.

Don't notify on every failed build, only those during deployments

---

CHANGELOG.md
README.md

Now we are on GPaaS add our education.gov.uk domains.
We will hopefully be able to update production without our service.gov.uk domain after passing a beta assessment.

Document where to find the service

---

CHANGELOG.md

- add header and footer information for feedback and data requests
- force SSL in production to only accept HTTPS traffic, enable HSTS and secure tower cookies
- prevent concurrent sign ins
- Create Task model; fetch tasks from Contentful and create them in the
database.
- Break direct association between Journey and Steps. Create new association
between Tasks and Steps.
- Show Tasks on Journey page; clicking on a Task name takes you to a task page.
- Show Steps on Task page and allow users to answer questions from Task page
- fix CI not running RSpec

release-010

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
Dockerfile
docker-compose.ci.yml
docker-compose.test.yml
docker-compose.yml

(Opening this while I wait for all my rebasing jobs to succeed to make this process easier)
This work is being copied across from our Rails Template. It was added after this project was created [1].
We are already using Docker Compose in CI on this project. However for context there is another pending change on the Rails Template[2] that includes a screenshot of how caching can behave.
The approach here is that we create a shared area on disk called /tmp/docker-save. We load this in at the start of every test run. It will make a past docker image for this app available to the build context. Docker can then use this image and it's layers to optimise the build steps, opting for the cached version rather than rebuilding from scratch.
If the cache is not hit (meaning the Dockerfile or …

Cache CI runs to reduce run times by ~5 minutes

---

Dockerfile
doc/managing-environment-variables.md

We recently changed the Dockerfile so it accidentally installed `yarn`. This has an unintended consequence when running `bundle exec rake assets:precompile` which causes [builds to fail](https://github.com/DFE-Digital/buy-for-your-school/runs/2449168818?check_suite_focus=true).
I'm not sure how we would install `yarn` and switch from `npm`. Perhaps by using `webpacker`. Suffice to say this is not the current aim so we can fight that one another day.
We make a change to how we run precompile so it we get failure feedback when CI runs on pull requests. Preventing this scenario where the deployment pipeline is unexpectedly blocked.

Fix deployments by removing yarn

---

app/views/layouts/application.html.erb
config/initializers/content_security_policy.rb

Expandable text fields were visible by default
When we switched on the content security policy, we didn't allow inline scripts. We now use the built in helper to generate a nonce for these so the scripts can be loaded.

Inline scripts now use nonce's

---

CHANGELOG.md
app/controllers/api/contentful/entries_controller.rb
spec/requests/cache_invalidation_spec.rb

This was useful for debugging our Contentful webhooks as they weren't working correctly. In this case the Contentful webhook didn't have the right content type set.
Instead of removing this logging, let's make it permenant so we can quickly review basic data on how the service is performing.
We don't want a unique Rollbar event to occur for every entry id so we remove it from the title and move it to the payload. This will mean there should only be a single rollbar item per environment with many occurences, much easier to manage.

Always log info about Contentful webhook receipts

---

CHANGELOG.md
doc/managing-environment-variables.md
script/test
spec/requests/authentication_spec.rb

- Document how to view, change and apply environment variables on the live GPaaS environments.
- We make a minor addition to local environment management to include reference to our Dotenv initialiser for use with critical variables whose absense would prevent the app starting.

Document how to change environment variables

---

CHANGELOG.md
app/models/step.rb
app/models/task.rb
app/views/journeys/show.html.erb
config/locales/en.yml
spec/models/task_spec.rb

This adds display of "not started", "in progress" or "completed" labels to task groups on the task list.
<!-- - [] Document this change in [Confluence](https://dfedigital.atlassian.net/wiki/spaces/GHBFS) --

Add display of task completion to task list

---

.github/workflows/deploy.yml

This change attempts to allow us to once again set environment variables that contain small numbers (such as `30`) without introducing the chance of random deployment failures. These have been occuring when the value appears randomly in the `GIT_SHA` of the commit being deployed.
This happens because of [the way we use `set-output` to pass `DOCKER_IMAGE`](https://github.com/DFE-Digital/buy-for-your-school/blob/develop/.github/workflows/deploy.yml#L36) from one GitHub Action step, to another. This works great normally, GitHub helpfully obfuscates usage of values that are also included as a secret to stop us leaking sensitive information by accident. 
When we want to use `set-output` to pass a value to another step and that value partially matches a secret, then we get the problem: 
When we …

(611) Fix bug that causes deployment failure when there short ENV values are present

---

terraform/app/variables.tf

We have started to see deployments take more than 2 minutes to modify the container. We aren't sure why the incease from 1 minute but want to verify if more time does fix the issue, rather than a stuck process that would never succeed.
Heathy commit:
https://github.com/DFE-Digital/buy-for-your-school/commit/5685d9e6ee179f73995b89b97fdc65f166e987a9
Failing commit:
https://github.com/DFE-Digital/buy-for-your-school/commit/5cb29b93c01b259ce7e079fb55dacb032508a961
Successful deploy (note the less than 2 minutes):
```
cloudfoundry_app.web_worker: Modifications complete after 1m3***s [id=9fc4f563-13ee-4588-bcaf-591b8ba73870]
cloudfoundry_app.web_app: Modifications complete after 1m35s [id=e455373d-44ea-456d-919e-5a5643***3ae3f]
**m
Apply complete! Resources: 0 added, *** changed, 0 destroyed. …
```

Give apps 5 minutes to start rather than 2

---

terraform/app/locals.tf

When we increase `var.web_worker_timeout` to 5 minutes, because it's tied to the `health_check_timeout`, Terraform throws an error since 180 seconds is the maximum for a healthcheck:
```
Error: The app is invalid: health_check_timeout Maximum exceeded: max 180s
```

Worker healthcheck timeout set to maximum

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
Dockerfile
docker-compose.ci.yml
docker-compose.test.yml
docker-compose.yml
script/bootstrap
script/test

Failures - particularly on CI - have been randomly occurring recently. Sometimes the test suite runs before Redis is ready and a large part of the test suite fails due to failing Redis connections.
The Debian `wait-for-it` package is used to wait for Redis to be ready _before_ running the tests. This follows this Docker guidance [1]. We give Redis a generous 60 seconds to start up.
Wait for it is only installed in the test stage of the Dockerfile so it should not be included in the deployed image.
[1] https://docs.docker.com/compose/startup-order/

Fix redis connections on randomly failing on CI

---

app/controllers/journeys_controller.rb
app/controllers/preview/entries_controller.rb
app/services/create_journey.rb
app/services/create_step.rb
spec/requests/entry_preview_spec.rb
spec/services/create_step_spec.rb

A class rename. The naming now sits better alongside the more recent services of: 
```
- CreateJourney
- CreateJourneyStep => CreateStep
- CreateSection
- CreateTask
```

Rename CreateJourneyStep to CreateStep

---

.github/workflows/deploy.yml
CHANGELOG.md

This avoids the [limit of 100](https://docs.github.com/en/actions/reference/encrypted-secrets#limits-for-secrets) `repository` secrets that we just ran into.
By specifying the `environment` within the Github Action job, only the variables within that [Github environment](https://docs.github.com/en/actions/reference/environments#environment-secrets) will be made available.
Given that the environment can only be declared at the top of a `job`, we move  our 4 deployment proceses from `job steps` into individual `jobs`.
I've tested this on the reserch environment. I've removed all RESEARCH keys from the repository secret list and added them all into the environment called `research`. You can take a [peek inside this deployment](https://github.com/DFE-Digital/buy-for-your-school/runs/2582959652 …

(654) Use GitHub environment rather than repository secrets

---

.github/workflows/clone-contentful-to-research.yml
.github/workflows/clone-contentful-to-staging.yml
CHANGELOG.md

The content team need a way to change test their changes to more complex logic such as branching flows that show and hide questions based on extra Contentful logic.
The preview function of Contentful is still useful for testing basic copy changes to a single question. It cannot help us when the test involves stepping through multiple entries.
As a first part of making this testing process easier, we create a new Contentful environment called `staging` and make it possible for GitHub users to easily clone master to staging with 1 click so that the service staging environment (rather than Contentful) can be used for testing purposes - without risking the integrity of production.
The `workflow_dispatch` trigger should only allow this to be triggered manually through the GitHub Actions web …

Use GitHub Action to clone the master Contentful environment to staging

---

CHANGELOG.md

- prevent random CI failures due to missing Redis connections
- GitHub action that allows manual cloning from master to staging with one-click for content testing
- steps are listed in the order set in Contentful rather than database insert order
- fix github secret limit by switching to environment variables

release-013

---

.github/workflows/clone-contentful-to-research.yml
.github/workflows/clone-contentful-to-staging.yml

Without this, cloning environments may have no effect on the target environment untill the currently cached content expires. This is 72 hours by default.
This change repurposes the endpoint we send Contentful webhooks to for cache busting. We will target the starting category entry. This is the first entry that is requested from Contentful and contains the mapping to discover all entries. By cache busting this entry, we make sure that all the latest sections, tasks and steps are requested.
A workaround for this change would be to manually edit the category within Contentful. That would have the same affect. This change automates that, making it more likely to not be forgotten.
For testing of entries, the content designer can still edit individual entries as normal and they will be cache …

Fix cloning Contentful environments by cache busting the category

---

app/models/activity_log_item.rb
app/services/record_action.rb
db/migrate/20210518084959_create_activity_log.rb
db/schema.rb
doc/architecture/013-store-user-activity-in-app.md
spec/models/activity_log_item_spec.rb
spec/services/record_action_spec.rb

Implement a new model for storing event log entries.
This is a timestamped record, along with:
- Internal user ID
- Internal journey ID
- Contentful category ID
- Contentful task ID
- Contentful section ID
- Contentful question ID
- String to describe the action being taken
- JSONB for additional payload needed to describe context
In all cases we are storing strings and not relationships, since journeys in particular may be purged from the database after inactivity, but we still may want to derive information.

Add backend functionality to record events

---

CHANGELOG.md
app/controllers/answers_controller.rb
app/models/task.rb
spec/features/school_buying_professionals/complete_a_journey_spec.rb
spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
spec/features/school_buying_professionals/view_a_task_spec.rb
spec/fixtures/contentful/001-categories/task-with-multiple-steps.json
spec/fixtures/contentful/002-sections/task-with-multiple-steps.json
spec/fixtures/contentful/003-tasks/multiple-steps.json
spec/models/task_spec.rb

Before this change the user would click on one of their tasks and it would present a list of questions. The user would click into a question, answer it and be taken back to the task page.
This is quite a fair bit of back and forth for a user who wants to progress through a related task in the same session. This change will change the redirection in this scenario so that they now only return to the task when we think they're done.
There are more stories to come after this that will change this task page to a check your answers pattern.
- If the task only has 1 step then answering it returns the user to the task page, as before.
- If the step is the last question to be answered then it returns the user to the task page, as before
- Otherwise if there is a remaining unanswered question the …

(639) Answering a task step takes user to the next step

---

CHANGELOG.md

- remove now unused `GetStepFromSection` service to complete code migration to get steps from tasks
- answering steps in a task may take you to the next step unless you've answered them all

release-014

---

CHANGELOG.md
app/controllers/steps_controller.rb
app/controllers/tasks_controller.rb
app/views/journeys/show.html.erb
app/views/tasks/show.html.erb
spec/features/school_buying_professionals/complete_a_journey_spec.rb
spec/features/school_buying_professionals/download_their_catering_specification_spec.rb
spec/features/school_buying_professionals/edit_their_answers_spec.rb
spec/features/school_buying_professionals/see_their_catering_specification_spec.rb
spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
spec/features/school_buying_professionals/view_a_task_spec.rb
spec/support/journey_helpers.rb

Before this change, when a user viewed a task for the first time, they were taken to that tasks page. From there they could choose which question they wanted to answer.
This was mildly problematic because if a user wanted to get on with answering the task they had to make an initial click. It is likely to be the case that when a user opens a task they want to start answering questions.
We don't behave the same for tasks that have been started. We define started as having at least one step that has been answered. When this happens the previous behaviour is still in affect: the user is taken to the task page where they can review what they've done and what they haven't, deciding which question they'd like to answer next.
- refactor the test suite so the test helpers we have make room for …

(640) Starting a task should take the user to the first step

---

app/controllers/tasks_controller.rb
app/models/task.rb

We have a method on task, let's reuse it and consolitate the codebase with a single definition.

Use a single definition for eager loading steps and their answers

---

app/controllers/tasks_controller.rb
app/models/step.rb
app/models/task.rb

Before this change, the following tasks fail:
```
rake db:drop
rake db:create
rake db:migrate
```
```
== 20201202150359 AddContentfulModelToStep: migrating =========================
-- add_column(:steps, :contentful_model, :string)
-> 0.0012s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
PG::UndefinedColumn: ERROR:  column "order" does not exist
LINE 1: ...id" IN (SELECT "steps"."id" FROM "steps" ORDER BY "order" AS...
```
I believe this is because Step now has this code: `default_scope { order(:order) }`.  Given that the `order` column doesn't exist when these earlier updates to the Step table are called, we get an error for missing column.
This changes moves us away from this troublesome `default_scope` method by switching to a plain old …

(656) Stop using default_scope for steps

---

app/controllers/journeys_controller.rb
app/controllers/preview/entries_controller.rb
app/models/journey.rb
app/models/task.rb
app/services/create_journey.rb
db/migrate/20210520155735_add_category_id_to_journey.rb
db/schema.rb
spec/factories/journey.rb
spec/fixtures/contentful/001-categories/category-with-no-title.json
spec/requests/entry_preview_spec.rb
spec/services/create_journey_spec.rb
spec/support/contentful_helpers.rb

- Change behaviour of `CreateJourney` to accept a category ID and derive the name from that, rather than accept a name and rely on the category ID being defined in the class.
- Store the Contentful category ID with newly created journeys, in case we need it later (eg for activity logging)

Refactor CreateJourney to accept and store category ID

---

doc/logging.md

Putting together the syslog drain URL (or even knowing what one is) isn't immediately intuitive - this adds a reference to external CloudFoundry docs on using LogIt as a service.

Add clearer explanation of syslog drain URL

---

spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb

`develop` has somehow had a commit merged which upset standard. This fixes it.

Run standardrb --fix

---

CHANGELOG.md

- always show task title even if it contains a single step
- replace journeys_path with a unified dashboard
- replace back to task list button with a link
- add button to continue completing the current task
- add button to continue to the next incomplete task if the current is complete
- track key user actions throughout the journey

release-015

---

app/views/dashboard/show.html.erb
spec/features/school_buying_professionals/view_a_dashboard_spec.rb
spec/support/sign_in_helpers.rb

- Move the **Create new specification** button to the top-left of the dashboard in order to comply with accessibility requirements by removing the containing `div` and changing the dashboard layout class to `govuk-grid-column-full`.
- Update the **Create new specification** button to be a link.
- Update the `view_a_dashboard_spec` scenario `user can view existing specifications` by checking for the presence of the button and ensuring its containing class is`govuk-grid-column-full`.
- Update other relevant tests now that the button is a link.

#56: Make the create spec button comply with accessibility needs

---

CHANGELOG.md
app/controllers/tasks_controller.rb
app/services/create_journey.rb
app/services/create_task.rb
db/migrate/20210621085254_add_order_to_tasks.rb
db/schema.rb
spec/services/create_task_spec.rb

Add task ordering which is required to reliably find the next unanswered task.

Add ordering to tasks

---

app/controllers/tasks_controller.rb
app/models/checkbox_answers.rb
app/models/currency_answer.rb
app/models/long_text_answer.rb
app/models/number_answer.rb
app/models/radio_answer.rb
app/models/short_text_answer.rb
app/models/single_date_answer.rb
app/models/step.rb
app/models/task.rb
db/migrate/20210621124139_add_step_tally_to_tasks.rb
db/schema.rb
spec/models/checkbox_answers_spec.rb
spec/models/currency_answer_spec.rb
spec/models/long_text_answer_spec.rb
spec/models/radio_answer_spec.rb
spec/models/short_text_answer_spec.rb
spec/models/single_date_answer_spec.rb
spec/models/task_spec.rb

- record numbers of total, visible, hidden and answered steps
- save counters as an extensible hash in JSONB
- use callbacks when answers are committed or steps revealed
- use the persisted tally to calculate task state in other methods
- remove memoisation in Task#eager_loaded_visible_steps which caused issues
- remove dedicated counting methods
- enable the TaskController to find the next_unanswered_task
- add a guard clause to Task#next_unanswered_step_id
- reduce the use of expensive relation loading
- add utility predicate methods to the task to query state
- use answer model class inheritance

Store a hash of step counts on the task

---

config/locales/en.yml
spec/features/visitors/see_a_planning_start_page_spec.rb
spec/features/visitors/see_a_specification_start_page_spec.rb

- skip existing spec coverage for the `/planning` endpoint during diary studies
- link to phase 5

Redirect to prototypes (temporary)

---

app/models/checkbox_answers.rb
app/models/concerns/task_counters.rb
app/models/currency_answer.rb
app/models/long_text_answer.rb
app/models/number_answer.rb
app/models/radio_answer.rb
app/models/short_text_answer.rb
app/models/single_date_answer.rb
spec/models/checkbox_answers_spec.rb
spec/models/currency_answer_spec.rb
spec/models/long_text_answer_spec.rb
spec/models/radio_answer_spec.rb
spec/models/short_text_answer_spec.rb
spec/models/single_date_answer_spec.rb
spec/support/concerns/task_counters.rb

Refactored update_task_counters callback from the answer models into a concern to 'DRY' them up and updated specs to used a shared concern.

Refactored update_task_counters into concern

---

doc/architecture/decisions/0002-use-pull-request-templates.md
doc/architecture/decisions/0004-use-a-changelog-for-tracking-changes-in-a-release.md
doc/architecture/decisions/0005-use-bullet-to-catch-nplus1-queries.md
doc/architecture/decisions/0006-use-dotenv-for-managing-environment-variables.md
doc/architecture/decisions/0007-add-rollbar-for-application-monitoring.md
doc/architecture/decisions/0008-use-brakeman-for-security-analysis.md
doc/architecture/decisions/0009-use-simplecov-to-monitor-code-test-coverage.md
doc/architecture/decisions/0010-use-redis-for-a-read-cache.md
doc/architecture/decisions/0011-use-sidekiq-for-asynchronous-tasks.md
doc/architecture/decisions/0012-create-infrastructure-on-gpaas-cloud-foundry-with-terraform.md
doc/architecture/decisions/0013-use-dfe-sign-in-as-auth-provider.md
doc/architecture/decisions/0014-use-logit-for-application-logs.md
doc/architecture/decisions/0015-store-user-activity-in-app.md

Tidy `/doc/architecture/decisions` so `adr-tools` doesn't become confused.

Fix sequential numbering and clashes in Architecture Decision Records

---

.gitignore
Dockerfile
Gemfile
package-lock.json
package.json

Support for Node version 10 has reached End-of-Life, upgrade to v16.

Bump NodeJS to version 16

---

app/controllers/preview/entries_controller.rb
spec/features/journey_mapping/preview_step_spec.rb
spec/helpers/application_helper_spec.rb
spec/requests/entry_preview_spec.rb

Content and model changes for multiple categories now exist in Contentful's staging environment, these are only compatible with our staging environment which breaks the preview link. Previews per environment seem preferable going forward.
- disable the `Preview::EntriesController` before action `check_app_is_running_in_preview_env`
https://trello.com/c/cQuVkrQK
- remove need for dedicated environment
- move the `preview` endpoint under `/design` and protect this with RBAC when roles and rich sign-in functionality is added

Permit designers to preview entries in the staging environment

---

CHANGELOG.md
app/models/currency_answer.rb
app/models/number_answer.rb
app/models/single_date_answer.rb
app/services/create_step.rb
app/validators/range_validator.rb
db/migrate/20210721115748_add_validation_criteria_to_steps.rb
db/schema.rb
spec/factories/step.rb
spec/features/landing/body_spec.rb
spec/features/steps/answer_validation_spec.rb
spec/fixtures/contentful/002-sections/single-date-section.json
spec/fixtures/contentful/003-tasks/single-date-validation-task.json
spec/fixtures/contentful/004-steps/single-date-in-past-question.json
spec/models/currency_answer_spec.rb
spec/models/single_date_answer_spec.rb
spec/models/step_spec.rb
spec/services/create_step_spec.rb
spec/support/contentful_helpers.rb

Use an optional JSON field to define custom validations for questions.
<https://dfedigital.atlassian.net/wiki/spaces/GHBFS/pages/3261825072/Error+Messages>
- define a custom error message rendered to the user
- use an upper/lower bound to set a range the value must fall within to be considered valid
- cater for open-ended bounds (no upper limit for example)

Implement dynamic validation defined in Contentful

---

app/views/journeys/show.html.erb
doc/accessibility.md

- move task list headings into list items to ensure valid list structure
- add an accessibilty doc as a guide to prevent the same errors in the future

List element has direct children that are not allowed inside list item elements

---

app/controllers/design_controller.rb
app/views/design/show.html.erb
config/locales/en.yml
spec/features/design/show_spec.rb

- replace generic heading text and page title with the current category's title

Use the category's title in `designs#show`

---

app/controllers/sessions_controller.rb
spec/features/landing/dfe_sign_in_spec.rb
spec/requests/authentication_spec.rb

- login failures caused users confusion during diary studies
- alert user to the failure via a flash message rather than render an error page
- feedback suggested this was a sufficient barrier to prevent them using the service
- if this fails we render the error page as before

Clear the session data on a failed authentication and redirect

---

app/controllers/preview/entries_controller.rb
app/models/task.rb
spec/features/design/preview_step_spec.rb
spec/requests/entry_preview_spec.rb

- fix `find_or_create_by` so a journey is created for each designer 
- add missing spec context for multiple designers

Fix shared preview journey

---

CHANGELOG.md
app/jobs/delete_stale_journeys_job.rb
app/jobs/flag_stale_journeys_job.rb
app/models/journey.rb
app/services/create_journey.rb
app/services/delete_stale_journeys.rb
app/services/flag_stale_journeys.rb
config/schedule.yml
db/migrate/20210805130832_change_journey_started_to_false.rb
db/schema.rb
spec/factories/journey.rb
spec/fixtures/contentful/001-categories/category-peter.json
spec/fixtures/contentful/002-sections/section-1-peter.json
spec/fixtures/contentful/002-sections/section-2-peter.json
spec/fixtures/contentful/002-sections/section-3-peter.json
spec/jobs/delete_stale_journeys_job_spec.rb
spec/jobs/flag_stale_journeys_job_spec.rb
spec/models/journey/journey_all_tasks_completed_spec.rb
spec/models/journey_spec.rb
spec/services/create_journey_spec.rb
spec/services/delete_stale_journeys_spec.rb
spec/services/flag_stale_journeys_spec.rb

- a journey is not started by default, database migration added
- a `@journey#started` == true once a step is completed
- a journey's state is discrete so no two states can be applicable
- a journey is flagged as stale if it is not started or edited for X days
- a stale journey can be automatically deleted after a further 30 days
- harden specs for `Journey` and `CreateJourney` to cover associations
- add new fixtures for a complex journey (WIP)
- correct journey factory
- refactor service objects and specs
- add self-documenting scopes to `Journey`
- update CHANGELOG
- complete new fixtures
- activate workers
- expand test coverage for `CreateJourney` further
- test journey scopes

(Re)define "stale" and "started" state for a journey

---

app/controllers/sessions_controller.rb
app/services/user_session.rb
config/locales/en.yml
config/routes.rb
spec/features/auth/sign_in_spec.rb
spec/features/auth/sign_out_spec.rb
spec/requests/authentication_spec.rb
spec/services/user_session_spec.rb

- add sign out notice once the user returns to the home page
- pass redirect_url into `UserSession` keeping routes in controller
- move notice messages into locales

Second refactor of UserSession restoring registered redirect url

---

db/migrate/20210825142733_add_slugs_to_existing_categories.rb
spec/migrations/self-serve/add_slugs_to_existing_categories_spec.rb

- fix a bug where database migration would fail if the `Category.contentful_id` field had an invalid ID while running the `AddSlugsToExistingCategories` migration

Use category slug as an HTML identifier (bugfix)

---

CHANGELOG.md
app/models/support/case.rb
db/migrate/20210909084632_add_unique_to_case_ref.rb
db/migrate/20210909090022_remove_ref_index_support_case.rb
db/migrate/20210909090047_add_unique_ref_index_support_case.rb
db/schema.rb
spec/factories/support/case.rb
spec/models/support/case_spec.rb

- Added generate_ref method to Support::Case
- `generate_ref` called before validation
- Added tests
- rspec define enum for with_values deprecation fix

Add Unique ID for a Support::Case

---

db/migrate/20210908131247_add_default_support_category_timestamps.rb
db/schema.rb

- correct migration [error](https://rollbar.com/dfe-digital/GHBS/items/71/occurrences/181744695606/) which caused `PG::DuplicateColumn`
- `timestamps` is a convenience for creation and cannot be repeated for making changes

Fix incorrect use of `timestamps` in migration when setting new defaults

---

app/controllers/journeys_controller.rb
app/controllers/specifications_controller.rb
spec/features/self-serve/dashboard/new_journey_spec.rb
spec/features/self-serve/journeys/category_spec.rb
spec/features/self-serve/journeys/continue_spec.rb
spec/features/self-serve/journeys/download_spec.rb
spec/features/self-serve/journeys/view_spec.rb
spec/support/matchers.rb

- Add custom rspec matcher to DRY breadcrumbs checks `have_breadcrumbs`
- Convert breadcrumbs to sentence case

Custom rspec matcher for breadcrumbs, sentence case breadcrumbs

---

.env.test
app/controllers/sessions_controller.rb
app/services/create_user.rb
spec/features/self-serve/auth/sign_in_spec.rb
spec/features/self-serve/auth/sign_out_spec.rb
spec/services/self-serve/create_user_spec.rb
spec/support/sign_in_helpers.rb

- users who have previously used the service will have their names added
- changes to names within DSI will be propagated to the `users` table
- entries in the table are reported to via Rollbar when created and updated
- NB: profile changes in the test DSI environment may be slow to take effect

Reflect DSI profile changes

---

app/controllers/support/cases_controller.rb
app/services/support/update_case.rb
spec/features/support/case_edit_spec.rb
spec/services/support/update_case_spec.rb
spec/support/matchers.rb

- Case Update logic was removed from the controller action and placed in [a self-contained testable unit](https://github.com/DFE-Digital/buy-for-your-school/pull/530/files#diff-d7bdf92c88afa3f7c447a24240ca7aac6c7b56132e0e8d92fd28b80b047adefdR5) (`Support::UpdateCase`)
- Redirect user to case page, after successful agent assignment
- [Added spec helper](https://github.com/DFE-Digital/buy-for-your-school/pull/530/files#diff-d35fdbf1d42c668f8f4c92df27b8d3f9151e36132faade568aff709c45044109R77) (following pattern already present elsewhere in the test suite)

Abstract Update Case logic into separate service

---

app/views/support/cases/show.html.erb
config/locales/en.yml
spec/features/support/case_show_spec.rb
spec/features/support/interactions/new_interaction_spec.rb

- Added case action links at the bottom of the Cases show screen
- Links for assigning / re-assigning (case to a worker) work as the functionality is already present
- Merge PR

Add case action links at the bottom of show screen

---

script/spec

A single spec can be run using `script/spec`

Fix running a subset of specs in the docker test env

---

app/assets/stylesheets/components/_specification.scss
app/presenters/long_text_answer_presenter.rb
app/services/document_formatter.rb
app/views/pages/planning_start_page.html.erb
app/views/specifications/show.html.erb
config/locales/en.yml
spec/features/self-serve/journeys/category_spec.rb
spec/features/self-serve/landing/body_spec.rb
spec/features/self-serve/planning/start_page_spec.rb
spec/features/self-serve/steps/presenter_spec.rb
spec/presenters/self-serve/long_text_answer_presenter_spec.rb
spec/services/self-serve/document_formatter_spec.rb
spec/services/self-serve/get_answers_for_steps_spec.rb

- add `govuk` styling to unordered lists
- have Pandoc strip comments when converting specifications
- other changes made in Contentful to fix Markdown

Fix specification appearance

---

config/application.rb
spec/features/self-serve/errors/custom_errors_spec.rb
spec/requests/self-serve/errors_spec.rb

- use custom error page routes to handle HTTP exceptions

Error pages not working

---

docker-compose.test.yml
script/server
spec/spec_helper.rb
spec/support/capybara.rb
spec/support/capybara_driver_helper.rb
spec/support/webmock_helper.rb

Config required to allow chrome usage with capybara to allow more advanced javascript in tests.
Use `js: true` in tests to activate the chrome driver.

Capability to use chrome with capybara using js: true

---

CHANGELOG.md
app/models/activity_log_item.rb
lib/tasks/export.rake
spec/models/self-serve/activity_log_item_spec.rb

- add a rake task to export activity log items as CSV data for convenience
- once the task has been run manually and the file downloaded it should be removed from the server
- potential for restricted access CSV download route so Data Analysts can interact without developer input

Interim solution to export KPI data

---

CHANGELOG.md
app/models/activity_log_item.rb
app/models/support/activity_log_item.rb
app/models/support/case.rb
db/schema.rb
lib/tasks/export.rake
spec/models/support/case_spec.rb

- add a `to_csv` method into `Support::Case`
- add case data as an option to the `export` rake task

Add csv export task for Support::Cases

---

app/controllers/pages_controller.rb
app/services/content/page/build.rb
db/migrate/20211123110903_add_breadcrumbs_to_pages.rb
db/schema.rb
spec/factories/pages.rb
spec/features/pages/breadcrumbs_spec.rb
spec/requests/self-serve/api/contentful/pages_controller_spec.rb
spec/services/self-serve/content/page/build_spec.rb
spec/services/self-serve/content/page/get_spec.rb
spec/support/contentful_helpers.rb

- add `breadcrumbs` field to `pages`
- add a method to generate breadcrumbs based on `Page.breadcrumbs`

Add breadcrumbs to Pages

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_override.scss
app/assets/stylesheets/components/_page.scss
app/presenters/support/case_presenter.rb
app/views/pages/_sidebar.html.erb
app/views/pages/show.html.erb
config/locales/en.yml
spec/features/self-serve/pages/show_spec.rb

* Removes bullet styling of lists for page sidebar
* reinstates timestamp styling

[154] Correct Page CSS

---

app/views/support/cases/case_history/_interaction.html.erb
app/views/support/cases/show.html.erb
spec/features/self-serve/pages/show_spec.rb
spec/features/support/interactions/list_interactions_spec.rb

This fixes an error opening the email in a new tab. The URL was malformed - passing in the current_case fixed the issue.

Uploaded email link and spec

---

app/controllers/admin_controller.rb
app/models/user.rb
app/presenters/user_presenter.rb
app/views/admin/show.html.erb
app/views/errors/missing_role.html.erb
config/locales/en.yml
config/routes.rb
spec/factories/user.rb
spec/features/self-serve/admin/show_spec.rb
spec/models/self-serve/user/user_analyst_spec.rb

- add new page `/admin`
- add new `User` scope `analysts`

Internal admin page secured by check on user roles

---

app/controllers/support/cases/assignments_controller.rb
app/controllers/tasks_controller.rb
app/models/support/agent.rb
db/migrate/20211222162846_add_internal_to_support_agents.rb
spec/factories/support/agent.rb
spec/features/support/case_assignment_spec.rb

- add `internal` field to `agent`
- add `caseworkers` scope to `agent`
- filter out internal team members on the case assignment page

Hide internal team members from assignable case workers

---

lib/microsoft_graph/client_session.rb
spec/lib/microsoft_graph/client_session_spec.rb

Previously the ms graph api ignored paged result sets, this ensures that when there are a lot of results the graph library follows each page to get the entire result set.

Ensure ms graph next link is followed

---

.rubocop_todo.yml
app/controllers/application_controller.rb
app/models/support/email_attachment.rb
app/presenters/support/email_presenter.rb
app/views/support/emails/show.html.erb
config/brakeman.ignore
db/migrate/20220112131559_add_is_inline_to_support_email_attachments.rb
db/schema.rb
spec/presenters/support/email_presenter_spec.rb

Email attachments marked as "inline" are displayed within the email body as expected.

Display inline email attachments

---

app/controllers/support/cases/emails/content_controller.rb

Notify templates have "reference" variable defined, the email preview functionality does not currently supply it.
Notify errors when a defined variable is not supplied.
This PR fixes the issue by defining the variable.

Bug: Email preview requires reference variable

---

app/views/support/emails/_email_list.html.erb

Emails being bold when unread looks odd given you cannot mark them as read yet.
Put this styling back in when "mark as read" story is developed

Remove email "unread" styling for now

---

app/forms/support/case_hub_migration_form_schema.rb
app/forms/support_form_schema.rb
config/locales/validation/en.yml
config/locales/validation/support/en.yml
spec/factories/support_request.rb
spec/features/self-serve/support_requests/create_support_request_spec.rb
spec/features/support/case_migration_spec.rb

- amended rule for phone number validation in hub cases as follows; (i) permits empty string in event of no entry, (ii) 0 followed by 9 or 10 digits, OR +44 followed by 9 or 10 digits, (iii) no spaces at any point in the number
- max_digits? captures the + in +44, so value of 13, although message correctly displays 12, with number entered greater than 12 digits

Error on phone number validation

---

app/controllers/support/cases/emails/content_controller.rb
spec/features/support/emails/agent_sends_basic_email_spec.rb

If a user edited the body of a non-template email and then went to the preview, they would lose the changes they'd made. This allows them to keep it.

Retain edited email body when going back from preview

---

app/forms/framework_support_form_schema.rb
app/views/framework_requests/steps/_form.html.erb
app/views/framework_requests/steps/_step_2.html.erb
app/views/framework_requests/steps/_step_3.html.erb
config/locales/en.yml
config/locales/validation/en.yml

* formatting for email and name faf pages
* custom error messages
* adds email format validation

[232, 233] Faf - name and email

---

app/assets/javascripts/faf_confirm_school.js
app/controllers/framework_requests_controller.rb
app/presenters/support/organisation_presenter.rb
app/views/framework_requests/show.html.erb
app/views/framework_requests/steps/_step_5.html.erb
app/views/framework_requests/steps/_step_6.html.erb
config/locales/en.yml
spec/presenters/support/organisation_presenter_spec.rb

- add the "Is this the school you're buying for?" page

FaF Support Request - is this the school? page

---

app/controllers/support/cases/emails/content_controller.rb
spec/features/support/emails/agent_sends_basic_email_spec.rb
spec/features/support/emails/agent_sends_templated_email_spec.rb

Sends the case reference as a personalised parameter for non-templated emails. 
Basic email template will have to be updated to include the reference in the subject and email body.

Add case reference to personalisation params on non-templated emails

---

app/controllers/framework_requests_controller.rb
app/presenters/framework_request_presenter.rb
app/views/framework_requests/show.html.erb
config/locales/en.yml
config/locales/validation/en.yml
spec/features/self-serve/faf/create_framework_request_no_dsi_spec.rb
spec/features/self-serve/faf/create_framework_request_spec.rb
spec/features/self-serve/faf/edit_framework_request_spec.rb
spec/support/capybara_driver_helper.rb

- School or group name, as well as school/group type displaying on CYA page

FaF MAT n Trusts - Add 'School type' to the None DSI CYA page

---

app/services/support/merge_case_emails.rb
spec/services/support/merge_case_emails_spec.rb

After merging emails/interactions from one new case to another:
* `from_case`'s `state` is set to `:closed`
* `from_case`'s `action_required` is set to `false`
* `to_case`'s `action_required` is set to `true` (state is **not** changed)

[271] Correct support_case statuses on email merge

---

app/controllers/framework_requests_controller.rb
app/views/framework_requests/show.html.erb
spec/features/self-serve/faf/create_framework_request_spec.rb

- No DSI journey - 'school type' change link now permits user to then select school/group after changing selection at step 2
- DSI journey - 'school type' change link no longer appearing.

FaF school type change link fix

---

app/controllers/support/cases_controller.rb

Cases in supported are now ordered by ``` created_at: :desc```, ie newest cases first, rather than by the date of the latest interaction.

Change order of cases in supported

---

config/locales/en.yml
config/locales/validation/en.yml
spec/features/self-serve/faf/create_framework_request_no_dsi_spec.rb

- Update content for FaF guest user group selection and validation
- simplify assertions for current step number in back link functionality

Content change for FaF guest user journey

---

app/services/submit_framework_request.rb
spec/features/self-serve/faf/submit_framework_request_map_org_spec.rb

- when a FaF request is made with a group (MAT or Fed) this is now displayed in case management

FaF Group name not appearing on the Case created in CM

---

app/presenters/support/case_presenter.rb
spec/presenters/support/case_presenter_spec.rb

- 'last updated' in 'all cases' and 'my cases' within CM now showing the date of the most recent interaction rather than the oldest

last_updated_at is displaying incorrect date

---

app/controllers/support/save_attachments_controller.rb
app/forms/support/save_attachments_form.rb
spec/forms/support/save_attachments_form_spec.rb

Previously the first attachment saves and then throws a 500 error before saving the other.
Now it will not save any of them and warn the user instead.

Fix bug: graceful validation of duplicate attachments

---

app/controllers/framework_requests_controller.rb
spec/features/self-serve/framework_requests/start_page_spec.rb
spec/features/self-serve/profile_spec.rb

- allow a FaF support request journey to be started
- allow subsequent non-FaF support requests from the dashboard via the profile page
- only clear the faf journey session variable once the first authenticated answer has been posted

FaF support journey start

---

app/controllers/support/application_controller.rb
app/controllers/support/cases_controller.rb
app/views/support/cases/_row.erb
spec/features/support/case_navigation_spec.rb

- add `back_to` parameter to case paths that contains the encoded current URL when going from cases `index` action to `show` action so it can be used as the back link

Case navigation back link

---

app/forms/support_form_schema.rb
config/locales/validation/en.yml

The [bug](https://rollbar.com/dfe-digital/GHBS/items/327/) was being caused by an attempt to validate a disabled field. The `phone_number` field in the Support Request form was disabled/commented out a while ago with the intention to re-enable it at a later point, but its validation in the schema was not disabled. This caused the schema to validate a nil field.
- disable validation for the unused `phone_number` field in the Support Request form

Disable validation for unused Support Request field

---

app/services/submit_framework_request.rb

Rollbar error: https://rollbar.com/dfe-digital/GHBS/items/467
- revert changes made to `SubmitFrameworkRequest` where the `request` was being cast from `FrameworkRequest` into `FrameworkRequestPresenter`, thus providing a user struct for non-DSI users.

SubmitFrameworkRequest bugfix

---

app/helpers/support/collection_helper.rb
app/models/support/category.rb
config/support/categories.yml
lib/tasks/case_management.rake
spec/helpers/support/collection_helper_spec.rb
spec/models/support/category_spec.rb

- A rake task to move a category from one parent to another
- Don't show categories that have no subcategories in any dropdowns.
- run `rails case_management:change_sub_category_parent'[MFD, ICT]'` on prod

Ability to move category from 1 parent to another

---

app/views/support/cases/emails/templates/index.html.erb
config/locales/en.yml
spec/features/support/emails/agent_sends_templated_email_spec.rb

Remove "Exit survey" email template from CMS

Remove exit survey from templates

---

app/presenters/support/case_presenter.rb

- don't display message threads with no ID (some emails come in without a conversation_id)

Exclude threads with no id

---

app/presenters/support/messages/notify_message_presenter.rb
app/presenters/support/messages/outlook_message_presenter.rb
app/views/support/cases/message_threads/_four_or_less_messages.html.erb
app/views/support/cases/message_threads/_greater_than_four_messages.html.erb
app/views/support/cases/message_threads/_message.erb

There are too many edge cases where the user will need to see quoted messages, simply show this button all the time for now.

Always show message recap

---

app/assets/stylesheets/components/supported/_messages.scss
app/controllers/support/cases/message_threads_controller.rb
app/javascript/components/add-recipients.js
app/views/support/cases/messages/replies/_form.html.erb
app/views/support/cases/messages/replies/_new_message_components.html.erb
config/locales/en.yml
spec/features/support/emails/agent_can_send_new_emails_spec.rb

- The case contact email is auto populated to the "To" field when creating a new email thread
- Visual improvements such as lining up table columns and giving more space to input boxes for legibility
- Ability to press enter in an input box to add the recipient
https://user-images.githubusercontent.com/1352756/192776935-068960a1-72ec-4597-8e62-962af027a624.mov

TO field pre-populated on new message thread page

---

app/controllers/support/interactions_controller.rb
app/views/support/cases/_case_actions.html.erb

- allow the addition of case notes to all cases regardless of status
- fix redirect path for added notes

Option to add a case note when case is on hold

---

.github/workflows/actions/build-docker-image/action.yml

Having problems deploying due to the following errors:
```
202***-0***-2***T***0:06:08.***8+0000 [STG/0] ERR Failed getting docker image manifest by tag: Error reading manifest 805a248 in ghcr.io/dfe-digital/buy-for-your-school: manifest unknown: OCI index found, but Accept header does not support OCI indexes  Going to retry attempt: ***
202***-0***-2***T***0:06:08.77+0000 [STG/0] ERR Failed getting docker image manifest by tag: Error reading manifest 805a248 in ghcr.io/dfe-digital/buy-for-your-school: manifest unknown: OCI index found, but Accept header does not support OCI indexes  Going to retry attempt: 2
202***-0***-2***T***0:06:09.***9+0000 [STG/0] ERR Failed getting docker image manifest by tag: Error reading manifest 805a248 in ghcr.io/dfe-digital/buy-for-your-school: manifest …
```

Pin docker buildx to fix OCI issue on CF

---

app/controllers/support/management/category_detections_controller.rb
app/forms/support/category_detection_form.rb
app/models/support/category_detection.rb
app/services/submit_framework_request.rb
app/views/support/management/category_detections/new.html.erb
spec/services/self-serve/submit_framework_request_spec.rb

Limit the category detection to only categories in the Energy tower when the user has specified the RFH is for energy

feat(rfh): detect only energy tower cats eng reqs

---

app/javascript/controllers/energy_bill_upload_controller.js

Added the Continue button text values to the `energy_bill_upload_controller`'s `values` object. These were previously missing and causing the button to show "undefined" when `pageOne` elements were being rendered.

fix(rfh): define bill upload button values

---

app/controllers/specifications_controller.rb
app/presenters/journey_presenter.rb
app/views/specifications/show.html.erb
spec/controllers/self-serve/specifications_controller_spec.rb
spec/presenters/self-serve/journey_presenter_spec.rb

Fixed the links and redirects to the Next Steps pages by ensuring that they go to the right page based on the specification category.
Jira: PWNN-417

fix(specify): fix next steps links and redirects

---

app/assets/stylesheets/components/_autocomplete.scss
app/controllers/support/establishment_groups_controller.rb
app/controllers/support/organisations_controller.rb
app/forms/framework_requests/procurement_amount_form.rb
app/javascript/components/autocomplete.js
app/presenters/request_presenter.rb
app/presenters/support/establishment_group_presenter.rb
app/presenters/support/organisation_presenter.rb
app/views/framework_request_submissions/show.html.erb
app/views/framework_requests/confirm_organisations/_confirm_group.html.erb
app/views/framework_requests/emails/_form.html.erb
app/views/framework_requests/procurement_amounts/_form.html.erb
app/views/framework_requests/procurement_amounts/_form_hint.erb
app/views/framework_requests/show.html.erb
config/locales/en.yml
spec/features/self-serve/framework_requests/create_framework_request_guest_spec.rb
spec/features/self-serve/support_requests/edit_support_request_spec.rb
spec/forms/framework_requests/procurement_amount_form_spec.rb
spec/presenters/self-serve/request_presenter_spec.rb
spec/presenters/support/establishment_group_presenter_spec.rb
spec/presenters/support/organisation_presenter_spec.rb

Fixes to accessibility audit failures in the Request For Help form.
- change 'ID' to 'IDs' on the Confirm Your Organisation page
- give more descriptive aria labels to 'Change' links on the Check Your Answers page
- fix a bug where the label is not associated with the input field for email
- give the submission confirmation page a title
- show "Not provided" when:
- an academy trust/federation does not have an address or a UKPRN
- a school does not have an address, contact, local authority, phase or UKPRN
- a procurement value is not provided (was 'Not known')
- relax the validation for the procurement value field to allow the pound sign
- increase the search result limit for school and academy trust/federation autocompletes from 25 to 50
- change the font for the 'No results found' …

Fix accessibility audit failures in RFH

---

app/services/support/create_case.rb
spec/services/support/create_case_spec.rb

All new cases will have default procurement stage, level and value fields.
- procurement stage: "Need"
- support level: 1
- case value: procurement value, if provided
Jira: PWNN-1246

feat(cms): prepopulate case stage, level, value

---

app/views/layouts/_breadcrumbs.html.erb
app/views/support/cases/index/_tab_all_cases.html.erb
app/views/support/cases/index/_tab_my_cases.html.erb
app/views/support/cases/index/_tab_new_cases.html.erb

Fixes for accessibility audit failures in CMS and Specify.
- add an aria label to breadcrumbs in Create-a-Spec and use `nav` tag
- change CMS tab headings (on index page) to from `h2` to `h1`
- PWNN-1183
- PWNN-1161

Fix accessibility audit failures in CMS & Specify

---

app/controllers/support/cases/searches_controller.rb
app/services/support/search_cases.rb
app/views/support/cases/message_threads/index.html.erb
app/views/support/cases/searches/_result.html.erb
app/views/support/cases/show/_case_attachments.html.erb
app/views/support/cases/show/_case_details.html.erb
app/views/support/cases/show/_case_history.html.erb
app/views/support/cases/show/_school_details.html.erb
config/locales/validation/support/en.yml
spec/features/support/agent_can_change_case_request_details_spec.rb
spec/features/support/agent_can_change_case_summary_spec.rb
spec/features/support/case_description_spec.rb
spec/features/support/case_procurement_details_spec.rb
spec/services/support/search_cases_spec.rb

- added `h2` headings to the tabs on the case show page
- added a custom validation message for case notes with a blank body
- updated the back link on the 'Find a case' results page to go back to the initial search page
- aligned the "Find a case" results table with the "All cases" table
- PWNN-1187
- PWNN-1165
- PWNN-1185
- PWNN-1191

Remaining accessibiltiy fixes in CMS

---

app/controllers/support/cases/message_threads_controller.rb
app/views/support/cases/show.html.erb
spec/controllers/support/cases/message_threads_controller_spec.rb

The messages frame can now accept a `messages_tab_url` param on the cases show route and navigate there.

fix(cms): dynamic messages frame

---

app/assets/stylesheets/components/supported/_messages.scss
app/helpers/date_helper.rb
app/javascript/components/display-cc-bcc.js
app/views/support/cases/_not_found.html.erb
app/views/support/cases/case_history/_interaction.html.erb
app/views/support/cases/index/_detailed_case.html.erb
app/views/support/cases/index/_detailed_cases.html.erb
app/views/support/cases/index/_simple_case.html.erb
app/views/support/cases/index/_simple_cases.html.erb
app/views/support/cases/message_threads/_logged_contact_thread.html.erb
app/views/support/cases/message_threads/_templated_message_thread.html.erb
app/views/support/cases/message_threads/_thread.html.erb
app/views/support/cases/message_threads/index.html.erb
app/views/support/cases/messages/replies/_form.html.erb
app/views/support/cases/messages/replies/_new_message_components.html.erb
app/views/support/cases/searches/index.html.erb
app/views/support/cases/show/_case_attachments.html.erb
config/locales/en.yml
spec/features/support/emails/agent_can_send_new_emails_spec.rb
spec/features/support/emails/agent_sees_email_threads_spec.rb
spec/features/support/interactions/list_interactions_spec.rb
spec/helpers/self-serve/date_helper_spec.rb

- renamed the add buttons in 'Create a new message thread' and split 'Show CC/BCC' into two
- added a read/unread status badge to the message threads view
- updated the text shown when there are no cases to display in case tabs and case search
- PWNN-1184
- PWNN-1189
- PWNN-1162
- PWNN-1226

CMS accessibility improvements

---

app/presenters/support/message_thread_presenter.rb
app/presenters/support/messages/outlook_message_presenter.rb
app/services/support/messages/outlook/message.rb
app/services/support/messages/outlook/send_reply_to_email.rb
app/services/support/messages/outlook/synchronisation/steps/persist_email.rb
app/views/support/cases/message_threads/_recipient_table.html.erb
app/views/support/cases/message_threads/_recipients.html.erb
app/views/support/cases/message_threads/show.html.erb
db/migrate/20230309165049_add_to_cc_bcc_recipients_to_support_emails.rb
db/schema.rb
lib/microsoft_graph/client.rb
lib/tasks/data_migrations.rake
spec/factories/support/email.rb
spec/features/support/emails/agent_can_send_replies_spec.rb
spec/presenters/support/messages/outlook_message_presenter_spec.rb
spec/services/support/messages/outlook/send_reply_to_email_spec.rb
spec/services/support/messages/outlook/synchronisation/steps/persist_email_spec.rb

- The message reply details now shows the To, CC and BCC recipients
- The columns for the different types of recipients have been added to support_emails
- Sending a reply now calls "createReplyAll" on the MS Graph API
Jira: PWNN-879

879 - Show message contacts

---

app/models/support/agent.rb
app/presenters/support/case_presenter.rb
app/views/support/cases/index/_detailed_case.html.erb
app/views/support/cases/messages/_reply_form_template.html.erb
spec/models/support/agent_spec.rb

- the initials of the agent who wrote the latest case note are now shown
- the email signature has been updated
Jira: PWNN-1279, PWNN-1295

1279, 1295 - show agent initials on latest note, new email signature

---

app/assets/stylesheets/base/_frontend.scss
app/views/support/cases/case_history/_interaction.html.erb
app/views/support/cases/message_threads/_message.erb

- The layout of notes and logged contacts is now preserved, rather than collapsed to a single line.

Retain layout for notes and logged contacts.

---

terraform/app/variables.tf

- add `pg_trgm` to enabled PostgreSQL extensions in Terraform
Jira: PWNN-1413

1413 - ci: add pg_trgm to postgres extensions

---

config/request_for_help/categories.yml
config/support/categories.yml
spec/services/support/seed_categories_spec.rb

- fix mapping to "Vehicle hire or purchase" category form RFH to CMS by fixing typo
- fix mappings to "Broadband service" and "Broadband infrastructure" categories form RFH to CMS by un-archiving corresponding categories in CMS
Jira: PWNN-1527

1527 - fix(rfh): fix missing category mappings

---

config/environments/production.rb
lib/middleware/application_insights_track_request_conditionally.rb

As azure front door does not currently support websockets, action cable will fail it's initial request. 
This is a temporary fix to stop these 404s polluting our app insights dashboards as failures.

fix: app insights ignore cable 404s

---

app/presenters/support/messages/notify_message_presenter.rb
app/views/engagement/cases/previews/new.html.erb
app/views/support/cases/message_threads/_message.erb
app/views/support/cases/previews/new.html.erb
app/views/support/cases/show/_case_details.html.erb

- fixed excessive whitespace in message bodies by removing `simple_format`
- added `simple_format` to bodies of non-messages to retain intended whitespace
Jira: PWNN-1491

1491 - fix(cms): fix formatting of text with whitespace

---

app/forms/framework_requests/email_form.rb
config/locales/en.yml
config/locales/validation/en.yml
spec/features/specify/framework_requests/create_framework_request_guest_spec.rb
spec/forms/framework_requests/email_form_spec.rb

- Added validation to exclude personal email addresses when filling out the request for help form when signing in as a guest

1639 feat(rfh): add validation to the email form to exclude certain addresses

---

app/models/support/case.rb
app/views/support/cases/discovery_method/_discovery_method.html.erb
config/locales/en.yml
spec/features/engagement/create_case_spec.rb
spec/features/support/case_summary_spec.rb
spec/features/support/create_case_spec.rb

Definition of discovery_methods changed to:
#
enum discovery_method: { used_before: 0, meeting_or_event: 1, dfe_publication: 2, non_dfe_publication: 3, recommendation: 4, search_engine: 5, social_media: 6, website: 7, other: 8 }
(note: non_dfe_publication is new and shunted the remaining enum cases along by a digit, but there is no live data using the enum yet so this was considered the preferred route)

1683 - feat(cms): change case origin options

---

app/cores/case_management/handle_messages.rb
spec/cores/case_management/handle_messages_spec.rb

- fixes the bug where a case created by email is automatically transitioned from `initial` state to `opened`
Jira: PWNN-1685

1685 - fix(cms): cases created by email stay new

---

app/views/support/cases/school_details/participating_schools/edit.html.erb
app/views/support/cases/school_details/participating_schools/show.html.erb
app/views/support/cases/school_details/show.html.erb
app/views/support/cases/show/_school_details.html.erb

- fixes a bug where the content of the School Details tab was being shown in other tabs if the tab is specified in the URL hash

fix(cms): school details tab shown in other tabs

---

app/presenters/framework_request_presenter.rb
app/services/submit_framework_request.rb
app/services/support/email_templates.rb
spec/presenters/self-serve/framework_request_presenter_spec.rb

Changes to the email confirmation after submitting a request for help, mainly changing the request message for a summary of information.

1574 - feat(rfh): edit confirmation email

---

app/cores/case_files/unique_attachments_for_case.rb
app/models/support/email_attachment/de_dupable.rb
db/schema.rb
spec/models/support/email_attachment_spec.rb

Fixes 3 bugs:
- Duplicate e-mail attachments not showing correctly (should be 1 of each duplicate within a case) in CMS -> Attachments -> All Files
- Duplicate e-mail attachments missing in CMS -> Attachments -> Received Files / Sent Files even when they're correctly listed in that case's All Files
- Duplicate e-mail attachments going missing between cases

1657 - fix(cms): duplicate email attachments not displaying correctly

---

app/controllers/framework_requests_controller.rb
spec/features/specify/framework_requests/edit_framework_request_dsi_spec.rb
spec/features/specify/framework_requests/edit_framework_request_guest_spec.rb

- removed the Back link from the `framework_request` show ( a.k.a. Check Your Answers) view
Jira: PWNN-1691

1691 - fix(rfh): remove back link from show view

---

app/controllers/framework_request_submissions_controller.rb
app/controllers/framework_requests/origins_controller.rb
app/views/support/interactions/forms/_contact.html.erb
spec/lib/specify/school/information_call_spec.rb
spec/lib/support/establishment_groups/information_call_spec.rb
spec/services/support/messages/outlook/synchronisation/message_attachment_importer_spec.rb

- [fix(rfh): remove request id later in the journey](https://github.com/DFE-Digital/buy-for-your-school/commit/fecc8c64c99f7a9823e3caaa4595766cdbb3c7d6)
Some users like to use the browser back button to go back to the questions once they've completed the RFH form. Until now the `framework_request_id` has been removed from the session when the last question is answered, so if the user used the browser back button to go back and change an existing answer or refresh the page on an answered question, a new `framework_request` would be created and the user would be filling out a new `framework_request`, but backwards. The thing would eventually crash because some questions depend on previous answers and a new `framework_request` wouldn't have these answers. The `framework_request_id` is now …

RFH & CMS bugfixes

---

app/services/create_user.rb
spec/services/specify/create_user_spec.rb

When logging in for the first time with a pre-created agent, the service looks up the agent by email in a case sensitive way. This PR attempts to make the lookup case insensitive.

fix: case insensitive email lookup for agent login

---

.github/workflows/support-update-ssl-cert-validation-implementation.yml
.github/workflows/support-update-ssl-cert-validation.yml

Fixes the issue with github actions that we need to approve a deployment to production in order to first check if we need to update the ssl validation.
This PR makes it so that we are able to check the validation status with a read-only azure log in, and then moves to a production environment only when it needs to make the change - and therefor correctly require approval (and send slack messages etc).
Sets the job to run every Monday so we can't forget to check the validation status.

ci: allow new prod read only to check ssl verification

---

app/controllers/engagement/case_requests/same_suppliers_controller.rb
app/controllers/engagement/case_requests/school_pickers_controller.rb
app/controllers/engagement/case_requests_controller.rb
app/models/case_request.rb
app/models/framework_request.rb
app/models/request_for_help_category.rb
app/models/support/category.rb
app/views/engagement/case_requests/show.html.erb
app/views/support/cases/request_details/show.html.erb
spec/models/request_for_help_category_spec.rb

Added `is_energy_or_services?` to `RequestForHelpCategory` to fix error as view previously assumed request category was a `Category`.
Moved `is_energy_or_services?` to `CaseRequest` + `FrameworkRequest` to avoid needing to call the `Category` / `RequestForHelpCategory`

fix: missing is_energy_or_services? method

---

.env.test
.github/workflows/ci-full-pipeline.yml
app/assets/stylesheets/base/_misc.scss
app/controllers/end_of_journey_surveys/thank_yous_controller.rb
app/controllers/end_of_journey_surveys_controller.rb
app/models/end_of_journey_survey_response.rb
app/views/end_of_journey_surveys/new.html.erb
app/views/end_of_journey_surveys/thank_yous/show.html.erb
app/views/framework_request_submissions/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20240126153454_create_end_of_journey_survey_responses.rb
db/schema.rb
spec/models/end_of_journey_survey_response_spec.rb
spec/requests/end_of_journey_survey/end_of_journey_survey_flow_spec.rb
spec/requests/end_of_journey_survey/end_of_journey_survey_for_service_spec.rb

- add the `end_of_journey_survey_responses` table to store user feedback collected at the end of the RfH and FaF journeys
- allow JSON POST requests to come in from FaF and store user feedback

1841 - feat: end-of-journey survey

---

app/javascript/controllers/framework_edit_controller.js
app/javascript/controllers/index.js
app/views/components/_autocomplete.html.erb
app/views/support/cases/procurement_details/edit.html.erb
spec/features/support/procurement_details/edit_procurment_details_spec.rb

- Ability to clear framework from case
- If there is no framework in the case then there is no clear framework link, if there is a framework then there is a clear framework link that removes the value, clears the box, and removes the clear framework link

1894 - fix(cms): add ability to remove framework

---

db/migrate/20240222143743_backfill_missing_customer_satisfaction_survey_cases.rb
db/migrate/20240222164526_update_exit_survey_sent_flag_on_old_cases.rb
db/schema.rb

- backfill the missing customer satisfaction survey response links to cases (PWNN-1908)
- update the `exit_survey_sent` flag on old cases that have Qualtrics survey responses (PWNN-1939)

1908 & 1939 - Update production data

---

app/helpers/support/filter_helper.rb

Reordered the ProcementStage substages within the ProcOps CMS filter panel, to be in lifecycle order

pwnn-1952 fix(cms): filter panel substages in wrong order

---

app/presenters/request_presenter.rb
spec/features/specify/support_requests/edit_support_request_spec.rb
spec/presenters/self-serve/request_presenter_spec.rb

- Changes "-" to "No" for accessibility answer display for requests (/support-requests and /procurement-support)

1170 - feat: change dash to no for accessibility requirements answer display

---

.github/workflows/support-update-ssl-cert-validation-implementation.yml

The SSL Certificate Validation workflow breaks because the `RESOURCE_GROUP_NAME` secret is being passed between jobs. However, [secrets cannot be assigned to job outputs and then be accessed in a subsequent job because they are redacted](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs).
To fix this, I set the secret as an environment variable at the workflow level so it can be accessed by any job.

fix: ssl cert workflow redacted secret

---

.github/workflows/support-update-ssl-cert-validation-implementation.yml

Add the missing Azure login step to the `update_validation` job in the "Support - Update SSL Cert Validation" workflow.

fix: add missing az login step to SSL workflow

---

app/controllers/support/email_read_status_controller.rb
app/views/support/cases/message_threads/stream_events/_marked_as_read.turbo_stream.erb
app/views/support/cases/show/_tabs.html.erb
db/migrate/20240702145517_add_support_emails_indexes.rb
db/migrate/20240703155237_add_support_email_attachments_indexes.rb
db/schema.rb
spec/features/support/emails/agent_can_mark_email_as_read_spec.rb

After trying out different combinations of indexes for the `support_emails` table and inspecting the query plan outputted by `EXPLAIN ANALYSE`, I've found that the Postgres planner seems to prefer the 3 indexes I've added to the schema.
Tested on local data only (significantly smaller number of rows than production), I see these reductions in **execution time**:
- for the`support_message_threads` view, down from ~180 ms to 15-20 ms
- for a query that fetches all the threads for a case with 35 threads and 64 emails (where `ticket_id` and `ticket_type` are specified in the `WHERE` clause), down from ~20 ms to ~1.5 ms
- for a query that fetches all the emails for a case with 64 emails (where `ticket_id` and `ticket_type` are specified in the `WHERE` clause), down from ~0.4 ms to ~0.1 ms …

pwnn-2018 - message bugs and performance issues

---

.github/workflows/ci-full-pipeline.yml

Added 3 new jobs to the CI/CD - Full Pipeline:
1. **Data regression testing - trigger copy to pre-release-original-data**
This triggers the "Pre-release Original Data sync" pipeline in Azure DevOps to apply a copy of the production database to the `pre_release_original_data` database in the production Postgres reporting server upon successful deployment to production.
2. **Data regression testing - trigger copy to pre-release-modified-data**
This triggers the "Pre-release Modified Data sync" pipeline in Azure DevOps to apply a copy of the production database to the `pre_release_modified_data` database in the production Postgres reporting server upon successful deployment to production.
3. **Data regression testing - apply migrations to pre-release-modified-data**
This runs the database …

1980 - ci: add data regression testing jobs

---

.github/workflows/ci-full-pipeline.yml

- Remove the environments from the data regression jobs - they seem to turn the jobs into deployments?
- Reference the correct Docker image in `data_regression_migrate_modified`.

1980 - ci: fix data regression job issues

---

.github/workflows/ci-full-pipeline.yml

- Updated the dependencies for job `data_regression_migrate_modified` to include `build_release` so that we can access the release Docker image.

1980 - ci: update data regression job dependencies

---

.github/workflows/ci-full-pipeline.yml

- Add `APPLICATION_URL` and set it to the production URL on the data_regression_migrate_modified job. This is to ensure that migrations only meant for certain environments (ones that check `APPLICATION_URL`) are executed when needed. We will want production migrations to be applied to `pre-release-modified-data`.

1980 - ci: set prod url on data regression env

---

Dockerfile

- Specified Node version 22.4.1 in Dockerfile after build failures related to `node:alpine` being upgraded to 22.5.0.

build: downgrade node from 22.5.0 to 22.4.1

---

app/javascript/controllers/index.js
app/javascript/controllers/scroll_controller.js
app/views/support/cases/case_list/_filters.html.erb

scroll on the last clicked filter upon reloading

feat(crm): scrolling the main page where last filter was select

---

db/migrate/20241001150600_update_support_case_data_to_version_13.rb
db/schema.rb
db/views/support_case_data_v13.sql
spec/models/support/case_spec.rb

Uses optimised SQL code from Prathi to hopefully speed up the download cases csv

2075 - fix(cms): change view to fix download timeout issue

---

app/assets/stylesheets/base/_frontend.scss
app/controllers/support/cases/message_threads_controller.rb
app/controllers/support/cases/messages/replies_controller.rb
app/controllers/tickets/message_threads_controller.rb
app/javascript/components/add-recipients.js
app/models/email/draft.rb
app/models/frameworks/evaluation/email_ticketable.rb
app/models/support/case.rb
app/views/support/cases/message_threads/_recipient_table.html.erb
app/views/support/cases/message_threads/_recipients.html.erb
app/views/support/cases/messages/replies/_form.html.erb
app/views/support/cases/messages/replies/add_recipient.html.erb
app/views/support/cases/messages/replies/edit.html.erb
config/routes.rb
lib/microsoft_graph/client.rb
spec/features/support/emails/agent_can_send_attachments_spec.rb

This change isn't working properly, and is causing replies not to be sent to the person being replied to.
As this code is complicated, untested, and not working, we will revert it until it can be fixed and tested properly.
This reverts #1932 PWNN-1996

fix(cms): Revert broken additional contact emails

---

spec/features/support/case_assignment_spec.rb

The code being tested is mature and not being worked on, but this test fails so often due to JavaScript-related timing issues that it's wasting a lot of time re-running specs on CI.
Revisit if/when we switch from Capybara to Playwright.

Skip very flaky test

---

db/migrate/20241112114859_remove_duplicate_support_agents.rb
db/migrate/20241112123453_normalize_support_agent_email_case.rb
db/migrate/20241125131721_fix_orphaned_json_fake_foreign_keys.rb
db/schema.rb

Fixes exception caused by #1971 where some references to deleted duplicate entries were hidden within JSON data columns.
The two known duplicate entries are updated to their correct values.

Fix JSON fake foreign keys

---

app/controllers/support/cases/tasklists_controller.rb
app/views/support/cases/show.html.erb
app/views/support/cases/show/_tabs.html.erb
app/views/support/cases/show/_tasklist.html.erb
config/locales/en.yml
config/routes.rb
spec/features/support/case_tabs_spec.rb
spec/features/support/case_tasklist_spec.rb
spec/rails_helper.rb

A tasklist tab is needed for the school collab project to show procops what tasks there are to complete for an evaluation. This is only for level 4 and 5 cases. At the moment, it is showing tasks but it is not functional and pages will be added one by one. It is behind a feature flag sc_tasklist_tab so the page is hidden until fully ready for procops.
- Add tasklist tab in the case page for cases that are level 4 or 5
- Add tasks in the tasklist tab as placeholders for future work

SC-80 Add tasklist tab to case

---

doc/release-process.md

Fix a typo, remove some unnecessary steps, and reformat the long lines so it's easier to read locally. (This has no effect on GitHub's rendering of Markdown.)

Tweak release docs

---

app/controllers/support/establishment_groups_controller.rb
app/controllers/support/organisations_controller.rb
app/models/local_authority.rb
app/models/support/category.rb
app/models/support/concerns/scope_active.rb
app/models/support/email_template.rb
app/models/support/establishment_group.rb
app/models/support/organisation.rb
db/migrate/20241127115728_update_archived_columns.rb
db/schema.rb
spec/factories/support/organisation.rb
spec/factories/support/support_establishment_group.rb
spec/features/engagement/create_case_spec.rb
spec/features/specify/framework_requests/create_framework_request_guest_spec.rb
spec/support/shared/user_with_many_orgs.rb

Archived organisations and establishment groups are those that are in our databases but are no longer in the GIAS data download for various reasons, such as a school never opening. We do not want Procurement Operations or school users to be able to select archived schools from any of the dropdowns or school pickers as there should be an alternate correct establishment to choose from.
- Removes archived schools from the selection in the multi school picker
- Removes archived school from the organisation and establishment group searches

2012 - feat(cms): Remove archived establishments from selection options

---

app/controllers/support/cases/evaluation_due_dates_controller.rb
app/forms/support/case_evaluation_due_date_form.rb
app/forms/support/case_evaluation_due_date_form_schema.rb
app/views/support/cases/evaluation_due_dates/edit.html.erb
app/views/support/cases/show/_tasklist.html.erb
config/locales/en.yml
config/locales/validation/support/en.yml
config/routes.rb
db/migrate/20241126122758_add_evaluation_due_date_to_support_cases.rb
db/schema.rb
spec/features/support/agent_can_add_evaluation_due_date_spec.rb
spec/models/support/case_spec.rb

1. app/controllers/support/cases/evaluation_due_dates_controller.rb - Added new controller to update evaluation due date
2. app/models/support/case.rb - Added evaluation due date validation
3. app/views/support/cases/evaluation_due_dates/edit.html.erb - Added new view file to update evaluation due date
4. config/locales/en.yml - Added new language variable
5. config/locales/validation/en.yml - Added nee validation language variable
6. config/routes.rb - Added new route for evaluation due date screen
7. db/migrate/20241126122758_add_evaluation_due_date_to_support_cases.rb - Added new migration file to add new field in support_cases table
8. 9.spec/features/support/agent_can_add_evaluation_due_date_spec.rb- Added new validation spec file for evaluaton due date

SC-107 Set due date 

---

app/controllers/support/cases/document_uploads_controller.rb
app/controllers/support/document_downloads_controller.rb
app/models/support/case.rb
app/models/support/case/document_uploadable.rb
app/models/support/case/document_uploader.rb
app/models/support/case_upload_document.rb
app/views/support/cases/document_uploads/_form.html.erb
app/views/support/cases/document_uploads/_uploaded_documents.html.erb
app/views/support/cases/document_uploads/destroy.html.erb
app/views/support/cases/document_uploads/edit.html.erb
app/views/support/cases/document_uploads/index.html.erb
app/views/support/cases/show/_tasklist.html.erb
config/locales/en.yml
config/locales/validation/support/en.yml
config/routes.rb
db/migrate/20241203125734_add_support_case_upload_documents.rb
db/migrate/20241209104836_add_has_uploaded_documents_to_support_cases.rb
db/schema.rb
spec/features/support/agent_can_upload_evaluation_documents_spec.rb
spec/models/support/case_spec.rb

1. app/controllers/support/cases/document_uploads_controller.rb - Added new document upload controller
2. app/controllers/support/document_downloads_controller.rb - Added new class name in download controller
3. app/models/support/case.rb - Included uploaded document object
4. app/models/support/case/document_uploadable.rb - Added new document uploadable model
5. app/models/support/case/document_uploader.rb - Added new document uploader model
6. app/models/support/case_upload_document.rb - Added new model
7. app/views/support/cases/document_uploads/_form.html.erb - Added new view file
8. app/views/support/cases/document_uploads/_uploaded_documents.html.erb - Added new view file
9. app/views/support/cases/document_uploads/destroy.html.erb - Added new view file for delete screen
10. …

SC-82 Upload Documents (evaluation pack)

---

app/controllers/support/cases/evaluators_controller.rb
app/models/support/evaluator.rb
app/views/support/cases/show/_tasklist.html.erb
config/locales/validation/support/en.yml
spec/features/support/case_tasklist_spec.rb
spec/models/support/evaluator_spec.rb

- Adds the correct link to the add evaluators page
- Changes the status to complete when there is an evaluator added
- Adds back links to the pages
- Adds validation for email format, and custom validation messages

SC-124 Add evaluators link and status change funtionality to tasklist

---

lib/microsoft_graph/application_authenticator.rb

This contains useful information like the fact that keys have expired.
Before:
```
MicrosoftGraph::ApplicationAuthenticator::AuthenticationFailureError: invalid_client
```
After:
```
MicrosoftGraph::ApplicationAuthenticator::AuthenticationFailureError: invalid_client: AADSTS7000222: The provided client secret keys for app '782c68a6-e4db-4d29-802d-2c5570a475a0' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: f6638b43-1c05-4378-99fa-408b31c86200 Correlation ID: 7c8b3745-5f50-49fe-be36-85c786d272a1 Timestamp: 2024-12-16 16:42:16Z
```

Report Azure auth error description

---

app/controllers/support/cases/email_evaluators_controller.rb
app/models/email/template_parser.rb
app/models/support/case.rb
app/services/support/email_evaluators_variable_parser.rb
app/views/support/cases/email_evaluators/_document_list.html.erb
app/views/support/cases/email_evaluators/_email_list.html.erb
app/views/support/cases/email_evaluators/_form.html.erb
app/views/support/cases/email_evaluators/_form_template.html.erb
app/views/support/cases/email_evaluators/edit.html.erb
app/views/support/cases/show/_tasklist.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20241211171744_add_sent_email_to_evaluators_to_case.rb
db/schema.rb
spec/features/support/agent_can_email_to_evaluators_spec.rb
spec/models/support/case_spec.rb

1. app/controllers/support/cases/email_evaluators_controller.rb - Added new controller
2. app/models/email/template_parser.rb - Added new parse variable
3. app/views/support/cases/email_evaluators/_document_list.html.erb - Added new view file to list uploaded documents
4. app/views/support/cases/email_evaluators/_email_list.html.erb - Added new view file to list evaluators
5. app/views/support/cases/email_evaluators/_form.html.erb - Added new form file
6. app/views/support/cases/email_evaluators/_form_template.html.erb - Added new default template file
7.  app/views/support/cases/email_evaluators/edit.html.erb - Added new view file
8. app/views/support/cases/show/_tasklist.html.erb - Updated email evaluator link in task list
9. config/locales/en.yml - added new language variable
10. …

SC-83 Invite evaluators to start evaluation tasks

---

app/controllers/evaluation/application_controller.rb
app/controllers/evaluation/tasks_controller.rb
app/models/support/evaluator.rb
app/views/evaluation/tasks/show.html.erb
config/locales/en.yml
spec/features/evaluation/task_list_spec.rb
spec/support/screenshot_helper.rb

This is a very basic stub page for the evaluator task list so that we have a place to take people when they sign in.
The due date is not filled in as this doesn't yet exist, and there are no task list items.
When you visit the page and you're signed in and an evaluator:
When you are signed in but not an evaluator, you are dumped back to the home page:
We might have to do further work to make the authentication journey work properly end to end once we are emailing evaluators, as the tests don't accurately reflect the real-world sign-in experience.

SC-84 Evaluator task list stub

---

app/controllers/evaluation/download_documents_controller.rb
app/controllers/evaluation/tasks_controller.rb
app/controllers/evaluation/upload_completed_documents_controller.rb
app/controllers/support/cases/document_uploads_controller.rb
app/controllers/support/document_downloads_controller.rb
app/models/support/case.rb
app/models/support/case/document_uploadable.rb
app/models/support/case/document_uploader.rb
app/models/support/evaluators_upload_document.rb
app/presenters/support/case_presenter.rb
app/views/evaluation/download_documents/show.html.erb
app/views/evaluation/tasks/show.html.erb
app/views/evaluation/upload_completed_documents/_form.html.erb
app/views/evaluation/upload_completed_documents/_uploaded_documents.html.erb
app/views/evaluation/upload_completed_documents/destroy.html.erb
app/views/evaluation/upload_completed_documents/show.html.erb
app/views/support/cases/show/_tasklist.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20250116143149_add_support_evaluators_upload_documents.rb
db/migrate/20250117101341_add_has_uploaded_documents_to_support_evalutors.rb
db/migrate/20250131133341_update_has_uploaded_documents_default_value.rb
db/schema.rb
spec/features/evaluation/upload_completed_documents_spec.rb
spec/features/support/agent_can_upload_evaluation_documents_spec.rb

Added new files to upload completed documents
1. app/controllers/evaluation/download_documents_controller.rb - Updated file for evaluation document upload
2. app/controllers/evaluation/upload_completed_documents_controller.rb - Added new controller for evaluation document upload
3. app/models/support/case.rb - Updated file for evaluation document upload
4. app/models/support/case/document_uploadable.rb - Added new function for evaluation document upload
5. app/models/support/case/document_uploader.rb - Added new function for evaluation document upload
6. app/models/support/evaluators_upload_document.rb - Added new model file for evaluation document upload
7. app/views/evaluation/tasks/show.html.erb - Updated file for upload documents link
8. …

SC-86 Evaluator journey: Upload complete evaluation 

---

app/controllers/sessions_controller.rb
spec/controllers/sessions_controller_spec.rb

1. app/controllers/sessions_controller.rb - Added condition to redirect evaluation task list for external user
2. spec/controllers/sessions_controller_spec.rb - Added test case for external user redirect

SC-207 Evaluator Login - External Evaluation user being re-directed to the Specifications dashboard screen

---

app/views/support/cases/show/_tasklist.html.erb

1. app/views/support/cases/show/_tasklist.html.erb -  Added GDS style tag for cannot start status
**Before:** 
**After:**

SC-193 Procurement task list - CSS Cannot start using incorrect GDS tag

---

.github/workflows/ci-full-pipeline.yml
.github/workflows/support-knapsack-generate-json.yml
.github/workflows/support-update-ssl-cert-validation-implementation.yml
spec/features/specify/framework_requests/create_framework_request_guest_spec.rb

Ubuntu 20.04 is being [deprecated] by GitHub, which means that jobs will sporadically and temporarily fail. Switching to ubuntu-latest should fix this and keep the jobs working in the future.
This does not affect the deployed artefacts, as they are built on the Ruby docker containers.
[deprecated]: https://github.com/actions/runner-images/issues/11101

Switch build to ubuntu-latest

---

app/forms/framework_requests/email_form.rb
app/models/case_request.rb
app/models/support/evaluator.rb
app/validators/email_address_validator.rb
config/locales/validation/en.yml
config/locales/validation/support/en.yml
spec/forms/framework_requests/email_form_spec.rb

- Refactored email validation for adding evaluators, framework requests, and creating a new case
- Other similar validation has NOT been changed due to complications with using forms and schemas

SC-150 - Refactor email address validation

---

app/controllers/evaluation/upload_completed_documents_controller.rb
app/models/support/case/notifiable.rb
app/models/support/notification.rb
app/views/support/notifications/topics/_evaluation_documents_uploaded.html.erb
spec/features/evaluation/upload_completed_documents_spec.rb

1. app/controllers/evaluation/upload_completed_documents_controller.rb - Added methods to update notification details
2. app/models/support/case/notifiable.rb - Added a method to update notification details
3. app/models/support/notification.rb - Added new topic enum value
4.  app/views/support/notifications/topics/_evaluation_documents_uploaded.html.erb - Added new file for notification
5. spec/features/evaluation/upload_completed_documents_spec.rb - Added test case to check notification count when evaluation is submitted

SC-213 Add notification list entry Proc Ops when an evaluation is submitted

---

app/services/support/sync_frameworks.rb
spec/services/support/sync_frameworks_spec.rb

1. app/services/support/sync_frameworks.rb -  updated condition to archive framework
2. spec/services/support/sync_frameworks_spec.rb - Added test case to check framework archive changes

SC-131 Activity log created for deleted framework every night

---

app/controllers/usability_surveys_controller.rb
app/helpers/usability_surveys_helper.rb
app/models/usability_survey_response.rb
app/services/url_verifier.rb
app/views/usability_surveys/new.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20250404120000_create_usability_survey_responses.rb
db/schema.rb
spec/features/usability_survey/usability_survey_spec.rb
spec/models/usability_survey_response_spec.rb
spec/rails_helper.rb
spec/requests/usability_survey/usability_survey_flow_spec.rb

This PR adds a new Usability Survey which will be used in the [FABS app](https://github.com/DFE-Digital/find-a-buying-solution/).
- New table, model, controller and form for collecting Usability Survey Responses
- Updated translation file
- URL Verifier to allow safe redirects back to urls provided by FABS 
- Unit, request and feature specs

Add usability survey for FABS

---

.github/workflows/ci-full-pipeline.yml

The build was failing:
AttributeError: Can't get attribute 'NormalizedResponse' on <module 'msal.throttled_http_client' from '/usr/local/lib/python3.10/site-packages/msal/throttled_http_client.py'>
This fixes it by disabling the MSAL HTTP cache. See https://github.com/Azure/azure-cli/issues/31419

Disable MSAL cache to fix build

---

app/helpers/support/sort_helper.rb
app/views/cec/onboarding_cases/case_list/case_panel/_top_right_pane.html.erb
app/views/support/cases/show/_case_details.html.erb
spec/features/cec/case_summary_spec.rb
spec/features/cec/case_tabs_spec.rb

- Adds next key date (that is already in the procops view) to the case details tab, case list summary, and as a sort option to the cec portal

ES-431 Add next key date to cec view

---

app/controllers/energy/tasks_controller.rb
app/controllers/sessions_controller.rb
app/services/energy/emails/school_onboarding_variable_parser.rb
spec/controllers/energy/tasks_controller_spec.rb
spec/controllers/sessions_controller_spec.rb

https://dfedigital.atlassian.net.mcas.ms/browse/ES-335
As part of the energy form started email, when the user click on the link, 
- For the signed in users: It should redirect to task list if the user has selected switching energy type, if switching energy type is not selected then the user will be redirected to switch energy screen. 
- For the non sign-in users: It should redirected to energy sign in page and then goes to task list

ES-335 - fix redirection of form started email link

---

app/services/energy/documents/vat_declaration_form_edf.rb
spec/services/energy/documents/vat_declaration_form_edf_spec.rb

Ticket: [ES-391](https://dfedigital.atlassian.net/browse/ES-391)
- PDG generation
- Auto-Populate EDF Electricity VAT Declaration PDF for Single Schools

 ES-390 | PDF generator, VAT certificates - EDF

---

app/helpers/application_helper.rb
config/locales/en.yml
spec/features/specify/landing/environment_banner_spec.rb
spec/features/specify/steps/checkboxes_spec.rb
spec/features/specify/steps/radios_spec.rb
spec/helpers/specify/application_helper_spec.rb

- Add text to show user the feedback link opens in a new tab but the span is visually hidden within the link so that it is only picked up by assistive technology

ES-481 - Add text to show user the feedback link opens in a new tab

---

app/controllers/concerns/cec_email_template_filters.rb
app/controllers/support/cases/email_templates_controller.rb
app/controllers/support/cases/message_threads_controller.rb
app/controllers/support/management/email_templates_controller.rb
app/forms/support/management/email_template_filter_form.rb
app/forms/support/management/email_template_form.rb
app/javascript/controllers/email_templates_edit_controller.js
app/javascript/controllers/email_templates_edit_controller.test.js
app/models/support/email_template.rb
app/views/support/cases/message_threads/_create_new_message_thread.erb
app/views/support/management/email_templates/form/_form.html.erb
app/views/support/management/email_templates/template_manager/_filters.html.erb
app/views/support/management/email_templates/template_manager/templates/_template_tags.html.erb
config/locales/en.yml
config/support/email_template_groups.yml
spec/features/cec/emails/cec_agent_can_send_new_emails_spec.rb
spec/features/support/management/email_templates/admin_can_create_templates_spec.rb
spec/models/support/email_template_spec.rb
spec/services/support/emails/templates/seed_groups_spec.rb

…lity
[1a97ac0](https://github.com/DFE-Digital/buy-for-your-school/commit/1a97ac09d42280ef05a04ed7de5c2e0db762bbc2) - Updated CEC Email Template Filter files to include Subgroup functionality

ES-529 Create CEC Email Template Filter with Subgroup and Stage Defaults

---

app/controllers/support/cases/summaries_controller.rb
spec/features/support/agent_can_change_case_summary_spec.rb

When a case has a request type of ‘query' rather than 'procurement', it doesn't have a procurement stage title so returns an internal server error. This code removes the condition of looking for the procurement title enquiry. It also adds a small sleep to the test which is flaky to fix that.
- Removes condition for changing to on hold
- Adds small sleep to fix flaky tests

ES-639 Fix error when procurement type is query and changing to level 6

---

app/models/support/case/searchable.rb
app/models/support/concerns/scope_filter_for_search.rb
spec/models/support/case_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/ES-238
This pull request enables users to search for cases using MPRN and MPAN. A new scope has been introduced, as the current case search functionality relies on the support_case_searches SQL view. Consequently, it is not feasible to integrate MPAN/MPRN search directly into the existing Lambda function.

ES-238 | Add ability to search cases by MPRN and MPAN

---

app/models/support/case/email_movable.rb
app/models/support/case/notifiable.rb
app/models/support/notification.rb
app/views/support/notifications/topics/_email_merge.html.erb
spec/features/support/agent_can_move_emails_to_case_spec.rb

[523f88d](https://github.com/DFE-Digital/buy-for-your-school/commit/523f88d430b692527b65d7996395ec4c84b2a546) - Added functionality to notify case owner when email merge to the case

ES-677 - Email Merge functionality to another case is not triggering the notification to the case owner
